from header import *
from header import *
## script_set_prsnt_debug
	# WARNING: this is totally new procedure (not present in native). 1257AD devs
set_prsnt_debug = 	(
	"set_prsnt_debug",
	[
			(position_set_x, pos1, 50),
		#HORIZONTAL
		(position_set_y, pos1, 50),
		(create_text_overlay, reg0, "@50----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 100),
		(create_text_overlay, reg0, "@100----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 200),
		(create_text_overlay, reg0, "@200----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 300),
		(create_text_overlay, reg0, "@300----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 400),
		(create_text_overlay, reg0, "@400----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 500),
		(create_text_overlay, reg0, "@500----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 600),
		(create_text_overlay, reg0, "@600----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 660),
		(create_text_overlay, reg0, "@660----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 700),
		(create_text_overlay, reg0, "@700----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		
		#VERTICAL
		(position_set_y, pos1, 720),
		(position_set_x, pos1, 50),
		(create_text_overlay, reg0, "@050+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 100),
		(create_text_overlay, reg0, "@100+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 150),
		(create_text_overlay, reg0, "@150+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 200),
		(create_text_overlay, reg0, "@200+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 250),
		(create_text_overlay, reg0, "@250+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 300),
		(create_text_overlay, reg0, "@300+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 350),
		(create_text_overlay, reg0, "@350+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 400),
		(create_text_overlay, reg0, "@400+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 450),
		(create_text_overlay, reg0, "@450+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 500),
		(create_text_overlay, reg0, "@500+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 550),
		(create_text_overlay, reg0, "@550+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 600),
		(create_text_overlay, reg0, "@600+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 650),
		(create_text_overlay, reg0, "@650+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 700),
		(create_text_overlay, reg0, "@700+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 750),
		(create_text_overlay, reg0, "@750+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 800),
		(create_text_overlay, reg0, "@800+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 850),
		(create_text_overlay, reg0, "@850+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 900),
		(create_text_overlay, reg0, "@900+", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
	])