from header import *


		# script_set_town_picture
		# WARNING: this is totally new procedure (not present in native). 1257AD devs
		# Input: none
		# Output: none
set_town_picture = (
	"set_town_picture",
			[

		(party_get_slot, ":culture", "$current_town", slot_center_culture),
			(try_begin), #WEST
			(this_or_next|eq, ":culture", fac_culture_finnish),
			(this_or_next|eq, ":culture", fac_culture_mazovian),
			(this_or_next|eq, ":culture", fac_culture_welsh),
			(this_or_next|eq, ":culture", fac_culture_iberian),
			(this_or_next|eq, ":culture", fac_culture_italian),
			(this_or_next|eq, ":culture", fac_culture_nordic),
			(this_or_next|eq, ":culture", fac_culture_gaelic),
			(this_or_next|eq, ":culture", fac_culture_anatolian_christian),
			(this_or_next|eq, ":culture", fac_culture_scotish),
			(eq, ":culture", fac_culture_western),
			(try_begin),
				(is_between, "$current_town", villages_begin, villages_end),
				(set_background_mesh, "mesh_pic_cataholic_village"),
			(else_try),
				(is_between, "$current_town", castles_begin, castles_end),
				(set_background_mesh, "mesh_pic_cataholic_castle"),
			(else_try),
				(set_background_mesh, "mesh_pic_cataholic_town"),
			(try_end),
		(else_try), #BALTIC  
			(this_or_next|eq, ":culture", fac_culture_baltic),
			(eq, ":culture", fac_culture_teutonic),
			(try_begin),
				(is_between, "$current_town", villages_begin, villages_end),
				(set_background_mesh, "mesh_pic_baltic_village"),
			(else_try),
				(is_between, "$current_town", castles_begin, castles_end),
				(set_background_mesh, "mesh_pic_baltic_castle"),
			(else_try),
				(set_background_mesh, "mesh_pic_baltic_town"),
			(try_end),
		(else_try), #ORTHODOX
			(this_or_next|eq, ":culture", fac_culture_serbian),
			(this_or_next|eq, ":culture", fac_culture_balkan),
			(this_or_next|eq, ":culture", fac_culture_rus),
			(this_or_next|eq, ":culture", fac_culture_byzantium),
			(eq, ":culture", fac_culture_mongol),
			(try_begin),
				(is_between, "$current_town", villages_begin, villages_end),
				(set_background_mesh, "mesh_pic_orthodox_village"),
			(else_try),
				(is_between, "$current_town", castles_begin, castles_end),
				(set_background_mesh, "mesh_pic_orthodox_castle"),
			(else_try),
				(set_background_mesh, "mesh_pic_orthodox_town"),
			(try_end),
		(else_try), #MUSLIM  
			(this_or_next|eq, ":culture", fac_culture_marinid),
			(this_or_next|eq, ":culture", fac_culture_mamluke),
			(this_or_next|eq, ":culture", fac_culture_andalus),
			(eq, ":culture", fac_culture_anatolian),
			(try_begin),
				(is_between, "$current_town", villages_begin, villages_end),
				(set_background_mesh, "mesh_pic_muslim_village"),
			(else_try),
				(is_between, "$current_town", castles_begin, castles_end),
				(set_background_mesh, "mesh_pic_muslim_castle"),
			(else_try),
				(set_background_mesh, "mesh_pic_muslim_town"),
			(try_end),
		(else_try),
			(try_begin),
				(is_between, "$current_town", villages_begin, villages_end),
				(set_background_mesh, "mesh_pic_cataholic_village"),
			(else_try),
				(is_between, "$current_town", castles_begin, castles_end),
				(set_background_mesh, "mesh_pic_cataholic_castle"),
			(else_try),
				(set_background_mesh, "mesh_pic_cataholic_town"),
			(try_end),
		(try_end),
		
		#####old
				# (try_begin),
					# (party_get_current_terrain, ":cur_terrain", "$current_town"),
					# (party_slot_eq,"$current_town",slot_party_type, spt_town),
					# (try_begin),
						# (this_or_next|eq, ":cur_terrain", rt_steppe),
						# (this_or_next|eq, ":cur_terrain", rt_steppe_forest),
						# (this_or_next|eq, ":cur_terrain", rt_desert),
						# (             eq, ":cur_terrain", rt_desert_forest),
						# (set_background_mesh, "mesh_pic_towndes"),
					# (else_try),
						# (this_or_next|eq, ":cur_terrain", rt_snow),
						# (             eq, ":cur_terrain", rt_snow_forest),
						# (set_background_mesh, "mesh_pic_townsnow"),
					# (else_try),
						# (set_background_mesh, "mesh_pic_town1"),
					# (try_end),
				# (else_try),
					# (try_begin),
						# (this_or_next|eq, ":cur_terrain", rt_steppe),
						# (this_or_next|eq, ":cur_terrain", rt_steppe_forest),
						# (this_or_next|eq, ":cur_terrain", rt_desert),
						# (             eq, ":cur_terrain", rt_desert_forest),
						# (set_background_mesh, "mesh_pic_castledes"),
					# (else_try),
						# (this_or_next|eq, ":cur_terrain", rt_snow),
						# (             eq, ":cur_terrain", rt_snow_forest),
						# (set_background_mesh, "mesh_pic_castlesnow"),
					# (else_try),
						# (set_background_mesh, "mesh_pic_castle1"),
					# (try_end),
				# (try_end),
		])
