from header import *

#script_spawn_mongols
	# WARNING: this is totally new procedure (not present in native). 1257AD devs
	# INPUT: none
	# OUTPUT: none
	# DESCRIPTION: This script will spawn a camp at each of the monglian faction towns.
spawn_mongols = (
	"spawn_mongols",
		[
			(try_for_range, ":town", centers_begin, centers_end),
			# (store_faction_of_party, ":faction", ":town"),
			# (this_or_next|eq, ":town", "fac_kingdom_3"),
			# (eq, ":town", "fac_kingdom_27"),
			(this_or_next|is_between, ":town", "p_town_3_1", "p_town_4_1"),
			(is_between, ":town", "p_town_27_1", "p_town_28_1"),
			(try_begin),
				(is_between, ":town", "p_town_27_1", "p_town_28_1"),
			(assign, ":faction", "fac_kingdom_27"),
			(else_try),
			(assign, ":faction", "fac_kingdom_3"),
			(try_end),
			#(assign, ":town", "p_town_3_1"),
			#(party_get_slot,":camp",":town",slot_mongol_camp),
			#(le, ":camp", 0),
			
			#(store_random_in_range, ":random", 1, 101),
			#(ge, ":random", 50),
			(set_spawn_radius, 5),
			(spawn_around_party,":town","pt_mongolian_camp"),
			(assign, ":party_id", reg0),
			(party_set_ai_behavior, ":party_id", ai_bhvr_patrol_location),
			(party_set_ai_object, ":party_id", ":town"),
			(party_set_slot, ":party_id", slot_party_ai_object, ":town"),
			(party_set_ai_patrol_radius, ":party_id", 15),
			
			(party_set_slot, ":party_id",slot_mongol_town,":town"),
			(party_set_slot, ":town",slot_mongol_camp,":party_id"),
			(party_set_faction, ":party_id",":faction"),
			(party_set_slot, ":party_id",slot_castle_exterior,"scn_village_mongol"),
			(party_set_slot, ":party_id", slot_feudal_lances, 1),#one lance!
			(party_set_slot, ":party_id", slot_center_culture, "fac_culture_mongol"),
			(party_set_slot, ":party_id",slot_mongol_camp_status, status_stationed),
			(party_set_icon, ":party_id", "icon_camp"),
		(try_end),
		])	  

	#script_cf_spawn_crusaders_and_jihadists
	# WARNING: this is totally new procedure (not present in native). 1257AD devs
	# INPUT: none
	# OUTPUT: none
cf_spawn_crusaders_and_jihadists = (
	"cf_spawn_crusaders_and_jihadists",
		[
		
			(faction_slot_eq, "fac_kingdom_23", slot_faction_state, sfs_active),
		(faction_slot_eq, "fac_kingdom_25", slot_faction_state, sfs_active),
		#jihad
			(assign, ":parties_to_spawn", 2),
		(try_begin),
			(store_num_parties_of_template, ":num_parties", "pt_jihadist_raiders"),
			(lt,":num_parties",":parties_to_spawn"),
				#(call_script, "script_cf_select_random_town_with_faction", "fac_kingdom_25"),
				#(assign, ":town_no", reg0),
			#(gt, ":town_no", 0),
				(assign, ":town_no", "p_town_25_5"), #jerusalem
			
			(set_spawn_radius, 5),
			(spawn_around_party,":town_no","pt_jihadist_raiders"),
			(assign, ":party_id", reg0),
			(party_set_ai_behavior, ":party_id", ai_bhvr_patrol_location),
			(party_set_ai_object, ":party_id", ":town_no"),
			(party_set_slot, ":party_id", slot_party_ai_object, ":town_no"),
			(party_set_ai_patrol_radius, ":party_id", 15),
		 # (party_set_banner_icon, ":party_id", "icon_banner_20"),
		(try_end),
		
		#crusaders
		(assign, ":parties_to_spawn", 4),
		(try_begin),
			(store_num_parties_of_template, ":num_parties", "pt_crusader_raiders"),
			(lt,":num_parties",":parties_to_spawn"),
				#(call_script, "script_cf_select_random_town_with_faction", "fac_kingdom_23"),
				#(assign, ":town_no", reg0),
			#(gt, ":town_no", 0),
				(assign, ":town_no", "p_town_23_1"), #acre
			
			(set_spawn_radius, 5),
			(spawn_around_party,":town_no","pt_crusader_raiders"),
			(assign, ":party_id", reg0),
			(party_set_ai_behavior, ":party_id", ai_bhvr_patrol_location),
			(party_set_ai_object, ":party_id", ":town_no"),
			(party_set_slot, ":party_id", slot_party_ai_object, ":town_no"),
			(party_set_ai_patrol_radius, ":party_id", 15),
			# (party_set_banner_icon, ":party_id", "icon_banner_20"),
		(try_end),
		])

	#script_spawn_balts
	# WARNING: this is totally new procedure (not present in native). 1257AD devs
	# INPUT: none
	# OUTPUT: none
spawn_balts = (
	"spawn_balts",
		[
		#(set_spawn_radius,1),
		
		(assign, ":parties_to_spawn", 3),
		
		(try_begin),
			(store_num_parties_of_template, ":num_parties", "pt_guelphs"),
			(lt,":num_parties",":parties_to_spawn"),
			(faction_slot_eq, "fac_kingdom_40", slot_faction_state, sfs_active),
			(set_spawn_radius, 5),
			(spawn_around_party,"p_town_40_2","pt_guelphs"),
			(assign, ":party_id", reg0),
			(party_set_ai_behavior, ":party_id", ai_bhvr_patrol_location),
			(party_set_ai_object, ":party_id", "p_town_40_2"),
			(party_set_slot, ":party_id", slot_party_ai_object, "p_town_40_2"),
			(party_set_ai_patrol_radius, ":party_id", 10),
			(party_set_banner_icon, ":party_id", "icon_banner_20"),
		(try_end),
		
		(assign, ":parties_to_spawn", 3),
		(try_begin),
			(store_num_parties_of_template, ":num_parties", "pt_ghibellines"),
			(lt,":num_parties",":parties_to_spawn"),
			(faction_slot_eq, "fac_kingdom_41", slot_faction_state, sfs_active),
			(set_spawn_radius, 5),
			(spawn_around_party,"p_town_41_2","pt_ghibellines"),
			(assign, ":party_id", reg0),
			(party_set_ai_behavior, ":party_id", ai_bhvr_patrol_location),
			(party_set_ai_object, ":party_id", "p_town_41_2"),
			(party_set_slot, ":party_id", slot_party_ai_object, "p_town_41_2"),
			(party_set_ai_patrol_radius, ":party_id", 10),
			(party_set_banner_icon, ":party_id", "icon_banner_19"),
		(try_end),
		#tom
		
		(assign, ":parties_to_spawn", 5),
		(try_begin),
			(faction_slot_eq, "fac_kingdom_35", slot_faction_state, sfs_active), #tom
			(store_num_parties_of_template, ":num_parties", "pt_curonians"),
			(lt,":num_parties",":parties_to_spawn"),
			(set_spawn_radius, 5),
			(spawn_around_party,"p_castle_35_1","pt_curonians"),
			(assign, ":party_id", reg0),
			(party_set_ai_behavior, ":party_id", ai_bhvr_patrol_location),
			(party_set_ai_object, ":party_id", "p_castle_35_1"),
			(party_set_slot, ":party_id", slot_party_ai_object, "p_castle_35_1"),
			(party_set_ai_patrol_radius, ":party_id", 15),
		(try_end),
		
		(try_begin),
			(faction_slot_eq, "fac_kingdom_34", slot_faction_state, sfs_active), #tom
			(store_num_parties_of_template, ":num_parties", "pt_prussians"),
			(lt,":num_parties",":parties_to_spawn"),
			(set_spawn_radius, 5),
			(spawn_around_party,"p_castle_34_1","pt_prussians"),
			(assign, ":party_id", reg0),
			(party_set_ai_behavior, ":party_id", ai_bhvr_patrol_party),
			(party_set_ai_object, ":party_id", "p_castle_34_1"),
			(party_set_slot, ":party_id", slot_party_ai_object, "p_castle_34_1"),
			(party_set_ai_patrol_radius, ":party_id", 15),
		(try_end),
		
		(try_begin),
			(faction_slot_eq, "fac_kingdom_36", slot_faction_state, sfs_active), #tom
			(store_num_parties_of_template, ":num_parties", "pt_samogitians"),
			(lt,":num_parties",":parties_to_spawn"),
			(set_spawn_radius, 5),
			(spawn_around_party,"p_castle_36_1","pt_samogitians"),
			(assign, ":party_id", reg0),
			(party_set_ai_behavior, ":party_id", ai_bhvr_patrol_party),
			(party_set_ai_object, ":party_id", "p_castle_36_1"),
			(party_set_slot, ":party_id", slot_party_ai_object, "p_castle_36_1"),
			(party_set_ai_patrol_radius, ":party_id", 15),
		(try_end),
		
		(try_begin),
			(faction_slot_eq, "fac_kingdom_33", slot_faction_state, sfs_active), #tom
			(store_num_parties_of_template, ":num_parties", "pt_yotvingians"),
			(lt,":num_parties",":parties_to_spawn"),
			(set_spawn_radius, 5),
			(spawn_around_party,"p_castle_33_1","pt_yotvingians"),
			(assign, ":party_id", reg0),
			(party_set_ai_behavior, ":party_id", ai_bhvr_patrol_party),
			(party_set_ai_object, ":party_id", "p_castle_33_1"),
			(party_set_slot, ":party_id", slot_party_ai_object, "p_castle_33_1"),
			(party_set_ai_patrol_radius, ":party_id", 15),
		(try_end),
		
		(assign, ":parties_to_spawn", 3),
		(try_begin),
			(faction_slot_eq, "fac_kingdom_37", slot_faction_state, sfs_active), #tom
			(store_num_parties_of_template, ":num_parties", "pt_welsh"),
			(lt,":num_parties",":parties_to_spawn"),
			(set_spawn_radius, 5),
			(spawn_around_party,"p_town_37_1","pt_welsh"),
			(assign, ":party_id", reg0),
			(party_set_ai_behavior, ":party_id", ai_bhvr_patrol_party),
			(party_set_ai_object, ":party_id", "p_town_37_1"),
			(party_set_slot, ":party_id", slot_party_ai_object, "p_town_37_1"),
			(party_set_ai_patrol_radius, ":party_id", 15),
		(try_end),
		
		(assign, ":parties_to_spawn", 2),
		(try_begin),
			(faction_slot_eq, "fac_kingdom_1", slot_faction_state, sfs_active), #tom
			(store_num_parties_of_template, ":num_parties", "pt_teutonic_raiders"),
			(lt,":num_parties",":parties_to_spawn"),
			(set_spawn_radius, 5),
				(call_script, "script_cf_select_random_town_with_faction", "fac_kingdom_1"),
				(assign, ":town_no", reg0),
			(gt, ":town_no", 0),
			(spawn_around_party,":town_no","pt_teutonic_raiders"),
			(assign, ":party_id", reg0),
			(party_set_ai_behavior, ":party_id", ai_bhvr_patrol_party),
			(party_set_ai_object, ":party_id", ":town_no"),
			(party_set_slot, ":party_id", slot_party_ai_object, ":town_no"),
			(party_set_ai_patrol_radius, ":party_id", 15),  
		(try_end),
		
		##making bandits out of destroyed faction troops
		(try_for_parties, ":party"),
			(party_get_template_id, ":template", ":party"),
			(try_begin),
				(eq, ":template", "pt_guelphs"),
			(neg|faction_slot_eq, "fac_kingdom_40", slot_faction_state, sfs_active),
			(party_set_faction, ":party", "fac_deserters"),
			(else_try),
				(eq, ":template", "pt_ghibellines"),
			(neg|faction_slot_eq, "fac_kingdom_41", slot_faction_state, sfs_active),
			(party_set_faction, ":party", "fac_deserters"),
			(else_try),
				(eq, ":template", "pt_curonians"),
			(neg|faction_slot_eq, "fac_kingdom_35", slot_faction_state, sfs_active),
			(party_set_faction, ":party", "fac_deserters"),
			(else_try),
				(eq, ":template", "pt_prussians"),
			(neg|faction_slot_eq, "fac_kingdom_34", slot_faction_state, sfs_active),
			(party_set_faction, ":party", "fac_deserters"),
			(else_try),
				(eq, ":template", "pt_samogitians"),
			(neg|faction_slot_eq, "fac_kingdom_36", slot_faction_state, sfs_active),
			(party_set_faction, ":party", "fac_deserters"),
			(else_try),
				(eq, ":template", "pt_yotvingians"),
			(neg|faction_slot_eq, "fac_kingdom_33", slot_faction_state, sfs_active),
			(party_set_faction, ":party", "fac_deserters"),
			(else_try),
				(eq, ":template", "pt_welsh"),
			(neg|faction_slot_eq, "fac_kingdom_37", slot_faction_state, sfs_active),
			(party_set_faction, ":party", "fac_deserters"),
			(else_try),
				(eq, ":template", "pt_teutonic_raiders"),
			(neg|faction_slot_eq, "fac_kingdom_1", slot_faction_state, sfs_active),
			(party_set_faction, ":party", "fac_deserters"),
			(try_end),
		(try_end),
		
	])

#script_spawn_peasant_rebels
	# WARNING: this is totally new procedure (not present in native). 1257AD devs
	# INPUT: none
	# OUTPUT: none
spawn_peasant_rebels = (
	"spawn_peasant_rebels",
		[
			#TOM NEW
		(store_current_day, ":cur_day"),
		#(try_for_range, ":faction", kingdoms_begin, kingdoms_end),
		(store_num_parties_of_template, ":num_parties", "pt_peasant_rebels_euro"), #limit how many rebels can be about
		(store_random_in_range, ":faction", kingdoms_begin, kingdoms_end),
		(try_begin),
			(faction_get_slot, ":last_rebellion", ":faction", slot_faction_peasant_rebellion_last),
			(store_sub, ":ok_to_rebel", ":cur_day", ":last_rebellion"),
			(ge, ":ok_to_rebel", 30),
			(le, ":num_parties", 9), # 6 rebelions!
			
			(assign, ":fac_towns", 0),
			(assign, ":fac_prosperity", 0),
			(assign, ":fac_average_prosperity", 0),
			(assign, ":lowest_prosperity", 100),
			(assign, ":lowest_prosperity_town", -1),
			(try_for_range, ":cur_town", towns_begin, towns_end),
			(store_faction_of_party, ":cur_fac", ":cur_town"),
			(eq, ":cur_fac", ":faction"),
			(val_add, ":fac_towns", 1),
			(party_get_slot, ":prosperity", ":cur_town", slot_town_prosperity),
			(val_add, ":fac_prosperity", ":prosperity"),
			(lt, ":prosperity", ":lowest_prosperity"),
			(assign, ":lowest_prosperity", ":prosperity"),
			(assign, ":lowest_prosperity_town", ":cur_town"),
			(try_end),
			(gt, ":fac_towns", 0),
			(gt, ":lowest_prosperity_town", 0),
			
			(store_div, ":fac_average_prosperity", ":fac_prosperity", ":fac_towns"),
			(le, ":fac_average_prosperity", 25),
			
			
			(set_spawn_radius,3),
			(assign, ":parties_to_spawn", 3),
			(faction_get_slot, ":village", ":faction", slot_faction_tier_1_troop),
			(faction_get_slot, ":town", ":faction", slot_faction_tier_1_town_troop),
			(faction_get_slot, ":castle", ":faction", slot_faction_tier_1_castle_troop),
			(try_for_range, reg1, 0, ":parties_to_spawn"),
				(spawn_around_party,":lowest_prosperity_town", "pt_peasant_rebels_euro"),
			(assign, ":party_id", reg0),
			(party_set_ai_behavior, ":party_id", ai_bhvr_patrol_party),
			(party_set_ai_object, ":party_id", ":lowest_prosperity_town"),
			(party_set_ai_patrol_radius, ":party_id", 10),
			(str_store_faction_name, s25, ":faction"),
			(party_set_slot, ":party_id", slot_party_ai_object, ":lowest_prosperity_town"),
			(party_add_members, ":party_id", ":castle", 40),
			(party_add_members, ":party_id", ":town", 120),
			(party_add_members, ":party_id", ":village", 240),
			#(party_upgrade_with_xp, ":party_id", 5000, 0),
			(try_end),
			(try_begin),
			(display_message, "@Peasants revolt in areas controlled by the {s25}!", 0xff0000),
			(faction_set_slot, ":faction", slot_faction_peasant_rebellion_last, ":cur_day"),
			(try_end),
		(try_end),		
		#TOM
		##(store_random_in_range, ":faction", fac_kingdom_1, fac_kingdom_28 + 1),
		# (try_for_range, ":faction", kingdoms_begin, kingdoms_end),
			# (assign, ":fac_towns", 0),
			# (assign, ":fac_prosperity", 0),
			
			# (try_for_range, ":cur_town", towns_begin, towns_end),
			# (store_faction_of_party, ":cur_fac", ":cur_town"),
			# (eq, ":cur_fac", ":faction"),
			# (val_add, ":fac_towns", 1),
			# (party_get_slot, ":prosperity", ":cur_town", slot_town_prosperity),
			# (val_add, ":fac_prosperity", ":prosperity"),
			# (try_end),
			
			# (assign, ":fac_average_prosperity", 0),
			# (try_begin),
			# (gt, ":fac_towns", 0),
			# (store_div, ":fac_average_prosperity", ":fac_prosperity", ":fac_towns"),
			# (try_end),
			
			# (set_spawn_radius,1),
			
			# (gt, ":fac_towns", 0),
			
			# (assign, ":parties_to_spawn", 5),
			# (call_script, "script_raf_aor_faction_to_region", ":faction"),
			# (assign, ":region", reg0),
			
			# (try_begin),
			# (eq, ":region", region_nordic),
			# (assign, ":template", "pt_peasant_rebels_nordic"),
			# (else_try),
			# (this_or_next | eq, ":region", region_teutonic),
			# (eq, ":region", region_baltic),
			# (assign, ":template", "pt_peasant_rebels_baltic"),
			# (else_try),
			# (this_or_next | eq, ":region", region_balkan),
			# (this_or_next | eq, ":region", region_byzantine),
			# (eq, ":region", region_eastern),
			# (assign, ":template", "pt_peasant_rebels_eastern"),
			# (else_try),
			# (eq, ":region", region_european),
			# (assign, ":template", "pt_peasant_rebels_euro"),
			# (else_try),  #TOM
			# (eq, ":region", region_scot),
			# (assign, ":template", "pt_peasant_rebels_scot"),
			# (else_try),
			# (eq, ":region", region_latin),
			# (assign, ":template", "pt_peasant_rebels_euro"),
			# (else_try),
			# (this_or_next | eq, ":region", region_anatolian),
			# (eq, ":region", region_mongol),
			# (assign, ":template", "pt_peasant_rebels_mongol"),
			# (else_try),
			# (eq, ":region", region_andalusian),
			# (assign, ":template", "pt_peasant_rebels_andalus"),
			# (else_try),
			# (eq, ":region", region_north_african),
			# (assign, ":template", "pt_peasant_rebels_marinid"),
			# (else_try),
			# (this_or_next | eq, ":region", region_crusaders),
			# (eq, ":region", region_mamluk),
			# (assign, ":template", "pt_peasant_rebels_mamluke"),
			# (try_end),
			
			# (assign, ":spawn_spot", -1),
			# (try_for_range, ":cur_town", towns_begin, towns_end),
			# (store_faction_of_party, ":town_faction", ":cur_town"),
			# (eq, ":town_faction", ":faction"),
			# (assign, ":spawn_spot", ":cur_town"),
			# (try_end),
			
			# (assign, ":message_shown", 0),
			
			# (try_for_range, ":unused", 0, ":parties_to_spawn"),
			# (store_current_day, ":cur_day"),
			# (faction_get_slot, ":last_rebellion", ":faction", slot_faction_peasant_rebellion_last),
			# (store_sub, ":ok_to_rebel", ":cur_day", ":last_rebellion"),
			# (ge, ":ok_to_rebel", 30),
			# (try_begin),
				# (gt, ":fac_average_prosperity", 0),
				# (le, ":fac_average_prosperity", 25),
				# (store_num_parties_of_template, ":num_parties", ":template"),
				# (lt,":num_parties",":parties_to_spawn"),
				# (spawn_around_party,":spawn_spot",":template"),
				# (assign, ":party_id", reg0),
				# (party_set_ai_behavior, ":party_id", ai_bhvr_patrol_party),
				# (party_set_ai_object, ":party_id", ":spawn_spot"),
				# (party_set_ai_patrol_radius, ":party_id", 10),
				# (str_store_faction_name, s25, ":faction"),
				# (party_set_slot, ":party_id", slot_party_ai_object, ":spawn_spot"),
				# (try_begin),
				# (eq, ":message_shown", 0),
				# (display_message, "@Peasants revolt in areas controlled by the {s25}!", 0xff0000),
				# (faction_set_slot, ":faction", slot_faction_peasant_rebellion_last, ":cur_day"),
				# (assign, ":message_shown", 1),
				# (try_end),
			# (try_end),
			# (try_end),
		# (try_end),
		])
	