from header import *


	#script_remove_manor_objects - tommade
	# WARNING: this is totally new procedure (not present in native). 1257AD devs
	# INPUT:none
	# OUTPUT:none
	#description: removes the objects from unique manor scenes which suppose to be not used
remove_manor_objects= (
	"remove_manor_objects",
			[
		(store_current_scene,":scene"),
		(try_begin),
			(eq, ":scene", "scn_manor_fortified_teutonic"),
			(try_begin), #house 1
			(party_slot_eq, "$g_encountered_party", manor_slot_houses, 0),
			(replace_scene_props, "spr_earth_house_c", "spr_empty"),
			(replace_scene_props, "spr_chair_trunk_c", "spr_empty"),
		(try_end),
			(try_begin), #house 2
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_houses, 2),
			(replace_scene_props, "spr_to_fake_house_f", "spr_empty"),
			(replace_scene_props, "spr_passage_house_a", "spr_empty"),
			(replace_scene_props, "spr_chair_trunk_a", "spr_empty"), 
		(try_end),
		(try_begin), #temple
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_Monastery, manor_building_operational),
			(replace_scene_props, "spr_1257_chapel", "spr_empty"),
			(replace_scene_props, "spr_village_wall_a", "spr_empty"),
			(replace_scene_props, "spr_village_wall_b", "spr_empty"),
		(try_end), 
		(try_begin), #marketplace
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_marketplace, manor_building_operational),
			(replace_scene_props, "spr_wooden_stand", "spr_empty"),
			(replace_scene_props, "spr_cart", "spr_empty"),
		(try_end), 
		(try_begin), #tavern
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_tavern, manor_building_operational),
			(replace_scene_props, "spr_to_town_house_u", "spr_empty"),
			(replace_scene_props, "spr_tavern_barrel", "spr_empty"),
			(replace_scene_props, "spr_tavern_sign", "spr_empty"),
		(try_end), 
		(try_begin), #whorehouse
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_whorehouse, manor_building_operational),
			(replace_scene_props, "spr_earth_house_a", "spr_empty"),
			# (replace_scene_props, "spr_tavern_chair_a", "spr_empty"),
			# (replace_scene_props, "spr_tavern_chair_b", "spr_empty"),
		(try_end), 
		(try_begin), #blacksmith
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_blacksmith, manor_building_operational),
			(replace_scene_props, "spr_town_house_aa", "spr_empty"),
			(replace_scene_props, "spr_stand_thatched", "spr_empty"),
			#(replace_scene_props, "spr_smithy_anvil", "spr_empty"),
			(replace_scene_props, "spr_smithy_forge", "spr_empty"),
		(try_end), 
		(try_begin), #weaponsmith
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_weaponsmith, manor_building_operational),
			(replace_scene_props, "spr_gatehouse_new_a", "spr_empty"),
			(replace_scene_props, "spr_smithy_forge", "spr_empty"),
		(try_end), 
		(try_begin), #armor_smith
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_armorsmith, manor_building_operational),
			(replace_scene_props, "spr_town_house_d", "spr_empty"),
			(replace_scene_props, "spr_smithy_grindstone_wheel", "spr_empty"),
		(try_end), 
		(try_begin), #fletcher
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_fletcher, manor_building_operational),
			#(replace_scene_props, "spr_town_house_h", "spr_empty"),
			(replace_scene_props, "spr_arena_archery_target_a", "spr_empty"),
			(replace_scene_props, "spr_archery_target_with_hit_a", "spr_empty"),
		(try_end), 
		(try_begin), #potter
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_potter, manor_building_operational),
			(replace_scene_props, "spr_to_castle_courtyard_house_b", "spr_empty"),
			(replace_scene_props, "spr_cup", "spr_empty"),
			(replace_scene_props, "spr_jug", "spr_empty"),
		(try_end), 
		(try_begin), #baker
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_bakery, manor_building_operational),
			(replace_scene_props, "spr_to_town_house_t", "spr_empty"),
			(replace_scene_props, "spr_bread_a", "spr_empty"),
		(try_end), 
		(try_begin), #butcher
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_butcher, manor_building_operational),
			(replace_scene_props, "spr_to_castle_courtyard_house_c", "spr_empty"),
		(try_end), 
		(try_begin), #brewer
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_brewery, manor_building_operational),
			(replace_scene_props, "spr_brewery_big_bucket", "spr_empty"),
			#(replace_scene_props, "spr_brewery_pool", "spr_empty"),
			(replace_scene_props, "spr_to_courtyard_gate_b", "spr_empty"),
			#(replace_scene_props, "spr_brewery_bucket_platform_b", "spr_empty"),
		(try_end),
		(try_begin), #winery
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_winery, manor_building_operational),
			(replace_scene_props, "spr_to_gatehouse_b", "spr_empty"),
			(replace_scene_props, "spr_winery_middle_barrel", "spr_empty"),
			(replace_scene_props, "spr_winery_wine_press", "spr_empty"),
			(replace_scene_props, "spr_winery_barrel_shelf", "spr_empty"),
		(try_end), 
		(try_begin), #prison
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_prison, manor_building_operational),
			(replace_scene_props, "spr_to_castle_h_house_b", "spr_empty"),
		(try_end), 
		(try_begin), #stables
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_breeder, manor_building_operational),
			(replace_scene_props, "spr_to_castle_h_house_c", "spr_empty"),
			(replace_scene_props, "spr_feeding_trough_a", "spr_empty"),
		(try_end), 
		(try_begin), #linen_workshop
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_linenworkshop, manor_building_operational),
			(replace_scene_props, "spr_to_town_house_y", "spr_empty"),
		(try_end), 
		(try_begin), #wool_workshop
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_woolworkshop, manor_building_operational),
			(replace_scene_props, "spr_to_town_house_r", "spr_empty"),
		(try_end), 
		(try_begin), #tanery
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_tannery, manor_building_operational),
			(replace_scene_props, "spr_to_town_house_w", "spr_empty"),
			(replace_scene_props, "spr_tannery_hide_a", "spr_empty"),
			(replace_scene_props, "spr_to_passage_house_c", "spr_empty"),
		(try_end), 
		(try_begin), #olive press
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_oilmaker, manor_building_operational),
			(replace_scene_props, "spr_to_town_house_z", "spr_empty"),
		(try_end), 
		(try_begin), #walls
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_walls, manor_building_operational),
			(replace_scene_props, "spr_to_castle_gate_house_a", "spr_empty"),
			(replace_scene_props, "spr_to_castle_f_battlement_a", "spr_empty"),
			(replace_scene_props, "spr_to_castle_round_tower_a", "spr_empty"),
		(try_end), 
		(try_begin), #grainfram
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_grainfarm, manor_building_operational),
			(replace_scene_props, "spr_farm_house_a", "spr_empty"),
			# (replace_scene_props, "spr_angry_wheat", "spr_empty"),
			# (replace_scene_props, "spr_cabbage_b", "spr_empty"),
		(try_end), 
		(try_begin), #fruitfarm
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_fruitfarm, manor_building_operational),
			(replace_scene_props, "spr_farm_house_b", "spr_empty"),
		(try_end), 
		(try_begin), #livestockfarm
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_livestock, manor_building_operational),
			(replace_scene_props, "spr_farm_house_c", "spr_empty"),
		(try_end), 
		(try_begin), #fisher
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_fisher, manor_building_operational),
			(replace_scene_props, "spr_village_house_d", "spr_empty"),
			(replace_scene_props, "spr_net_a", "spr_empty"),
			(replace_scene_props, "spr_net_b", "spr_empty"),
		(try_end),  
		(try_begin), #well
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_well, manor_building_operational),
			(replace_scene_props, "spr_water_well_a", "spr_empty"),
		(try_end),
		(else_try),
			#(party_slot_eq, "$g_encountered_party", manor_slot_unique, 1),
		(try_begin), #house 1
			(party_slot_eq, "$g_encountered_party", manor_slot_houses, 0),
			(replace_scene_props, "spr_earth_house_c", "spr_empty"),
		(try_end),
			(try_begin), #house 2
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_houses, 2),
			(replace_scene_props, "spr_village_house_g", "spr_empty"),
			(replace_scene_props, "spr_village_house_h", "spr_empty"),
			(replace_scene_props, "spr_village_house_i", "spr_empty"),
			(replace_scene_props, "spr_village_house_j", "spr_empty"),
			(replace_scene_props, "spr_small_wall_f", "spr_empty"), #ka su situo daryt?
			
			(replace_scene_props, "spr_chair_trunk_c", "spr_empty"),
			(replace_scene_props, "spr_barrel", "spr_empty"),
			(replace_scene_props, "spr_box_a", "spr_empty"),
			(replace_scene_props, "spr_chair_trunk_a", "spr_empty"), 
		(try_end),
		(try_begin), #temple
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_Monastery, manor_building_operational),
			(replace_scene_props, "spr_church_a", "spr_empty"),
			(replace_scene_props, "spr_church_tower_a", "spr_empty"),
		(try_end), 
		(try_begin), #marketplace
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_marketplace, manor_building_operational),
			(replace_scene_props, "spr_wooden_stand", "spr_empty"),
			(replace_scene_props, "spr_cart", "spr_empty"),
		(try_end), 
		(try_begin), #tavern
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_tavern, manor_building_operational),
			(replace_scene_props, "spr_timber_frame_house_b", "spr_empty"),
			(replace_scene_props, "spr_tavern_barrel", "spr_empty"),
			(replace_scene_props, "spr_tavern_sign", "spr_empty"),
		(try_end), 
		(try_begin), #whorehouse
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_whorehouse, manor_building_operational),
			(replace_scene_props, "spr_timber_frame_house_c", "spr_empty"),
			(replace_scene_props, "spr_tavern_chair_a", "spr_empty"),
			(replace_scene_props, "spr_tavern_chair_b", "spr_empty"),
		(try_end), 
		(try_begin), #blacksmith
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_blacksmith, manor_building_operational),
			(replace_scene_props, "spr_town_house_aa", "spr_empty"),
			(replace_scene_props, "spr_stand_thatched", "spr_empty"),
			(replace_scene_props, "spr_smithy_anvil", "spr_empty"),
			(replace_scene_props, "spr_smithy_forge", "spr_empty"),
		(try_end), 
		(try_begin), #weaponsmith
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_weaponsmith, manor_building_operational),
			(replace_scene_props, "spr_town_house_c", "spr_empty"),
			(replace_scene_props, "spr_smithy_grindstone_wheel", "spr_empty"),
		(try_end), 
		(try_begin), #armor_smith
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_armorsmith, manor_building_operational),
			(replace_scene_props, "spr_town_house_d", "spr_empty"),
			(replace_scene_props, "spr_smithy_forge_bellows", "spr_empty"),
		(try_end), 
		(try_begin), #fletcher
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_fletcher, manor_building_operational),
			(replace_scene_props, "spr_town_house_h", "spr_empty"),
			(replace_scene_props, "spr_arena_archery_target_a", "spr_empty"),
			(replace_scene_props, "spr_archery_target_with_hit_a", "spr_empty"),
		(try_end), 
		(try_begin), #potter
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_potter, manor_building_operational),
			(replace_scene_props, "spr_town_house_e", "spr_empty"),
			(replace_scene_props, "spr_table_small", "spr_empty"),
			(replace_scene_props, "spr_village_oven", "spr_empty"),
			(replace_scene_props, "spr_cup", "spr_empty"),
			(replace_scene_props, "spr_jug", "spr_empty"),
		(try_end), 
		(try_begin), #baker
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_bakery, manor_building_operational),
			(replace_scene_props, "spr_town_house_f", "spr_empty"),
			(replace_scene_props, "spr_fireplace_a", "spr_empty"),
			(replace_scene_props, "spr_table_small_b", "spr_empty"),
			(replace_scene_props, "spr_bread_a", "spr_empty"),
		(try_end), 
		(try_begin), #butcher
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_butcher, manor_building_operational),
			(replace_scene_props, "spr_town_house_g", "spr_empty"),
		(try_end), 
		(try_begin), #brewer
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_brewery, manor_building_operational),
			(replace_scene_props, "spr_brewery_big_bucket", "spr_empty"),
			(replace_scene_props, "spr_brewery_pool", "spr_empty"),
			(replace_scene_props, "spr_town_house_o", "spr_empty"),
			(replace_scene_props, "spr_brewery_bucket_platform_b", "spr_empty"),
		(try_end),
		(try_begin), #winery
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_winery, manor_building_operational),
			(replace_scene_props, "spr_town_house_za", "spr_empty"),
			(replace_scene_props, "spr_winery_middle_barrel", "spr_empty"),
			(replace_scene_props, "spr_winery_wine_press", "spr_empty"),
			(replace_scene_props, "spr_winery_wine_cart_loaded", "spr_empty"),
			(replace_scene_props, "spr_winery_wine_cart_small_loaded", "spr_empty"),
		(try_end), 
		(try_begin), #prison
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_prison, manor_building_operational),
			(replace_scene_props, "spr_torture_tool_a", "spr_empty"),
			(replace_scene_props, "spr_torture_tool_b", "spr_empty"),
			(replace_scene_props, "spr_torture_tool_c", "spr_empty"),
			(replace_scene_props, "spr_castle_courtyard_house_a", "spr_empty"),
		(try_end), 
		(try_begin), #stables
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_breeder, manor_building_operational),
			(replace_scene_props, "spr_village_shed_b", "spr_empty"),
			(replace_scene_props, "spr_village_stable_a", "spr_empty"),
			(replace_scene_props, "spr_open_stable_a", "spr_empty"),
			(replace_scene_props, "spr_open_stable_b", "spr_empty"),
			(replace_scene_props, "spr_feeding_trough_a", "spr_empty"),
		(try_end), 
		(try_begin), #linen_workshop
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_linenworkshop, manor_building_operational),
			(replace_scene_props, "spr_town_house_y", "spr_empty"),
		(try_end), 
		(try_begin), #wool_workshop
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_woolworkshop, manor_building_operational),
			(replace_scene_props, "spr_town_house_z", "spr_empty"),
		(try_end), 
		(try_begin), #tanery
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_tannery, manor_building_operational),
			(replace_scene_props, "spr_town_house_i", "spr_empty"),
			(replace_scene_props, "spr_tannery_hide_a", "spr_empty"),
			(replace_scene_props, "spr_tannery_hide_b", "spr_empty"),
			(replace_scene_props, "spr_tannery_pools_a", "spr_empty"),
			(replace_scene_props, "spr_tannery_pools_b", "spr_empty"),
		(try_end), 
		(try_begin), #olive press
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_oilmaker, manor_building_operational),
			(replace_scene_props, "spr_town_house_a", "spr_empty"),
		(try_end), 
		(try_begin), #walls
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_walls, manor_building_operational),
			(replace_scene_props, "spr_castle_f_battlement_a", "spr_empty"),
			(replace_scene_props, "spr_castle_gate_house_a", "spr_empty"),
		(try_end), 
		(try_begin), #grainfram
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_grainfarm, manor_building_operational),
			(replace_scene_props, "spr_farm_house_a", "spr_empty"),
			(replace_scene_props, "spr_angry_wheat", "spr_empty"),
			(replace_scene_props, "spr_cabbage_b", "spr_empty"),
		(try_end), 
		(try_begin), #fruitfarm
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_fruitfarm, manor_building_operational),
			(replace_scene_props, "spr_farm_house_b", "spr_empty"),
		(try_end), 
		(try_begin), #livestockfarm
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_livestock, manor_building_operational),
			(replace_scene_props, "spr_farm_house_c", "spr_empty"),
		(try_end), 
		(try_begin), #fisher
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_fisher, manor_building_operational),
			(replace_scene_props, "spr_earth_house_b", "spr_empty"),
			(replace_scene_props, "spr_net_a", "spr_empty"),
			(replace_scene_props, "spr_net_b", "spr_empty"),
		(try_end),  
		(try_begin), #well
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_well, manor_building_operational),
			(replace_scene_props, "spr_water_well_a", "spr_empty"),
		(try_end),
	(try_end),	
		
	#tier 2 goods - seperate for aditional cultures
	(try_begin),
		(party_slot_eq, "$g_encountered_party", manor_slot_marketplace, manor_building_operational),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_fisher, manor_building_operational),
			(replace_scene_items_with_scene_props,"itm_smoked_fish","spr_empty"),
		(try_end),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_oilmaker, manor_building_operational),
			(replace_scene_items_with_scene_props,"itm_oil","spr_empty"),
		(try_end),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_potter, manor_building_operational),
			(replace_scene_items_with_scene_props,"itm_pottery","spr_empty"),
		(try_end),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_linenworkshop, manor_building_operational),
			(replace_scene_items_with_scene_props,"itm_linen","spr_empty"),
		(try_end),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_woolworkshop, manor_building_operational),
			(replace_scene_items_with_scene_props,"itm_wool_cloth","spr_empty"),
		(try_end),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_blacksmith, manor_building_operational),
			(replace_scene_items_with_scene_props,"itm_tools","spr_empty"),
		(try_end),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_tannery, manor_building_operational),
			(replace_scene_items_with_scene_props,"itm_raw_leather","spr_empty"),
			(replace_scene_items_with_scene_props,"itm_leatherwork","spr_empty"),
		(try_end),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_winery, manor_building_operational),
			(replace_scene_items_with_scene_props,"itm_wine","spr_empty"), 
		(replace_scene_items_with_scene_props,"itm_quest_wine","spr_empty"),
		(try_end),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_brewery, manor_building_operational),
			(replace_scene_items_with_scene_props,"itm_ale","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_quest_ale","spr_empty"),
		(try_end),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_butcher, manor_building_operational),
			(replace_scene_items_with_scene_props,"itm_dried_meat","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_sausages","spr_empty"),
		(try_end),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_bakery, manor_building_operational),
			(replace_scene_items_with_scene_props,"itm_bread","spr_empty"),
		(try_end),
		
		##traders
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_trader, "trp_manor_trader_furs"), 
			(replace_scene_items_with_scene_props,"itm_furs","spr_empty"),
		(try_end),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_trader, "trp_manor_trader_salt"), 
			(replace_scene_items_with_scene_props,"itm_salt","spr_empty"),
		(try_end),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_trader, "trp_manor_trader_silk"),  
			(replace_scene_items_with_scene_props,"itm_raw_silk","spr_empty"),
		(try_end),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_trader, "trp_manor_trader_dyes"), 
			(replace_scene_items_with_scene_props,"itm_raw_dyes","spr_empty"),
		(try_end),
		(try_begin),
			(neg|party_slot_eq, "$g_encountered_party", manor_slot_trader, "trp_manor_trader_spice"), 
			(replace_scene_items_with_scene_props,"itm_spice","spr_empty"),
		(try_end),
	(else_try),
		#tier 1 goods
		(replace_scene_items_with_scene_props,"itm_grain","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_honey","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_cabbages","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_apples","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_wool","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_butter","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_cheese","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_cattle_meat","spr_empty"),
			
		(replace_scene_items_with_scene_props,"itm_smoked_fish","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_oil","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_pottery","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_linen","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_wool_cloth","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_tools","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_raw_leather","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_leatherwork","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_wine","spr_empty"), 
		(replace_scene_items_with_scene_props,"itm_quest_wine","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_ale","spr_empty"),
			(replace_scene_items_with_scene_props,"itm_quest_ale","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_dried_meat","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_sausages","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_bread","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_furs","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_salt","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_raw_silk","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_raw_dyes","spr_empty"),
		(replace_scene_items_with_scene_props,"itm_spice","spr_empty"),
	(try_end),

		])


	
	#script_manor_set_unique_scene
	# WARNING: this is totally new procedure (not present in native). 1257AD devs
	# NOTE: modded2x: might be cool to alter the terrain algorithms
	#input:manor_party_id, center
	#output: none
	#description: sets the manor scene based on it's terrain type
manor_set_unique_scene = (
	"manor_set_unique_scene",
		[
		(store_script_param, ":manor_party_id", 1),
		(store_script_param, ":center", 2),
		(party_get_slot, ":culture", ":center", slot_center_culture),
		
		(party_get_current_terrain, ":terrain", ":manor_party_id"),
		(try_begin),
			(this_or_next|eq, ":culture", "fac_culture_finnish"),
			(this_or_next|eq, ":culture", "fac_culture_mazovian"),
			(this_or_next|eq, ":culture", "fac_culture_teutonic"),
			(eq, ":culture", "fac_culture_baltic"),
			(party_set_slot, ":manor_party_id", slot_castle_exterior, "scn_manor_fortified_teutonic"),
		(else_try),
			(this_or_next|eq, ":terrain", rt_snow),
			(eq, ":terrain", rt_snow_forest),
			(party_set_slot, ":manor_party_id", slot_castle_exterior, "scn_manor_fortified_euro_snow"),
		(else_try),
			(this_or_next|eq, ":terrain", rt_desert),
			(eq, ":terrain", rt_desert_forest),
			(party_set_slot, ":manor_party_id", slot_castle_exterior, "scn_manor_fortified_euro_desert"),
		(else_try),
			(this_or_next|eq, ":terrain", rt_steppe),
			(eq, ":terrain", rt_steppe_forest),
			(party_set_slot, ":manor_party_id", slot_castle_exterior, "scn_manor_fortified_euro_steppe"),
		(else_try),
			(party_set_slot, ":manor_party_id", slot_castle_exterior, "scn_manor_fortified_euro_plains"),
		(try_end),
		])