from header import * 
#script_raf_set_troop_classes
		# WARNING: this is totally new procedure (not present in native). 1257AD devs
		#INPUT: none
		#OUTPUT: none
raf_set_troop_classes = (
	"raf_set_troop_classes",
			[
			# (troop_set_class, "trp_euro_spearman_1", grc_archers),
			# (troop_set_class, "trp_euro_spearman_2", grc_archers),
			# (troop_set_class, "trp_euro_spearman_3", grc_archers),
			# (troop_set_class, "trp_mercenary_veteran_spearman", grc_archers),
			# (troop_set_class, "trp_teutonic_veteran_spearman", grc_archers),
			# (troop_set_class, "trp_rus_town_3_2", grc_archers),
			# (troop_set_class, "trp_nordic_spearman", grc_archers),
			# (troop_set_class, "trp_nordic_veteran_spearman", grc_archers),
			# (troop_set_class, "trp_balt_spearman", grc_archers),
			# (troop_set_class, "trp_balt_veteran_spearman", grc_archers),
			# (troop_set_class, "trp_templar_veteran_spearman", grc_archers),
			# (troop_set_class, "trp_hospitaller_veteran_spearman", grc_archers),
			# (troop_set_class, "trp_marinid_levy_spearman", grc_archers),
			# (troop_set_class, "trp_mamluke_spearman", grc_archers),
			# (troop_set_class, "trp_iberian_veteran_spearman", grc_archers),
			# (troop_set_class, "trp_andalus_spearman_1", grc_archers),
			# (troop_set_class, "trp_andalus_spearman_2", grc_archers),
			# (troop_set_class, "trp_andalus_spearman_3", grc_archers),
			# (troop_set_class, "trp_gaelic_spearman_1", grc_archers),
			# (troop_set_class, "trp_gaelic_spearman_2", grc_archers),
			# (troop_set_class, "trp_merc_gaelic_spearman", grc_archers),
			# (troop_set_class, "trp_anatolian_christian_spearman_1", grc_archers),
			# (troop_set_class, "trp_anatolian_christian_spearman_2", grc_archers),
			# (troop_set_class, "trp_scottish_forinsec_spearman", grc_archers),
			# (troop_set_class, "trp_scottish_forinsec_spearman", grc_archers),
			#tom
			# (troop_set_class, "trp_euro_spearman_1", grc_spearmen),
			# (troop_set_class, "trp_euro_spearman_2", grc_spearmen),
			# (troop_set_class, "trp_euro_spearman_3", grc_spearmen),
			# (troop_set_class, "trp_mercenary_veteran_spearman", grc_spearmen),
			# (troop_set_class, "trp_teu_town_2_1", grc_spearmen),
			# (troop_set_class, "trp_teu_town_3_1", grc_spearmen),
			# (troop_set_class, "trp_teu_town_4_1", grc_spearmen),
			# (troop_set_class, "trp_rus_town_3_2", grc_spearmen),
			# (troop_set_class, "trp_nordic_spearman", grc_spearmen),
			# (troop_set_class, "trp_nordic_veteran_spearman", grc_spearmen),
			# (troop_set_class, "trp_balt_spearman", grc_spearmen),
			# (troop_set_class, "trp_balt_veteran_spearman", grc_spearmen),
			# (troop_set_class, "trp_marinid_levy_spearman", grc_spearmen),
			# (troop_set_class, "trp_mamluke_spearman_1", grc_spearmen),
			# (troop_set_class, "trp_mamluke_spearman_2", grc_spearmen),
			# (troop_set_class, "trp_mamluke_spearman_3", grc_spearmen),
			# (troop_set_class, "trp_iberian_veteran_spearman", grc_spearmen),
			# (troop_set_class, "trp_andalus_spearman_1", grc_spearmen),
			# (troop_set_class, "trp_andalus_spearman_2", grc_spearmen),
			# (troop_set_class, "trp_andalus_spearman_3", grc_spearmen),
			# (troop_set_class, "trp_gaelic_spearman_1", grc_spearmen),
			# (troop_set_class, "trp_gaelic_spearman_2", grc_spearmen),
			# (troop_set_class, "trp_merc_gaelic_spearman", grc_spearmen),
			# (troop_set_class, "trp_anatolian_christian_spearman_1", grc_spearmen),
			# (troop_set_class, "trp_anatolian_christian_spearman_2", grc_spearmen),
			# (troop_set_class, "trp_scottish_forinsec_spearman", grc_spearmen),
			# (troop_set_class, "trp_scottish_forinsec_spearman", grc_spearmen),
			
			#(str_store_string, s21, "@Spearmen"),
			#(class_set_name, grc_spearmen, s21),
			
			(troop_set_class, "trp_euro_spearman_1", grc_infantry),
			(troop_set_class, "trp_euro_spearman_2", grc_infantry),
			(troop_set_class, "trp_euro_spearman_3", grc_infantry),
			#(troop_set_class, "trp_mercenary_veteran_spearman", grc_infantry),
			(troop_set_class, "trp_teu_town_2_1", grc_infantry),
			(troop_set_class, "trp_teu_town_3_1", grc_infantry),
			(troop_set_class, "trp_teu_town_4_1", grc_infantry),
			(troop_set_class, "trp_rus_town_3_2", grc_infantry),
			(troop_set_class, "trp_nordic_spearman", grc_infantry),
			(troop_set_class, "trp_nordic_veteran_spearman", grc_infantry),
			(troop_set_class, "trp_balt_spearman", grc_infantry),
			(troop_set_class, "trp_balt_veteran_spearman", grc_infantry),
			(troop_set_class, "trp_marinid_levy_spearman", grc_infantry),
			# (troop_set_class, "trp_mamluke_spearman_1", grc_infantry),
			# (troop_set_class, "trp_mamluke_spearman_2", grc_infantry),
			# (troop_set_class, "trp_mamluke_spearman_3", grc_infantry),
			(troop_set_class, "trp_iberian_veteran_spearman", grc_infantry),
			(troop_set_class, "trp_andalus_spearman_1", grc_infantry),
			(troop_set_class, "trp_andalus_spearman_2", grc_infantry),
			(troop_set_class, "trp_andalus_spearman_3", grc_infantry),
			(troop_set_class, "trp_gaelic_spearman_1", grc_infantry),
			(troop_set_class, "trp_gaelic_spearman_2", grc_infantry),
			(troop_set_class, "trp_merc_gaelic_spearman", grc_infantry),
			(troop_set_class, "trp_anatolian_christian_spearman_1", grc_infantry),
			(troop_set_class, "trp_anatolian_christian_spearman_2", grc_infantry),
			(troop_set_class, "trp_scottish_forinsec_spearman", grc_infantry),
			(troop_set_class, "trp_scottish_forinsec_spearman", grc_infantry),
			#tom
			
			(troop_set_class, "trp_tatar_veteran_horse_archer", grc_horse_archers),
			(troop_set_class, "trp_tatar_horse_archer", grc_horse_archers),
			(troop_set_class, "trp_tatar_horseman", grc_horse_archers),
			(troop_set_class, "trp_tatar_skirmisher", grc_horse_archers),
			(troop_set_class, "trp_cuman_veteran_horse_archer", grc_horse_archers),
			(troop_set_class, "trp_cuman_horse_archer", grc_horse_archers),
			(troop_set_class, "trp_cuman_horseman", grc_horse_archers),
			(troop_set_class, "trp_cuman_skirmisher", grc_horse_archers),
			(troop_set_class, "trp_cuman_tribesman", grc_horse_archers),
			(troop_set_class, "trp_rus_horse_1", grc_horse_archers),
			# (troop_set_class, "trp_mamluke_turkoman", grc_horse_archers),
			# (troop_set_class, "trp_mamluke_light_horse_archer", grc_horse_archers),
			# (troop_set_class, "trp_mamluke_medium_horse_archer", grc_horse_archers),
			# (troop_set_class, "trp_mamluke_heavy_horse_archer", grc_horse_archers),
			# (troop_set_class, "trp_mamluke_elite_horse_archer", grc_horse_archers),
			# (troop_set_class, "trp_byz_castle_1", grc_horse_archers),
			(troop_set_class, "trp_byz_castle_2", grc_horse_archers),
			(troop_set_class, "trp_andalus_horse_1", grc_horse_archers),
			(troop_set_class, "trp_andalus_horse_1", grc_horse_archers),
			(troop_set_class, "trp_anatolian_turkoman_1", grc_horse_archers),
			(troop_set_class, "trp_anatolian_turkoman_2", grc_horse_archers),
			# (troop_set_class, "trp_teu_balt_3", grc_horse_archers),
			(troop_set_class, "trp_crusader_turkopole", grc_horse_archers),
			(troop_set_class, "trp_merc_sicily_horse_archer_1", grc_horse_archers),
			(troop_set_class, "trp_merc_sicily_horse_archer_2", grc_horse_archers),
			
			
			(str_store_string, s21, "@Horse Archers"),
			(class_set_name, grc_horse_archers, s21),
			
			
			(troop_set_class, "trp_marinid_village_rabble", grc_infantry),
			(troop_set_class, "trp_marinid_skirmishers", grc_infantry),
			(troop_set_class, "trp_marinid_javelin_infantry", grc_infantry),
			(troop_set_class, "trp_byz_village_2", grc_infantry),
			(troop_set_class, "trp_iberian_village_skirmisher", grc_infantry),
			(troop_set_class, "trp_teu_balt_1", grc_infantry),
			(troop_set_class, "trp_teu_balt_2", grc_infantry),
			(troop_set_class, "trp_balkan_vil_3_1_1", grc_infantry),
			(troop_set_class, "trp_balt_skirmisher", grc_infantry),
			(troop_set_class, "trp_balt_jav", grc_infantry),
			(troop_set_class, "trp_balt_veteran_jav", grc_infantry),
			#(troop_set_class, "trp_balt_jav_sergeant", grc_infantry), Tom
			(troop_set_class, "trp_merc_almogabar", grc_infantry),
			(troop_set_class, "trp_byz_village_3_1", grc_infantry),
			(troop_set_class, "trp_byz_village_4_1", grc_infantry),
			(troop_set_class, "trp_balkan_vil_4_1_1", grc_infantry),
			(troop_set_class, "trp_balkan_vil_4_1_1", grc_infantry),
			
			(troop_set_class, "trp_marinid_mounted_skirmisher_1", grc_cavalry),
			(troop_set_class, "trp_marinid_mounted_skirmisher_2", grc_cavalry),
			(troop_set_class, "trp_marinid_mounted_skirmisher_3", grc_cavalry),
			
			(troop_set_class, "trp_balt_mounted_skirmisher", grc_cavalry),
			(troop_set_class, "trp_balt_light_cavalry", grc_cavalry),
			(troop_set_class, "trp_balt_medium_cavalry", grc_cavalry),
			
			#tom
			(try_for_range, ":troop", lords_begin, lords_end),
				(troop_set_class, ":troop", grc_cavalry),
			(try_end),
			#tom
			])
