from header import *

# script_team_give_order_from_order_panel
		# Input: arg1 = leader_agent_no, arg2 = class_no
		# Output: none
team_give_order_from_order_panel = (
	"team_give_order_from_order_panel",
			[(store_script_param_1, ":leader_agent_no"),
				(store_script_param_2, ":order"),
				(agent_get_team, ":team_no", ":leader_agent_no"),
				(set_show_messages, 0),
				(try_begin),
					(eq, "$g_formation_group0_selected", 1),
					(team_give_order, ":team_no", 0, ":order"),
				(try_end),
				(try_begin),
					(eq, "$g_formation_group1_selected", 1),
					(team_give_order, ":team_no", 1, ":order"),
				(try_end),
				(try_begin),
					(eq, "$g_formation_group2_selected", 1),
					(team_give_order, ":team_no", 2, ":order"),
				(try_end),
				(try_begin),
					(eq, "$g_formation_group3_selected", 1),
					(team_give_order, ":team_no", 3, ":order"),
				(try_end),
				(try_begin),
					(eq, "$g_formation_group4_selected", 1),
					(team_give_order, ":team_no", 4, ":order"),
				(try_end),
				(try_begin),
					(eq, "$g_formation_group5_selected", 1),
					(team_give_order, ":team_no", 5, ":order"),
				(try_end),
				(try_begin),
					(eq, "$g_formation_group6_selected", 1),
					(team_give_order, ":team_no", 6, ":order"),
				(try_end),
				(try_begin),
					(eq, "$g_formation_group7_selected", 1),
					(team_give_order, ":team_no", 7, ":order"),
				(try_end),
				(try_begin),
					(eq, "$g_formation_group8_selected", 1),
					(team_give_order, ":team_no", 8, ":order"),
				(try_end),
				
				(try_begin),
					(eq, ":order", mordr_hold),
					(agent_get_position, pos1, ":leader_agent_no"),
					(try_begin),
						(eq, "$g_formation_group0_selected", 1),
						(team_set_order_position, ":team_no", 0, pos1),
					(try_end),
					(try_begin),
						(eq, "$g_formation_group1_selected", 1),
						(team_set_order_position, ":team_no", 1, pos1),
					(try_end),
					(try_begin),
						(eq, "$g_formation_group2_selected", 1),
						(team_set_order_position, ":team_no", 2, pos1),
					(try_end),
					(try_begin),
						(eq, "$g_formation_group3_selected", 1),
						(team_set_order_position, ":team_no", 3, pos1),
					(try_end),
					(try_begin),
						(eq, "$g_formation_group4_selected", 1),
						(team_set_order_position, ":team_no", 4, pos1),
					(try_end),
					(try_begin),
						(eq, "$g_formation_group5_selected", 1),
						(team_set_order_position, ":team_no", 5, pos1),
					(try_end),
					(try_begin),
						(eq, "$g_formation_group6_selected", 1),
						(team_set_order_position, ":team_no", 6, pos1),
					(try_end),
					(try_begin),
						(eq, "$g_formation_group7_selected", 1),
						(team_set_order_position, ":team_no", 7, pos1),
					(try_end),
					(try_begin),
						(eq, "$g_formation_group8_selected", 1),
						(team_set_order_position, ":team_no", 8, pos1),
					(try_end),
				(try_end),
				(set_show_messages, 1),
		])
		
		# script_update_order_panel
		# some UI stuffs in battle pane during battle, might b interesting
		# WARNING : modified by 1257AD devs
		# Input: arg1 = team_no
		# Output: none
update_order_panel = (
	"update_order_panel",
			[(store_script_param_1, ":team_no"),
				(set_fixed_point_multiplier, 1000),
				
				#ozan added
				(try_begin),
					(eq, "$group0_has_troops", 1),
					(call_script, "script_store_movement_order_name_to_s1", ":team_no", 0),
					(overlay_set_text, "$g_presentation_but0_movement", s1),
					(call_script, "script_store_riding_order_name_to_s1", ":team_no", 0),
					(overlay_set_text, "$g_presentation_but0_riding", s1),
					(call_script, "script_store_weapon_usage_order_name_to_s1", ":team_no", 0),
					(overlay_set_text, "$g_presentation_but0_weapon_usage", s1),
				(try_end),
				(try_begin),
					(eq, "$group1_has_troops", 1),
					(call_script, "script_store_movement_order_name_to_s1", ":team_no", 1),
					(overlay_set_text, "$g_presentation_but1_movement", s1),
					(call_script, "script_store_riding_order_name_to_s1", ":team_no", 1),
					(overlay_set_text, "$g_presentation_but1_riding", s1),
					(call_script, "script_store_weapon_usage_order_name_to_s1", ":team_no", 1),
					(overlay_set_text, "$g_presentation_but1_weapon_usage", s1),
				(try_end),
				(try_begin),
					(eq, "$group2_has_troops", 1),
					(call_script, "script_store_movement_order_name_to_s1", ":team_no", 2),
					(overlay_set_text, "$g_presentation_but2_movement", s1),
					(call_script, "script_store_riding_order_name_to_s1", ":team_no", 2),
					(overlay_set_text, "$g_presentation_but2_riding", s1),
					(call_script, "script_store_weapon_usage_order_name_to_s1", ":team_no", 2),
					(overlay_set_text, "$g_presentation_but2_weapon_usage", s1),
				(try_end),
				(try_begin),
					(eq, "$group3_has_troops", 1),
					(call_script, "script_store_movement_order_name_to_s1", ":team_no", 3),
					(overlay_set_text, "$g_presentation_but3_movement", s1),
					(call_script, "script_store_riding_order_name_to_s1", ":team_no", 3),
					(overlay_set_text, "$g_presentation_but3_riding", s1),
					(call_script, "script_store_weapon_usage_order_name_to_s1", ":team_no", 3),
					(overlay_set_text, "$g_presentation_but3_weapon_usage", s1),
				(try_end),
				(try_begin),
					(eq, "$group4_has_troops", 1),
					(call_script, "script_store_movement_order_name_to_s1", ":team_no", 4),
					(overlay_set_text, "$g_presentation_but4_movement", s1),
					(call_script, "script_store_riding_order_name_to_s1", ":team_no", 4),
					(overlay_set_text, "$g_presentation_but4_riding", s1),
					(call_script, "script_store_weapon_usage_order_name_to_s1", ":team_no", 4),
					(overlay_set_text, "$g_presentation_but4_weapon_usage", s1),
				(try_end),
				(try_begin),
					(eq, "$group5_has_troops", 1),
					(call_script, "script_store_movement_order_name_to_s1", ":team_no", 5),
					(overlay_set_text, "$g_presentation_but5_movement", s1),
					(call_script, "script_store_riding_order_name_to_s1", ":team_no", 5),
					(overlay_set_text, "$g_presentation_but5_riding", s1),
					(call_script, "script_store_weapon_usage_order_name_to_s1", ":team_no", 5),
					(overlay_set_text, "$g_presentation_but5_weapon_usage", s1),
				(try_end),
				(try_begin),
					(eq, "$group6_has_troops", 1),
					(call_script, "script_store_movement_order_name_to_s1", ":team_no", 6),
					(overlay_set_text, "$g_presentation_but6_movement", s1),
					(call_script, "script_store_riding_order_name_to_s1", ":team_no", 6),
					(overlay_set_text, "$g_presentation_but6_riding", s1),
					(call_script, "script_store_weapon_usage_order_name_to_s1", ":team_no", 6),
					(overlay_set_text, "$g_presentation_but6_weapon_usage", s1),
				(try_end),
				(try_begin),
					(eq, "$group7_has_troops", 1),
					(call_script, "script_store_movement_order_name_to_s1", ":team_no", 7),
					(overlay_set_text, "$g_presentation_but7_movement", s1),
					(call_script, "script_store_riding_order_name_to_s1", ":team_no", 7),
					(overlay_set_text, "$g_presentation_but7_riding", s1),
					(call_script, "script_store_weapon_usage_order_name_to_s1", ":team_no", 7),
					(overlay_set_text, "$g_presentation_but7_weapon_usage", s1),
				(try_end),
				(try_begin),
					(eq, "$group8_has_troops", 1),
					(call_script, "script_store_movement_order_name_to_s1", ":team_no", 8),
					(overlay_set_text, "$g_presentation_but8_movement", s1),
					(call_script, "script_store_riding_order_name_to_s1", ":team_no", 8),
					(overlay_set_text, "$g_presentation_but8_riding", s1),
					(call_script, "script_store_weapon_usage_order_name_to_s1", ":team_no", 8),
					(overlay_set_text, "$g_presentation_but8_weapon_usage", s1),
				(try_end),
				
				#ozan added
				(assign, ":stat_position_y", 660),
				(try_begin),
					(position_set_y, pos1, ":stat_position_y"),
					(eq, "$group0_has_troops", 1),
					(position_set_x, pos1, 270),
					(overlay_set_position, "$g_presentation_but0_movement", pos1),
					(position_set_x, pos1, 410),
					(overlay_set_position, "$g_presentation_but0_riding", pos1),
					(position_set_x, pos1, 550),
					(overlay_set_position, "$g_presentation_but0_weapon_usage", pos1),
					(val_add, ":stat_position_y", -40),
				(try_end),
				(try_begin),
					(position_set_y, pos1, ":stat_position_y"),
					(eq, "$group1_has_troops", 1),
					(position_set_x, pos1, 270),
					(overlay_set_position, "$g_presentation_but1_movement", pos1),
					(position_set_x, pos1, 410),
					(overlay_set_position, "$g_presentation_but1_riding", pos1),
					(position_set_x, pos1, 550),
					(overlay_set_position, "$g_presentation_but1_weapon_usage", pos1),
					(val_add, ":stat_position_y", -40),
				(try_end),
				(try_begin),
					(position_set_y, pos1, ":stat_position_y"),
					(eq, "$group2_has_troops", 1),
					(position_set_x, pos1, 270),
					(overlay_set_position, "$g_presentation_but2_movement", pos1),
					(position_set_x, pos1, 410),
					(overlay_set_position, "$g_presentation_but2_riding", pos1),
					(position_set_x, pos1, 550),
					(overlay_set_position, "$g_presentation_but2_weapon_usage", pos1),
					(val_add, ":stat_position_y", -40),
				(try_end),
				(try_begin),
					(position_set_y, pos1, ":stat_position_y"),
					(eq, "$group3_has_troops", 1),
					(position_set_x, pos1, 270),
					(overlay_set_position, "$g_presentation_but3_movement", pos1),
					(position_set_x, pos1, 410),
					(overlay_set_position, "$g_presentation_but3_riding", pos1),
					(position_set_x, pos1, 550),
					(overlay_set_position, "$g_presentation_but3_weapon_usage", pos1),
					(val_add, ":stat_position_y", -40),
				(try_end),
				(try_begin),
					(position_set_y, pos1, ":stat_position_y"),
					(eq, "$group4_has_troops", 1),
					(position_set_x, pos1, 270),
					(overlay_set_position, "$g_presentation_but4_movement", pos1),
					(position_set_x, pos1, 410),
					(overlay_set_position, "$g_presentation_but4_riding", pos1),
					(position_set_x, pos1, 550),
					(overlay_set_position, "$g_presentation_but4_weapon_usage", pos1),
					(val_add, ":stat_position_y", -40),
				(try_end),
				(try_begin),
					(position_set_y, pos1, ":stat_position_y"),
					(eq, "$group5_has_troops", 1),
					(position_set_x, pos1, 270),
					(overlay_set_position, "$g_presentation_but5_movement", pos1),
					(position_set_x, pos1, 410),
					(overlay_set_position, "$g_presentation_but5_riding", pos1),
					(position_set_x, pos1, 550),
					(overlay_set_position, "$g_presentation_but5_weapon_usage", pos1),
					(val_add, ":stat_position_y", -40),
				(try_end),
				(try_begin),
					(position_set_y, pos1, ":stat_position_y"),
					(eq, "$group6_has_troops", 1),
					(position_set_x, pos1, 270),
					(overlay_set_position, "$g_presentation_but6_movement", pos1),
					(position_set_x, pos1, 410),
					(overlay_set_position, "$g_presentation_but6_riding", pos1),
					(position_set_x, pos1, 550),
					(overlay_set_position, "$g_presentation_but6_weapon_usage", pos1),
					(val_add, ":stat_position_y", -40),
				(try_end),
				(try_begin),
					(position_set_y, pos1, ":stat_position_y"),
					(eq, "$group7_has_troops", 1),
					(position_set_x, pos1, 270),
					(overlay_set_position, "$g_presentation_but7_movement", pos1),
					(position_set_x, pos1, 410),
					(overlay_set_position, "$g_presentation_but7_riding", pos1),
					(position_set_x, pos1, 550),
					(overlay_set_position, "$g_presentation_but7_weapon_usage", pos1),
					(val_add, ":stat_position_y", -40),
				(try_end),
				(try_begin),
					(position_set_y, pos1, ":stat_position_y"),
					(eq, "$group8_has_troops", 1),
					(position_set_x, pos1, 270),
					(overlay_set_position, "$g_presentation_but8_movement", pos1),
					(position_set_x, pos1, 410),
					(overlay_set_position, "$g_presentation_but8_riding", pos1),
					(position_set_x, pos1, 550),
					(overlay_set_position, "$g_presentation_but8_weapon_usage", pos1),
					(val_add, ":stat_position_y", -40),
				(try_end),
		])
		
		# script_update_agent_position_on_map
		# Input: arg1 = agent_no, pos2 = map_size_pos
		# Output: none
update_agent_position_on_map = (
	"update_agent_position_on_map",
			[(store_script_param_1, ":agent_no"),
				(agent_get_slot, ":agent_overlay", ":agent_no", slot_agent_map_overlay_id),
				
				(get_player_agent_no, ":player_agent"),
				(try_begin),
					(le, ":agent_overlay", 0),
					(set_fixed_point_multiplier, 1000),
					(try_begin),
						(eq, ":agent_no", ":player_agent"),
						(create_mesh_overlay, reg1, "mesh_player_dot"),
						(position_set_x, pos1, 500),
						(position_set_y, pos1, 500),
						(overlay_set_size, reg1, pos1),
					(else_try),
						(create_mesh_overlay, reg1, "mesh_white_dot"),
						(position_set_x, pos1, 200),
						(position_set_y, pos1, 200),
						(overlay_set_size, reg1, pos1),
					(try_end),
					(overlay_set_alpha, reg1, 0x88),
					(agent_set_slot, ":agent_no", slot_agent_map_overlay_id, reg1),
					(assign, ":agent_overlay", reg1),
				(try_end),
				
				(try_begin),
					(neq, ":agent_no", ":player_agent"),
					(agent_get_party_id, ":agent_party", ":agent_no"),
					(try_begin),
						(eq, ":agent_party", "p_main_party"),
						(agent_get_division, ":agent_division", ":agent_no"),
						(try_begin),
							(eq, ":agent_division", 0),
							(overlay_set_color, ":agent_overlay", 0x8d5220),
						(else_try),
							(eq, ":agent_division", 1),
							(overlay_set_color, ":agent_overlay", 0x34c6e4),
						(else_try),
							(eq, ":agent_division", 2),
							(overlay_set_color, ":agent_overlay", 0x569619),
						(else_try),
							(eq, ":agent_division", 3),
							(overlay_set_color, ":agent_overlay", 0xFFE500),
						(else_try),
							(eq, ":agent_division", 4),
							(overlay_set_color, ":agent_overlay", 0x990099),
						(else_try),
							(eq, ":agent_division", 5),
							(overlay_set_color, ":agent_overlay", 0x99FE80),
						(else_try),
							(eq, ":agent_division", 6),
							(overlay_set_color, ":agent_overlay", 0x9DEFFE),
						(else_try),
							(eq, ":agent_division", 7),
							(overlay_set_color, ":agent_overlay", 0xFECB9D),
						(else_try),
							(eq, ":agent_division", 8),
							(overlay_set_color, ":agent_overlay", 0xB19C9C),
						(try_end),
					(else_try),
						(agent_is_ally, ":agent_no"),
						(overlay_set_color, ":agent_overlay", 0x5555FF),
					(else_try),
						(overlay_set_color, ":agent_overlay", 0xFF0000),
					(try_end),
				(try_end),
				
				(try_begin),
					(eq, ":agent_no", ":player_agent"),
					(agent_get_look_position, pos1, ":agent_no"),
					(position_get_rotation_around_z, ":rot", pos1),
					(init_position, pos10),
					(position_rotate_z, pos10, ":rot"),
					(overlay_set_mesh_rotation, ":agent_overlay", pos10),
					(call_script, "script_convert_3d_pos_to_map_pos"),
				(else_try),
					(agent_get_position, pos1, ":agent_no"),
					(call_script, "script_convert_3d_pos_to_map_pos"),
				(try_end),
				(overlay_set_position, ":agent_overlay", pos0),
		])
		
		
		# script_update_order_flags_on_map
		# Input: none
		# Output: none
update_order_flags_on_map = (
	"update_order_flags_on_map",
			[(set_fixed_point_multiplier, 1000),
				(get_player_agent_no, ":player_agent"),
				(agent_get_team, ":player_team", ":player_agent"),
				
				(get_scene_boundaries, pos2, pos3),
				
				(team_get_movement_order, ":cur_order", ":player_team", grc_infantry),
				(try_begin),
					(eq, ":cur_order", mordr_hold),
					(team_get_order_position, pos1, ":player_team", grc_infantry),
					(call_script, "script_convert_3d_pos_to_map_pos"),
					(overlay_set_alpha, "$g_battle_map_infantry_order_flag", 0xFF),
					(overlay_set_position, "$g_battle_map_infantry_order_flag", pos0),
				(else_try),
					(overlay_set_alpha, "$g_battle_map_infantry_order_flag", 0),
				(try_end),
				(team_get_movement_order, ":cur_order", ":player_team", grc_archers),
				(try_begin),
					(eq, ":cur_order", mordr_hold),
					(team_get_order_position, pos1, ":player_team", grc_archers),
					(call_script, "script_convert_3d_pos_to_map_pos"),
					(overlay_set_alpha, "$g_battle_map_archers_order_flag", 0xFF),
					(overlay_set_position, "$g_battle_map_archers_order_flag", pos0),
				(else_try),
					(overlay_set_alpha, "$g_battle_map_archers_order_flag", 0),
				(try_end),
				(team_get_movement_order, ":cur_order", ":player_team", grc_cavalry),
				(try_begin),
					(eq, ":cur_order", mordr_hold),
					(team_get_order_position, pos1, ":player_team", grc_cavalry),
					(call_script, "script_convert_3d_pos_to_map_pos"),
					(overlay_set_alpha, "$g_battle_map_cavalry_order_flag", 0xFF),
					(overlay_set_position, "$g_battle_map_cavalry_order_flag", pos0),
				(else_try),
					(overlay_set_alpha, "$g_battle_map_cavalry_order_flag", 0),
				(try_end),
		])
		
		# script_update_order_panel_checked_classes
		# Input: none
		# Output: none
update_order_panel_checked_classes = (
	"update_order_panel_checked_classes",
			[(get_player_agent_no, ":player_agent"),
				(agent_get_team, ":player_team", ":player_agent"),
				
				(try_begin),
					(eq, "$group0_has_troops", 1),
					(class_is_listening_order, ":player_team", 0),
					(overlay_set_val, "$g_presentation_obj_battle_check0", 1),
					(assign, "$g_formation_group0_selected", 1),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but0", 250, 0x44),
				(else_try),
					(eq, "$group0_has_troops", 1),
					(overlay_set_val, "$g_presentation_obj_battle_check0", 0),
					(assign, "$g_formation_group0_selected", 0),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but0", 250, 0),
				(try_end),
				(try_begin),
					(eq, "$group1_has_troops", 1),
					(class_is_listening_order, ":player_team", 1),
					(overlay_set_val, "$g_presentation_obj_battle_check1", 1),
					(assign, "$g_formation_group1_selected", 1),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but1", 250, 0x44),
				(else_try),
					(eq, "$group1_has_troops", 1),
					(overlay_set_val, "$g_presentation_obj_battle_check1", 0),
					(assign, "$g_formation_group1_selected", 0),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but1", 250, 0),
				(try_end),
				(try_begin),
					(eq, "$group2_has_troops", 1),
					(class_is_listening_order, ":player_team", 2),
					(overlay_set_val, "$g_presentation_obj_battle_check2", 1),
					(assign, "$g_formation_group2_selected", 1),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but2", 250, 0x44),
				(else_try),
					(eq, "$group2_has_troops", 1),
					(overlay_set_val, "$g_presentation_obj_battle_check2", 0),
					(assign, "$g_formation_group2_selected", 0),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but2", 250, 0),
				(try_end),
				(try_begin),
					(eq, "$group3_has_troops", 1),
					(class_is_listening_order, ":player_team", 3),
					(overlay_set_val, "$g_presentation_obj_battle_check3", 1),
					(assign, "$g_formation_group3_selected", 1),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but3", 250, 0x44),
				(else_try),
					(eq, "$group3_has_troops", 1),
					(overlay_set_val, "$g_presentation_obj_battle_check3", 0),
					(assign, "$g_formation_group3_selected", 0),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but3", 250, 0),
				(try_end),
				(try_begin),
					(eq, "$group4_has_troops", 1),
					(class_is_listening_order, ":player_team", 4),
					(overlay_set_val, "$g_presentation_obj_battle_check4", 1),
					(assign, "$g_formation_group4_selected", 1),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but4", 250, 0x44),
				(else_try),
					(eq, "$group4_has_troops", 1),
					(overlay_set_val, "$g_presentation_obj_battle_check4", 0),
					(assign, "$g_formation_group4_selected", 0),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but4", 250, 0),
				(try_end),
				(try_begin),
					(eq, "$group5_has_troops", 1),
					(class_is_listening_order, ":player_team", 5),
					(overlay_set_val, "$g_presentation_obj_battle_check5", 1),
					(assign, "$g_formation_group5_selected", 1),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but5", 250, 0x44),
				(else_try),
					(eq, "$group5_has_troops", 1),
					(overlay_set_val, "$g_presentation_obj_battle_check5", 0),
					(assign, "$g_formation_group5_selected", 0),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but5", 250, 0),
				(try_end),
				(try_begin),
					(eq, "$group6_has_troops", 1),
					(class_is_listening_order, ":player_team", 6),
					(overlay_set_val, "$g_presentation_obj_battle_check6", 1),
					(assign, "$g_formation_group6_selected", 1),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but6", 250, 0x44),
				(else_try),
					(eq, "$group6_has_troops", 1),
					(overlay_set_val, "$g_presentation_obj_battle_check6", 0),
					(assign, "$g_formation_group6_selected", 0),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but6", 250, 0),
				(try_end),
				(try_begin),
					(eq, "$group7_has_troops", 1),
					(class_is_listening_order, ":player_team", 7),
					(overlay_set_val, "$g_presentation_obj_battle_check7", 1),
					(assign, "$g_formation_group7_selected", 1),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but7", 250, 0x44),
				(else_try),
					(eq, "$group7_has_troops", 1),
					(overlay_set_val, "$g_presentation_obj_battle_check7", 0),
					(assign, "$g_formation_group7_selected", 0),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but7", 250, 0),
				(try_end),
				(try_begin),
					(eq, "$group8_has_troops", 1),
					(class_is_listening_order, ":player_team", 8),
					(overlay_set_val, "$g_presentation_obj_battle_check8", 1),
					(assign, "$g_formation_group8_selected", 1),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but8", 250, 0x44),
				(else_try),
					(eq, "$group8_has_troops", 1),
					(overlay_set_val, "$g_presentation_obj_battle_check8", 0),
					(assign, "$g_formation_group8_selected", 0),
					(overlay_animate_to_alpha, "$g_presentation_obj_battle_but8", 250, 0),
				(try_end),
		])
		
		# script_update_order_panel_statistics_and_map
		# Input: none
		# Output: none
update_order_panel_statistics_and_map = (
	"update_order_panel_statistics_and_map", #TODO: Call this in every battle mission template, once per second
			[(set_fixed_point_multiplier, 1000),
				
				(assign, ":num_us_ready_group0", 0),
				(assign, ":num_us_ready_group1", 0),
				(assign, ":num_us_ready_group2", 0),
				(assign, ":num_us_ready_group3", 0),
				(assign, ":num_us_ready_group4", 0),
				(assign, ":num_us_ready_group5", 0),
				(assign, ":num_us_ready_group6", 0),
				(assign, ":num_us_ready_group7", 0),
				(assign, ":num_us_ready_group8", 0),
				
				(assign, ":num_us_ready_men", 0),
				(assign, ":num_us_wounded_men", 0),
				(assign, ":num_us_routed_men", 0),
				(assign, ":num_us_dead_men", 0),
				(assign, ":num_allies_ready_men", 0),
				(assign, ":num_allies_wounded_men", 0),
				(assign, ":num_allies_routed_men", 0),
				(assign, ":num_allies_dead_men", 0),
				(assign, ":num_enemies_ready_men", 0),
				(assign, ":num_enemies_wounded_men", 0),
				(assign, ":num_enemies_routed_men", 0),
				(assign, ":num_enemies_dead_men", 0),
				
				(get_scene_boundaries, pos2, pos3),
				
				(try_for_agents,":cur_agent"),
					(agent_is_human, ":cur_agent"),
					(agent_get_division, ":agent_division", ":cur_agent"),
					(agent_get_party_id, ":agent_party", ":cur_agent"),
					(agent_get_slot, ":agent_overlay", ":cur_agent", slot_agent_map_overlay_id),
					(try_begin),
						(eq, ":agent_party", "p_main_party"),
						(try_begin),
							(agent_is_alive, ":cur_agent"),
							(call_script, "script_update_agent_position_on_map", ":cur_agent"),
							(try_begin),
								(eq, ":agent_division", 0),
								(val_add, ":num_us_ready_group0", 1),
								(eq, "$group0_has_troops", 1), #added to solve problem. test this.
							(else_try),
								(eq, ":agent_division", 1),
								(val_add, ":num_us_ready_group1", 1),
								(eq, "$group1_has_troops", 1), #added to solve problem.
							(else_try),
								(eq, ":agent_division", 2),
								(val_add, ":num_us_ready_group2", 1),
								(eq, "$group2_has_troops", 1), #added to solve problem.
							(else_try),
								(eq, ":agent_division", 3),
								(val_add, ":num_us_ready_group3", 1),
								(eq, "$group3_has_troops", 1), #added to solve problem.
							(else_try),
								(eq, ":agent_division", 4),
								(val_add, ":num_us_ready_group4", 1),
								(eq, "$group4_has_troops", 1), #added to solve problem.
							(else_try),
								(eq, ":agent_division", 5),
								(val_add, ":num_us_ready_group5", 1),
								(eq, "$group5_has_troops", 1), #added to solve problem.
							(else_try),
								(eq, ":agent_division", 6),
								(val_add, ":num_us_ready_group6", 1),
								(eq, "$group6_has_troops", 1), #added to solve problem.
							(else_try),
								(eq, ":agent_division", 7),
								(val_add, ":num_us_ready_group7", 1),
								(eq, "$group7_has_troops", 1), #added to solve problem.
							(else_try),
								(eq, ":agent_division", 8),
								(val_add, ":num_us_ready_group8", 1),
								(eq, "$group8_has_troops", 1), #added to solve problem.
							(try_end),
							(val_add, ":num_us_ready_men", 1),
						(else_try),
							(overlay_set_alpha, ":agent_overlay", 0),
							(agent_is_wounded, ":cur_agent"),
							(val_add, ":num_us_wounded_men", 1),
						(else_try),
							(agent_is_routed, ":cur_agent"),
							(val_add, ":num_us_routed_men", 1),
						(else_try),
							(val_add, ":num_us_dead_men", 1),
						(try_end),
					(else_try),
						(agent_is_ally, ":cur_agent"),
						(try_begin),
							(agent_is_alive, ":cur_agent"),
							(call_script, "script_update_agent_position_on_map", ":cur_agent"),
							(val_add, ":num_allies_ready_men", 1),
						(else_try),
							(overlay_set_alpha, ":agent_overlay", 0),
							(agent_is_wounded, ":cur_agent"),
							(val_add, ":num_allies_wounded_men", 1),
						(else_try),
							(agent_is_routed, ":cur_agent"),
							(val_add, ":num_allies_routed_men", 1),
						(else_try),
							(val_add, ":num_allies_dead_men", 1),
						(try_end),
					(else_try),
						(try_begin),
							(agent_is_alive, ":cur_agent"),
							(call_script, "script_update_agent_position_on_map", ":cur_agent"),
							(val_add, ":num_enemies_ready_men", 1),
						(else_try),
							(overlay_set_alpha, ":agent_overlay", 0),
							(agent_is_wounded, ":cur_agent"),
							(val_add, ":num_enemies_wounded_men", 1),
						(else_try),
							(agent_is_routed, ":cur_agent"),
							(val_add, ":num_enemies_routed_men", 1),
						(else_try),
							(val_add, ":num_enemies_dead_men", 1),
						(try_end),
					(try_end),
				(try_end),
				
				(assign, reg1, ":num_us_ready_group0"),
				(assign, reg2, ":num_us_ready_group1"),
				(assign, reg3, ":num_us_ready_group2"),
				(assign, reg4, ":num_us_ready_group3"),
				(assign, reg5, ":num_us_ready_group4"),
				(assign, reg6, ":num_us_ready_group5"),
				(assign, reg7, ":num_us_ready_group6"),
				(assign, reg8, ":num_us_ready_group7"),
				(assign, reg9, ":num_us_ready_group8"),
				(assign, reg10, ":num_us_ready_men"),
				(assign, reg11, ":num_us_wounded_men"),
				(assign, reg12, ":num_us_routed_men"),
				(assign, reg13, ":num_us_dead_men"),
				(assign, reg14, ":num_allies_ready_men"),
				(assign, reg15, ":num_allies_wounded_men"),
				(assign, reg16, ":num_allies_routed_men"),
				(assign, reg17, ":num_allies_dead_men"),
				(assign, reg18, ":num_enemies_ready_men"),
				(assign, reg19, ":num_enemies_wounded_men"),
				(assign, reg20, ":num_enemies_routed_men"),
				(assign, reg21, ":num_enemies_dead_men"),
				
				(try_begin),
					(eq, "$group0_has_troops", 1),
					(str_store_class_name, s1, 0),
					(overlay_set_text, "$g_presentation_obj_battle_name0", "str_s1_reg1"),
				(try_end),
				(try_begin),
					(eq, "$group1_has_troops", 1),
					(str_store_class_name, s1, 1),
					(overlay_set_text, "$g_presentation_obj_battle_name1", "str_s1_reg2"),
				(try_end),
				(try_begin),
					(eq, "$group2_has_troops", 1),
					(str_store_class_name, s1, 2),
					(overlay_set_text, "$g_presentation_obj_battle_name2", "str_s1_reg3"),
				(try_end),
				(try_begin),
					(eq, "$group3_has_troops", 1),
					(str_store_class_name, s1, 3),
					(overlay_set_text, "$g_presentation_obj_battle_name3", "str_s1_reg4"),
				(try_end),
				(try_begin),
					(eq, "$group4_has_troops", 1),
					(str_store_class_name, s1, 4),
					(overlay_set_text, "$g_presentation_obj_battle_name4", "str_s1_reg5"),
				(try_end),
				(try_begin),
					(eq, "$group5_has_troops", 1),
					(str_store_class_name, s1, 5),
					(overlay_set_text, "$g_presentation_obj_battle_name5", "str_s1_reg6"),
				(try_end),
				(try_begin),
					(eq, "$group6_has_troops", 1),
					(str_store_class_name, s1, 6),
					(overlay_set_text, "$g_presentation_obj_battle_name6", "str_s1_reg7"),
				(try_end),
				(try_begin),
					(eq, "$group7_has_troops", 1),
					(str_store_class_name, s1, 7),
					(overlay_set_text, "$g_presentation_obj_battle_name7", "str_s1_reg8"),
				(try_end),
				(try_begin),
					(eq, "$group8_has_troops", 1),
					(str_store_class_name, s1, 8),
					(overlay_set_text, "$g_presentation_obj_battle_name8", "str_s1_reg9"),
				(try_end),
				
				(overlay_set_text, "$g_battle_us_ready", "@{!}{reg10}"),
				(overlay_set_text, "$g_battle_us_wounded", "@{!}{reg11}"),
				(overlay_set_text, "$g_battle_us_routed", "@{!}{reg12}"),
				(overlay_set_text, "$g_battle_us_dead", "str_reg13"),
				(overlay_set_text, "$g_battle_allies_ready", "str_reg14"),
				(overlay_set_text, "$g_battle_allies_wounded", "str_reg15"),
				(overlay_set_text, "$g_battle_allies_routed", "str_reg16"),
				(overlay_set_text, "$g_battle_allies_dead", "str_reg17"),
				(overlay_set_text, "$g_battle_enemies_ready", "str_reg18"),
				(overlay_set_text, "$g_battle_enemies_wounded", "str_reg19"),
				(overlay_set_text, "$g_battle_enemies_routed", "str_reg20"),
				(overlay_set_text, "$g_battle_enemies_dead", "str_reg21"),
				
				(assign, ":stat_position_x", 675),
				(assign, ":stat_position_y", 280),
				(val_add, ":stat_position_x", 70),
				(val_add, ":stat_position_y", 60),
				(position_set_x, pos1, ":stat_position_x"),
				(position_set_y, pos1, ":stat_position_y"),
				(overlay_set_position, "$g_battle_us_ready", pos1),
				(val_add, ":stat_position_x", 70),
				(position_set_x, pos1, ":stat_position_x"),
				(overlay_set_position, "$g_battle_us_wounded", pos1),
				(val_add, ":stat_position_x", 70),
				(position_set_x, pos1, ":stat_position_x"),
				(overlay_set_position, "$g_battle_us_routed", pos1),
				(val_add, ":stat_position_x", 70),
				(position_set_x, pos1, ":stat_position_x"),
				(overlay_set_position, "$g_battle_us_dead", pos1),
				(val_add, ":stat_position_x", -210),
				(val_add, ":stat_position_y", -30),
				(position_set_x, pos1, ":stat_position_x"),
				(position_set_y, pos1, ":stat_position_y"),
				(overlay_set_position, "$g_battle_allies_ready", pos1),
				(val_add, ":stat_position_x", 70),
				(position_set_x, pos1, ":stat_position_x"),
				(overlay_set_position, "$g_battle_allies_wounded", pos1),
				(val_add, ":stat_position_x", 70),
				(position_set_x, pos1, ":stat_position_x"),
				(overlay_set_position, "$g_battle_allies_routed", pos1),
				(val_add, ":stat_position_x", 70),
				(position_set_x, pos1, ":stat_position_x"),
				(overlay_set_position, "$g_battle_allies_dead", pos1),
				(val_add, ":stat_position_x", -210),
				(val_add, ":stat_position_y", -30),
				(position_set_x, pos1, ":stat_position_x"),
				(position_set_y, pos1, ":stat_position_y"),
				(overlay_set_position, "$g_battle_enemies_ready", pos1),
				(val_add, ":stat_position_x", 70),
				(position_set_x, pos1, ":stat_position_x"),
				(overlay_set_position, "$g_battle_enemies_wounded", pos1),
				(val_add, ":stat_position_x", 70),
				(position_set_x, pos1, ":stat_position_x"),
				(overlay_set_position, "$g_battle_enemies_routed", pos1),
				(val_add, ":stat_position_x", 70),
				(position_set_x, pos1, ":stat_position_x"),
				(overlay_set_position, "$g_battle_enemies_dead", pos1),
				
				(call_script, "script_update_order_flags_on_map"),
		])
		