from header import *


troop_note = (
	"troop_note", 0, mesh_load_window, [
		(ti_on_presentation_load,
			[
				(presentation_set_duration, 999999),
				(set_fixed_point_multiplier, 1000),

				## init troop items
				(call_script, "script_copy_inventory", "$temp", "trp_temp_array_a"),
				(try_for_range, ":i_slot", 0, 10),
					(troop_get_inventory_slot, ":item", "trp_temp_array_a", ":i_slot"),
					(gt, ":item", -1),
					(troop_add_item,"trp_temp_array_a",":item"),
					(troop_set_inventory_slot, "trp_temp_array_a", ":i_slot", -1),
				(try_end),

				## back
				(create_game_button_overlay, "$g_presentation_obj_1", "@Done"),
				(position_set_x, pos1, 900),
				(position_set_y, pos1, 25),
				(overlay_set_position, "$g_presentation_obj_1", pos1),

				################
				(store_mul, ":cur_troop", "$temp", 2), #with weapons
				(create_mesh_overlay_with_tableau_material, reg0, -1, "tableau_game_party_window", ":cur_troop"),
				(position_set_x, pos1, 800),
				(position_set_y, pos1, 800),
				(overlay_set_size, reg0, pos1),
				(position_set_x, pos1, 720),
				(position_set_y, pos1, 450),
				(overlay_set_position, reg0, pos1),

				(str_store_troop_name, s1, "$temp"),
				(store_character_level, ":troop_level", "$temp"),
				(assign, reg1, ":troop_level"),
				(str_store_string, s1, "@Name: {s1}^Level: {reg1}"),
				(call_script, "script_get_troop_max_hp", "$temp"),
				(str_store_string, s1, "@{s1}^HP: {reg0}"),

				(create_text_overlay, reg0, "@{s1}", tf_double_space),
				(position_set_x, pos1, 500),
				(position_set_y, pos1, 500),
				(overlay_set_position, reg0, pos1),

				(str_store_string, s3, "@Attributes:"),
				(store_attribute_level, reg1, "$temp", ca_strength),
				(store_attribute_level, reg2, "$temp", ca_intelligence),
				(str_store_string, s3, "@{s3}^STR: {reg1}^INT: {reg2}^^Skills:"),
				(store_skill_level, reg1, skl_power_strike, "$temp"),
				(store_skill_level, reg2, skl_power_draw, "$temp"),
				(store_skill_level, reg3, skl_power_throw, "$temp"),
				(store_skill_level, reg4, skl_horse_archery, "$temp"),
				(str_store_string, s3, "@{s3}^Power Strike: {reg1}^Power Draw: {reg2}^Power Throw: {reg3}^Horse Archery: {reg4}^^Weapon Proficiencies:"),
				(store_proficiency_level, reg1, "$temp", wpt_one_handed_weapon),
				(store_proficiency_level, reg2, "$temp", wpt_two_handed_weapon),
				(store_proficiency_level, reg3, "$temp", wpt_polearm),
				(str_store_string, s3, "@{s3}^1 Hand Wpns: {reg1}^2 Hand Wpns: {reg2}^Polearms: {reg3}"),
				(create_text_overlay, reg0, "@{s3}", tf_double_space),
				(position_set_x, pos1, 500),
				(position_set_y, pos1, 100),
				(overlay_set_position, reg0, pos1),

				(str_store_string, s4, "str_empty_string"),
				(store_attribute_level, reg1, "$temp", ca_agility),
				(store_attribute_level, reg2, "$temp", ca_charisma),
				(str_store_string, s4, "@{s4}^AGI: {reg1}^CHA: {reg2}^^"),
				(store_skill_level, reg1, skl_ironflesh, "$temp"),
				(store_skill_level, reg2, skl_athletics, "$temp"),
				(store_skill_level, reg3, skl_shield, "$temp"),
				(store_skill_level, reg4, skl_riding, "$temp"),
				(str_store_string, s4, "@{s4}^Ironflesh: {reg1}^Athletics: {reg2}^Shield: {reg3}^Riding: {reg4}^^"),
				(store_proficiency_level, reg1, "$temp", wpt_archery),
				(store_proficiency_level, reg2, "$temp", wpt_crossbow),
				(store_proficiency_level, reg3, "$temp", wpt_throwing),
				(str_store_string, s4, "@{s4}^Archery: {reg1}^Crossbows: {reg2}^Throwing: {reg3}"),
				(create_text_overlay, reg0, "@{s4}", tf_double_space),
				(position_set_x, pos1, 710),
				(position_set_y, pos1, 100),
				(overlay_set_position, reg0, pos1),
				################

				(str_clear, s0),
				(create_text_overlay, "$g_presentation_obj_2", s0, tf_scrollable),
				(position_set_x, pos1, 50),
				(position_set_y, pos1, 50),
				(overlay_set_position, "$g_presentation_obj_2", pos1),
				(position_set_x, pos1, 350),
				(position_set_y, pos1, 560),
				(overlay_set_area_size, "$g_presentation_obj_2", pos1),
				(set_container_overlay, "$g_presentation_obj_2"),

				(assign, ":pos_x", 0),
				(assign, ":pos_y", 1840),
				(assign, ":slot_no", 10),
				(try_for_range, ":unused_height", 0, 24),
					(try_for_range, ":unused_width", 0, 4),
						(create_mesh_overlay, reg1, "mesh_inv_slot"),
						(position_set_x, pos1, 800),
						(position_set_y, pos1, 800),
						(overlay_set_size, reg1, pos1),
						(position_set_x, pos1, ":pos_x"),
						(position_set_y, pos1, ":pos_y"),
						(overlay_set_position, reg1, pos1),
						(create_mesh_overlay, reg1, "mesh_mp_inventory_choose"),
						(position_set_x, pos1, 640),
						(position_set_y, pos1, 640),
						(overlay_set_size, reg1, pos1),
						(position_set_x, pos1, ":pos_x"),
						(position_set_y, pos1, ":pos_y"),
						(overlay_set_position, reg1, pos1),
						(troop_set_slot, "trp_temp_array_a", ":slot_no", reg1),
						(troop_get_inventory_slot, ":item_no", "trp_temp_array_a", ":slot_no"),
						(try_begin),
							(gt, ":item_no", -1),
							(create_mesh_overlay_with_item_id, reg1, ":item_no"),
							(position_set_x, pos1, 800),
							(position_set_y, pos1, 800),
							(overlay_set_size, reg1, pos1),
							(store_add, ":item_x", ":pos_x", 40),
							(store_add, ":item_y", ":pos_y", 40),
							(position_set_x, pos1, ":item_x"),
							(position_set_y, pos1, ":item_y"),
							(overlay_set_position, reg1, pos1),
							(troop_set_slot, "trp_temp_array_b", ":slot_no", reg1),
						(try_end),
						(val_add, ":pos_x", 80),
						(val_add, ":slot_no", 1),
					(try_end),
					(assign, ":pos_x", 0),
					(val_sub, ":pos_y", 80),
				(try_end),

				(set_container_overlay, -1),

				(create_text_overlay, reg1, "@Equipments: ", tf_vertical_align_center),
				(position_set_x, pos1, 60),
				(position_set_y, pos1, 635),
				(overlay_set_position, reg1, pos1),
				## items

#        ####### mouse fix pos system #######
#        (call_script, "script_mouse_fix_pos_ready"),
#        ####### mouse fix pos system #######
			]),

#    (ti_on_presentation_run,
#      [
#        ####### mouse fix pos system #######
#        (call_script, "script_mouse_fix_pos_run"),
#        ####### mouse fix pos system #######
#    ]),

		(ti_on_presentation_mouse_enter_leave,
			[
			(store_trigger_param_1, ":object"),
			(store_trigger_param_2, ":enter_leave"),

			(try_begin),
				(eq, ":enter_leave", 0),
				(try_for_range, ":slot_no", 10, 106),
					(troop_slot_eq, "trp_temp_array_a", ":slot_no", ":object"),
					(troop_get_inventory_slot, ":item_no", "trp_temp_array_a", ":slot_no"),
					(try_begin),
						(gt, ":item_no", -1),
						(troop_get_slot, ":target_obj", "trp_temp_array_b", ":slot_no"),
						(overlay_get_position, pos0, ":target_obj"),
						(show_item_details, ":item_no", pos0, 100),
						(assign, "$g_current_opened_item_details", ":slot_no"),
					(try_end),
				(try_end),
			(else_try),
				(try_for_range, ":slot_no", 10, 106),
					(troop_slot_eq, "trp_temp_array_a", ":slot_no", ":object"),
					(try_begin),
						(eq, "$g_current_opened_item_details", ":slot_no"),
						(close_item_details),
					(try_end),
				(try_end),
			(try_end),
		]),

		(ti_on_presentation_event_state_change,
			[
				(store_trigger_param_1, ":object"),

				(try_begin),
					(eq, ":object", "$g_presentation_obj_1"),
					(try_begin),
						(gt, "$g_presentation_next_presentation", -1),
						(store_sub, "$temp_2", "$g_presentation_next_presentation", -1),
						(start_presentation, "$g_presentation_next_presentation"),
					(else_try),
						(presentation_set_duration, 0),
					(try_end),
				(try_end),
		]),
	])

recruit_npc = (
	"recruit_npc", 0, mesh_load_window,
	[
		(ti_on_presentation_load,
		[
			(presentation_set_duration, 999999),
				(set_fixed_point_multiplier, 1000),
		
		(str_clear, s0),
				(position_set_x, pos1, 50),

		
		(store_faction_of_party, ":center_faction", "$current_town"),
		(party_get_slot, ":local_culture", "$current_town", slot_center_culture),
		
		(try_begin),  #monogol
			(this_or_next|eq, ":center_faction", "fac_kingdom_3"),
			(this_or_next|eq, ":center_faction", "fac_kingdom_27"),
			(eq, ":local_culture", "fac_culture_mongol"),
			(str_store_string, s7, "@Mongol"),
		(else_try),  #baltic
			(eq, ":local_culture", "fac_culture_baltic"),
			(neq, ":center_faction", "fac_kingdom_1"), #not crusader knights
			(str_store_string, s7, "@Baltic"),
		(else_try), #orthodox
			(this_or_next|eq, ":local_culture", "fac_culture_rus"),
			(this_or_next|eq, ":local_culture", "fac_culture_serbian"),
			(this_or_next|eq, ":local_culture", "fac_culture_balkan"),
			(eq, ":local_culture", "fac_culture_byzantium"),
			(str_store_string, s7, "@Orthodox"),
		(else_try), #muslim
			(this_or_next|eq, ":local_culture", "fac_culture_marinid"),
			(this_or_next|eq, ":local_culture", "fac_culture_mamluke"),
			(this_or_next|eq, ":local_culture", "fac_culture_andalus"),
			(eq, ":local_culture", "fac_culture_anatolian"),
			(str_store_string, s7, "@Muslim"),
		(else_try), #western - anything else
			(str_store_string, s7, "@Catholic"),
			(try_end),
		
		(position_set_y, pos1, 700),
		(create_text_overlay, reg0, "@Current Culture: ", tf_vertical_align_center),
				(overlay_set_position, reg0, pos1),
		(position_set_x, pos1, 200),
		(create_text_overlay, reg0, s7, tf_vertical_align_center),
				(overlay_set_position, reg0, pos1),
		
		#row thing
		(position_set_x, pos1, 50),
		
		(position_set_y, pos1, 660),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 620),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 580),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 540),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 500),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 460),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 420),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 380),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 340),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 300),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 260),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 220),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 180),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 140),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 100),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 60),
		(create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		# (position_set_y, pos1, 20),
		# (create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		# (overlay_set_position, reg0, pos1),

		(assign, ":label_y", 600),
		(assign, ":button_y", 585),
		(assign, ":label_diffrence", 40),
		
		(assign, ":pathfinder", 0),
		(assign, ":trader", 0),
		(assign, ":monk", 0),
		(assign, ":engineer", 0),
		(assign, ":trainer", 0),
			

			
		(str_clear, s8),
		(try_for_range, ":troop", "trp_npc16", "trp_kingdom_1_lord"),
			(str_store_troop_name, s1, ":troop"),
			#profesion
			(try_begin),
				(is_between, ":troop", "trp_npc16", "trp_npc19"),
			(str_store_string, s2, "@Pathfinder"),
			(try_begin),
				(eq, ":pathfinder", 0),
				(party_count_members_of_type, reg1, "p_main_party", ":troop"),
				(ge, reg1, 1),
				(str_store_string, s8, "@{s8} Pathfinder"),
				(assign, ":pathfinder", 1),
			(try_end),
			(else_try),
				(is_between, ":troop", "trp_npc19", "trp_npc21"),
				(str_store_string, s2, "@Trader"),
			(try_begin),
				(eq, ":trader", 0),
				(party_count_members_of_type, reg1, "p_main_party", ":troop"),
				(ge, reg1, 1),
				(str_store_string, s8, "@{s8} Trader"),
				(assign, ":trader", 1),
			(try_end),
			(else_try),
				(is_between, ":troop", "trp_npc21", "trp_npc23"),
				(str_store_string, s2, "@Monk"),
			(try_begin),
				(eq, ":monk", 0),
				(party_count_members_of_type, reg1, "p_main_party", ":troop"),
				(ge, reg1, 1),
				(str_store_string, s8, "@{s8} Monk"),
				(assign, ":monk", 1),
			(try_end),
			(else_try),
				(is_between, ":troop", "trp_npc23", "trp_npc25"),
				(str_store_string, s2, "@Engineer"),
			(try_begin),
				(eq, ":engineer", 0),
				(party_count_members_of_type, reg1, "p_main_party", ":troop"),
				(ge, reg1, 1),
				(str_store_string, s8, "@{s8} Engineer"),
				(assign, ":engineer", 1),
			(try_end),
			(else_try),
				#(is_between, ":troop", "trp_npc26", "trp_npc29"),
				(str_store_string, s2, "@Trainer"),
			(try_begin),
				(eq, ":trainer", 0),
				(party_count_members_of_type, reg1, "p_main_party", ":troop"),
				(ge, reg1, 1),
				(str_store_string, s8, "@{s8} Trainer"),
				(assign, ":trainer", 1),
			(try_end),
			(try_end), 
			
			#culture
			(try_begin),
				(this_or_next|eq, ":troop", "trp_npc16"),
				(this_or_next|eq, ":troop", "trp_npc26"),
				(eq, ":troop", "trp_npc19"),
			(str_store_string, s3, "@Balt"),
			(else_try),
				(this_or_next|eq, ":troop", "trp_npc23"),
				(this_or_next|eq, ":troop", "trp_npc25"),
				(eq, ":troop", "trp_npc21"),
				(str_store_string, s3, "@Catholic"),
			(else_try),
				(this_or_next|eq, ":troop", "trp_npc22"),
				(this_or_next|eq, ":troop", "trp_npc27"),
				(eq, ":troop", "trp_npc17"),
				(str_store_string, s3, "@Orthodox"),
			(else_try),
				(this_or_next|eq, ":troop", "trp_npc20"),
				(this_or_next|eq, ":troop", "trp_npc24"),
				(eq, ":troop", "trp_npc28"),
				(str_store_string, s3, "@Muslim"),
			(else_try),
				(this_or_next|eq, ":troop", "trp_npc18"),
				(eq, ":troop", "trp_npc29"),
				(str_store_string, s3, "@Mongol"),
			(else_try),
			(str_store_string, s3, "@Strange"),
			(try_end), 
			#cost, status, ?hire button?
			(assign, reg5, 50), #initial price
			(store_character_level, ":level",":troop"),
			(val_mul, reg5, ":level"),
			#(str_store_string, s5, "@Hire"),
			(str_store_string, s6, "@Available"),
			(try_begin), #captured?
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(val_mul, reg5, 2),
			#(str_store_string, s5, "@Ransom"),
			(str_store_string, s6, "@Captured"),
			(else_try), #hired?
				(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(ge, reg1, 1),
					(str_store_string, s6, "@Hired"),
			(else_try),
				(neg|troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(str_store_string, s6, "@On a mission"),
			(else_try),
			(neg|troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(neg|troop_slot_eq, ":troop",slot_troop_occupation, slto_player_companion),
			(str_store_string, s6, "@Unavailable"),
			(try_end),
			(str_store_string, s4, "@{reg5}"),
			
			#profesion
			(position_set_x, pos1, 50),
			(position_set_y, pos1, ":label_y"),
			(create_text_overlay, reg0, s2, tf_vertical_align_center),
			(overlay_set_position, reg0, pos1),
			
			#name
			(position_set_x, pos1, 200),
			(position_set_y, pos1, ":label_y"),
			(create_text_overlay, reg0, s1, tf_vertical_align_center),
			(overlay_set_position, reg0, pos1),
			
			#culture
			(position_set_x, pos1, 350),
			(position_set_y, pos1, ":label_y"),
			(create_text_overlay, reg0, s3, tf_vertical_align_center),
			(overlay_set_position, reg0, pos1),
			
			#cost
			(position_set_x, pos1, 450),
			(position_set_y, pos1, ":label_y"),
			(create_text_overlay, reg0, s4, tf_vertical_align_center),
			(overlay_set_position, reg0, pos1),
			
			#button--- ## this is probably a no no?
			
			#status
			(position_set_x, pos1, 650),
			(position_set_y, pos1, ":label_y"),
			(create_text_overlay, reg0, s6, tf_vertical_align_center),
			(overlay_set_position, reg0, pos1),
			
			(val_sub, ":label_y", ":label_diffrence"),
			(val_sub, ":button_y", ":label_diffrence"),
		(try_end),
		
		#status
		(position_set_x, pos1, 50),
		(position_set_y, pos1, 680),
		(create_text_overlay, reg0, "@Specialists in party: ", tf_vertical_align_center),
				(overlay_set_position, reg0, pos1),
			
		(position_set_x, pos1, 200),
		(create_text_overlay, reg0, s8, tf_vertical_align_center),
				(overlay_set_position, reg0, pos1),
		
		#first row
		(position_set_x, pos1, 50),
		(position_set_y, pos1, 640),
		(create_text_overlay, reg0, "@Specialist:", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),

		#second row
		(position_set_x, pos1, 200),
		
		(position_set_y, pos1, 640),
		(create_text_overlay, reg0, "@Name:", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		
		
		#third row
		(position_set_x, pos1, 350),
		
		(position_set_y, pos1, 640),
		(create_text_overlay, reg0, "@Culture:", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		
		#fourth
		(position_set_x, pos1, 450),
		
		(position_set_y, pos1, 640),
		(create_text_overlay, reg0, "@Cost to hire:", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		
		#fifth
		(position_set_x, pos1, 560),
		
		(position_set_y, pos1, 640),
		(create_text_overlay, reg0, "@Hire:", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		
		(position_set_x, pos1, 610),
		
		(try_begin),
			(str_store_string, s0, "@Hire"),
			(assign, ":troop", "trp_npc16"),
			(try_begin),
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(str_store_string, s0, "@Ransom"),
			(try_end),
			
			(position_set_y, pos1, 585),
			(create_game_button_overlay, "$g_presentation_obj_1", s0),
			(overlay_set_position, "$g_presentation_obj_1", pos1),
			(overlay_set_display, "$g_presentation_obj_1", 0),  
			(troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(troop_slot_eq, ":troop", slot_troop_days_on_mission, 0),
			(neq, ":troop", "$g_player_minister"),
			(neq, ":troop", "$g_player_chamberlain"),
					(neq, ":troop", "$g_player_constable"),
			(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(eq, reg1, 0),
			(neq, ":pathfinder", 1),
			(overlay_set_display, "$g_presentation_obj_1", 1),  
		(try_end),
		
		(try_begin),
			(str_store_string, s0, "@Hire"),
			(assign, ":troop", "trp_npc17"),
			(try_begin),
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(str_store_string, s0, "@Ransom"),
			(try_end),
			
			(position_set_y, pos1, 545),
			(create_game_button_overlay, "$g_presentation_obj_2", s0),
			(overlay_set_position, "$g_presentation_obj_2", pos1),
			(overlay_set_display, "$g_presentation_obj_2", 0),
			(troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(troop_slot_eq, ":troop", slot_troop_days_on_mission, 0),
			(neq, ":troop", "$g_player_minister"),
			(neq, ":troop", "$g_player_chamberlain"),
					(neq, ":troop", "$g_player_constable"),
			(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(eq, reg1, 0),
			(neq, ":pathfinder", 1),
			(overlay_set_display, "$g_presentation_obj_2", 1),      
		(try_end),
		
		(try_begin),
			(str_store_string, s0, "@Hire"),
			(assign, ":troop", "trp_npc18"),
			(try_begin),
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(str_store_string, s0, "@Ransom"),
			(try_end),
			
			(position_set_y, pos1, 505),
			(create_game_button_overlay, "$g_presentation_obj_3", s0),
			(overlay_set_position, "$g_presentation_obj_3", pos1),
			(overlay_set_display, "$g_presentation_obj_3", 0),
			(troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(troop_slot_eq, ":troop", slot_troop_days_on_mission, 0),
			(neq, ":troop", "$g_player_minister"),
			(neq, ":troop", "$g_player_chamberlain"),
					(neq, ":troop", "$g_player_constable"),
			(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(eq, reg1, 0),
			(neq, ":pathfinder", 1),
			(overlay_set_display, "$g_presentation_obj_3", 1),
		(try_end),
		
		(try_begin),
			(str_store_string, s0, "@Hire"),
			(assign, ":troop", "trp_npc19"),
			(try_begin),
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(str_store_string, s0, "@Ransom"),
			(try_end),
			
			(position_set_y, pos1, 465),
			(create_game_button_overlay, "$g_presentation_obj_4", s0),
			(overlay_set_position, "$g_presentation_obj_4", pos1),
			(overlay_set_display, "$g_presentation_obj_4", 0),
			(troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(troop_slot_eq, ":troop", slot_troop_days_on_mission, 0),
			(neq, ":troop", "$g_player_minister"),
			(neq, ":troop", "$g_player_chamberlain"),
					(neq, ":troop", "$g_player_constable"),
			(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(eq, reg1, 0),
			(neq, ":trader", 1),
			(overlay_set_display, "$g_presentation_obj_4", 1),      
		(try_end),
		
		(try_begin),
			(str_store_string, s0, "@Hire"),
			(assign, ":troop", "trp_npc20"),
			(try_begin),
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(str_store_string, s0, "@Ransom"),
			(try_end),
			
			(position_set_y, pos1, 425),
			(create_game_button_overlay, "$g_presentation_obj_5", s0),
			(overlay_set_position, "$g_presentation_obj_5", pos1),
			 (overlay_set_display, "$g_presentation_obj_5", 0),
			(troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(troop_slot_eq, ":troop", slot_troop_days_on_mission, 0),
			(neq, ":troop", "$g_player_minister"),
			(neq, ":troop", "$g_player_chamberlain"),
					(neq, ":troop", "$g_player_constable"),
			(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(eq, reg1, 0),
			(neq, ":trader", 1),
			(overlay_set_display, "$g_presentation_obj_5", 1),      
		(try_end),
		
		(try_begin),
			(str_store_string, s0, "@Hire"),
			(assign, ":troop", "trp_npc21"),
			(try_begin),
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(str_store_string, s0, "@Ransom"),
			(try_end),
			
			(position_set_y, pos1, 385),
			(create_game_button_overlay, "$g_presentation_obj_6", s0),
			(overlay_set_position, "$g_presentation_obj_6", pos1),
			(overlay_set_display, "$g_presentation_obj_6", 0),
			(troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(troop_slot_eq, ":troop", slot_troop_days_on_mission, 0),     
			(neq, ":troop", "$g_player_minister"),
			(neq, ":troop", "$g_player_chamberlain"),
					(neq, ":troop", "$g_player_constable"),
			(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(eq, reg1, 0),
			(neq, ":monk", 1),
			(overlay_set_display, "$g_presentation_obj_6", 1),      
		(try_end),
		
		(try_begin),
			(str_store_string, s0, "@Hire"),
			(assign, ":troop", "trp_npc22"),
			(try_begin),
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(str_store_string, s0, "@Ransom"),
			(try_end),
			
			(position_set_y, pos1, 345),
			(create_game_button_overlay, "$g_presentation_obj_7", s0),
			(overlay_set_position, "$g_presentation_obj_7", pos1),
			(overlay_set_display, "$g_presentation_obj_7", 0),  
			(troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(troop_slot_eq, ":troop", slot_troop_days_on_mission, 0),
			(neq, ":troop", "$g_player_minister"),
			(neq, ":troop", "$g_player_chamberlain"),
					(neq, ":troop", "$g_player_constable"),
			(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(eq, reg1, 0),
			(neq, ":monk", 1),
			(overlay_set_display, "$g_presentation_obj_7", 1),      
		(try_end),
		
		(try_begin),
			(str_store_string, s0, "@Hire"),
			(assign, ":troop", "trp_npc23"),
			(try_begin),
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(str_store_string, s0, "@Ransom"),
			(try_end),
			
			(position_set_y, pos1, 305),
			(create_game_button_overlay, "$g_presentation_obj_8", s0),
			(overlay_set_position, "$g_presentation_obj_8", pos1),
			(overlay_set_display, "$g_presentation_obj_8", 0),
			(troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(troop_slot_eq, ":troop", slot_troop_days_on_mission, 0),
			(neq, ":troop", "$g_player_minister"),
			(neq, ":troop", "$g_player_chamberlain"),
					(neq, ":troop", "$g_player_constable"),
			(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(eq, reg1, 0),
			(neq, ":engineer", 1),
			(overlay_set_display, "$g_presentation_obj_8", 1),      
		(try_end),
		
		(try_begin),
			(str_store_string, s0, "@Hire"),
			(assign, ":troop", "trp_npc24"),
			(try_begin),
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(str_store_string, s0, "@Ransom"),
			(try_end),
			
			(position_set_y, pos1, 265),
			(create_game_button_overlay, "$g_presentation_obj_9", s0),
			(overlay_set_position, "$g_presentation_obj_9", pos1),
			(overlay_set_display, "$g_presentation_obj_9", 0),  
			(troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(troop_slot_eq, ":troop", slot_troop_days_on_mission, 0),
			(neq, ":troop", "$g_player_minister"),
			(neq, ":troop", "$g_player_chamberlain"),
					(neq, ":troop", "$g_player_constable"),
			(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(eq, reg1, 0),
			(neq, ":engineer", 1),
			(overlay_set_display, "$g_presentation_obj_9", 1),      
		(try_end),
		
		(try_begin),
			(str_store_string, s0, "@Hire"),
			(assign, ":troop", "trp_npc25"),
			(try_begin),
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(str_store_string, s0, "@Ransom"),
			(try_end),
			
			(position_set_y, pos1, 225),
			(create_game_button_overlay, "$g_presentation_obj_10", s0),
			(overlay_set_position, "$g_presentation_obj_10", pos1),
			(overlay_set_display, "$g_presentation_obj_10", 0),
			(troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(troop_slot_eq, ":troop", slot_troop_days_on_mission, 0),
			(neq, ":troop", "$g_player_minister"),
			(neq, ":troop", "$g_player_chamberlain"),
					(neq, ":troop", "$g_player_constable"),
			(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(eq, reg1, 0),
			(neq, ":trainer", 1),
			(overlay_set_display, "$g_presentation_obj_10", 1),
		(try_end),
		
		(try_begin),
			(str_store_string, s0, "@Hire"),
			(assign, ":troop", "trp_npc26"),
			(try_begin),
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(str_store_string, s0, "@Ransom"),
			(try_end),
			
			(position_set_y, pos1, 185),
			(create_game_button_overlay, "$g_presentation_obj_11", s0),
			(overlay_set_position, "$g_presentation_obj_11", pos1),
			(overlay_set_display, "$g_presentation_obj_11", 0),
			(troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(troop_slot_eq, ":troop", slot_troop_days_on_mission, 0),
			(neq, ":troop", "$g_player_minister"),
			(neq, ":troop", "$g_player_chamberlain"),
					(neq, ":troop", "$g_player_constable"),
			(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(eq, reg1, 0),
			(neq, ":trainer", 1),
			(overlay_set_display, "$g_presentation_obj_11", 1),
		(try_end),
		
		(try_begin),
			(str_store_string, s0, "@Hire"),
			(assign, ":troop", "trp_npc27"),
			(try_begin),
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(str_store_string, s0, "@Ransom"),
			(try_end),
			
			(position_set_y, pos1, 145),
			(create_game_button_overlay, "$g_presentation_obj_12", s0),
			(overlay_set_position, "$g_presentation_obj_12", pos1),
			(overlay_set_display, "$g_presentation_obj_12", 0), 
			(troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(troop_slot_eq, ":troop", slot_troop_days_on_mission, 0),
			(neq, ":troop", "$g_player_minister"),
			(neq, ":troop", "$g_player_chamberlain"),
					(neq, ":troop", "$g_player_constable"),
			(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(eq, reg1, 0),
			(neq, ":trainer", 1),
			(overlay_set_display, "$g_presentation_obj_12", 1),     
		(try_end),
		
		(try_begin),
			(str_store_string, s0, "@Hire"),
			(assign, ":troop", "trp_npc28"),
			(try_begin),
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(str_store_string, s0, "@Ransom"),
			(try_end),
			
			(position_set_y, pos1, 105),
			(create_game_button_overlay, "$g_presentation_obj_13", s0),
			(overlay_set_position, "$g_presentation_obj_13", pos1),
			(overlay_set_display, "$g_presentation_obj_13", 0), 
			(troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(troop_slot_eq, ":troop", slot_troop_days_on_mission, 0),
			(neq, ":troop", "$g_player_minister"),
			(neq, ":troop", "$g_player_chamberlain"),
					(neq, ":troop", "$g_player_constable"),
			(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(eq, reg1, 0),
			(neq, ":trainer", 1),
			(overlay_set_display, "$g_presentation_obj_13", 1),     
		(try_end),
		
		(try_begin),
			(str_store_string, s0, "@Hire"),
			(assign, ":troop", "trp_npc29"),
			(try_begin),
				(troop_slot_ge, ":troop", slot_troop_prisoner_of_party, 0),
			(str_store_string, s0, "@Ransom"),
			(try_end),
			
			(position_set_y, pos1, 65),
			(create_game_button_overlay, "$g_presentation_obj_14", s0),
			(overlay_set_position, "$g_presentation_obj_14", pos1),
			(overlay_set_display, "$g_presentation_obj_14", 0),
			(troop_slot_eq, ":troop",slot_troop_occupation, slto_inactive),
			(troop_slot_eq, ":troop", slot_troop_current_mission, 0),
			(troop_slot_eq, ":troop", slot_troop_days_on_mission, 0),
			(neq, ":troop", "$g_player_minister"),
			(neq, ":troop", "$g_player_chamberlain"),
					(neq, ":troop", "$g_player_constable"),
			(party_count_members_of_type, reg1, "p_main_party", ":troop"),
			(eq, reg1, 0),
			(neq, ":trainer", 1),
			(overlay_set_display, "$g_presentation_obj_14", 1),     
		(try_end),
		
		# (position_set_y, pos1, 65),
		# (create_game_button_overlay, "$g_presentation_obj_15", "@Hire"),
		# (overlay_set_position, "$g_presentation_obj_15", pos1),
		
		#sixth row
		(position_set_x, pos1, 650),
		
		(position_set_y, pos1, 640),
		(create_text_overlay, reg0, "@Status:", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),
		
		# done button
				(create_game_button_overlay, "$g_presentation_obj_20", "@Done"),
				(position_set_x, pos1, 900),
				(position_set_y, pos1, 25),
				(overlay_set_position, "$g_presentation_obj_20", pos1),
		
		#button resize
		(position_set_x, pos1, 90),
		(position_set_y, pos1, 30),
		
		(overlay_set_size, "$g_presentation_obj_1", pos1),
		(overlay_set_size, "$g_presentation_obj_2", pos1),
		(overlay_set_size, "$g_presentation_obj_3", pos1),
		(overlay_set_size, "$g_presentation_obj_4", pos1),
		(overlay_set_size, "$g_presentation_obj_5", pos1),
		(overlay_set_size, "$g_presentation_obj_6", pos1),
		(overlay_set_size, "$g_presentation_obj_7", pos1),
		(overlay_set_size, "$g_presentation_obj_8", pos1),
		(overlay_set_size, "$g_presentation_obj_9", pos1),
		(overlay_set_size, "$g_presentation_obj_10", pos1),
		(overlay_set_size, "$g_presentation_obj_11", pos1),
		(overlay_set_size, "$g_presentation_obj_12", pos1),
		(overlay_set_size, "$g_presentation_obj_13", pos1),
		(overlay_set_size, "$g_presentation_obj_14", pos1),
		
		]
	),
	
	(ti_on_presentation_event_state_change,
		[
				(store_trigger_param_1, ":object"),
				(store_trigger_param_2, ":value"),
		
		(assign, ":pathfinder", 0),
		(assign, ":trader", 0),
		(assign, ":monk", 0),
		(assign, ":engineer", 0),
		(assign, ":trainer", 0),
		(try_begin), #done button
			(eq, ":object", "$g_presentation_obj_1"),
			(call_script, "script_cf_hire_npc_specialist", "trp_npc16"),
			(overlay_set_display, "$g_presentation_obj_1", 0),
			(assign, ":pathfinder", 1),
		(else_try),
			(eq, ":object", "$g_presentation_obj_2"),
			(call_script, "script_cf_hire_npc_specialist", "trp_npc17"),
			(overlay_set_display, "$g_presentation_obj_2", 0),
			(assign, ":pathfinder", 1),
		(else_try),
			(eq, ":object", "$g_presentation_obj_3"),
			(call_script, "script_cf_hire_npc_specialist", "trp_npc18"),
			(overlay_set_display, "$g_presentation_obj_3", 0),
			(assign, ":pathfinder", 1),
		(else_try),
			(eq, ":object", "$g_presentation_obj_4"),
			(call_script, "script_cf_hire_npc_specialist", "trp_npc19"),
			(overlay_set_display, "$g_presentation_obj_4", 0),
			(assign, ":trader", 1),
		(else_try),
			(eq, ":object", "$g_presentation_obj_5"),
			(call_script, "script_cf_hire_npc_specialist", "trp_npc20"),
			(overlay_set_display, "$g_presentation_obj_5", 0),
			(assign, ":trader", 1),
		(else_try),
			(eq, ":object", "$g_presentation_obj_6"),
			(call_script, "script_cf_hire_npc_specialist", "trp_npc21"),
			(overlay_set_display, "$g_presentation_obj_6", 0),
			(assign, ":monk", 1),
		(else_try),
			(eq, ":object", "$g_presentation_obj_7"),
			(call_script, "script_cf_hire_npc_specialist", "trp_npc22"),
			(overlay_set_display, "$g_presentation_obj_7", 0),
			(assign, ":monk", 1),
		(else_try),
			(eq, ":object", "$g_presentation_obj_8"),
			(call_script, "script_cf_hire_npc_specialist", "trp_npc23"),
			(overlay_set_display, "$g_presentation_obj_8", 0),
			(assign, ":engineer", 1),
		(else_try),
			(eq, ":object", "$g_presentation_obj_9"),
			(call_script, "script_cf_hire_npc_specialist", "trp_npc24"),
			(overlay_set_display, "$g_presentation_obj_9", 0),
			(assign, ":engineer", 1),
		(else_try),
			(eq, ":object", "$g_presentation_obj_10"),
			(call_script, "script_cf_hire_npc_specialist", "trp_npc25"),
			(overlay_set_display, "$g_presentation_obj_10", 0),
			(assign, ":trainer", 1),
		(else_try),
			(eq, ":object", "$g_presentation_obj_11"),
			(call_script, "script_cf_hire_npc_specialist", "trp_npc26"),
			(overlay_set_display, "$g_presentation_obj_11", 0),
			(assign, ":trainer", 1),
		(else_try),
			(eq, ":object", "$g_presentation_obj_12"),
			(call_script, "script_cf_hire_npc_specialist", "trp_npc27"),
			(overlay_set_display, "$g_presentation_obj_12", 0),
			(assign, ":trainer", 1),
		(else_try),
			(eq, ":object", "$g_presentation_obj_13"),
			(call_script, "script_cf_hire_npc_specialist", "trp_npc28"),
			(overlay_set_display, "$g_presentation_obj_13", 0),
			(assign, ":trainer", 1),
		(else_try),
			(eq, ":object", "$g_presentation_obj_14"),
			(call_script, "script_cf_hire_npc_specialist", "trp_npc29"),
			(overlay_set_display, "$g_presentation_obj_14", 0),
			(assign, ":trainer", 1),
		(else_try),
			(eq, ":object", "$g_presentation_obj_20"),
			(presentation_set_duration, 0),  
				(try_end),
		
		(try_begin),
				(eq, ":pathfinder", 1),
			(overlay_set_display, "$g_presentation_obj_1", 0),
			(overlay_set_display, "$g_presentation_obj_2", 0),
			(overlay_set_display, "$g_presentation_obj_3", 0),
		(else_try),
			(eq, ":trader", 1),
			(overlay_set_display, "$g_presentation_obj_4", 0),
			(overlay_set_display, "$g_presentation_obj_5", 0),
		(else_try),
			(eq, ":monk", 1),
			(overlay_set_display, "$g_presentation_obj_6", 0),
			(overlay_set_display, "$g_presentation_obj_7", 0),
		(else_try),
			(eq, ":engineer", 1),
			(overlay_set_display, "$g_presentation_obj_8", 0),
			(overlay_set_display, "$g_presentation_obj_9", 0),
			(overlay_set_display, "$g_presentation_obj_10", 0),
		(else_try),
			(eq, ":trainer", 1),
			(overlay_set_display, "$g_presentation_obj_11", 0),
			(overlay_set_display, "$g_presentation_obj_12", 0),
			(overlay_set_display, "$g_presentation_obj_13", 0),
			(overlay_set_display, "$g_presentation_obj_14", 0),
		(try_end),
		]
		),  
	])


##economy tom  
economy_build =	(
	"economy_build", 0, mesh_load_window, [
		(ti_on_presentation_load,
			[
				(presentation_set_duration, 999999),
				(set_fixed_point_multiplier, 1000),
		###debug
		(call_script, "script_set_prsnt_debug"),
		###get strings
		(call_script, "script_economy_get_buildings"),
		
		(position_set_x, pos2, 60),
		(position_set_y, pos2, 22),
		
		(position_set_x, pos1, 50),
		(position_set_y, pos1, 500),
		# (create_text_overlay, reg0, "@----------------------------------------------------------------------------------------------------------------------------------------------------------------", tf_vertical_align_center),
		# (overlay_set_position, reg0, pos1),
		(create_text_overlay, reg0, "@NAME(build)     cost", tf_vertical_align_center),
		(overlay_set_position, reg0, pos1),

		# (position_set_y, pos1, 550),
		# (create_text_overlay, reg0, "@{s1}", tf_left_align),
		# (overlay_set_position, reg0, pos1),
		# (position_set_y, pos1, 525),
		# (create_text_overlay, reg0, "@{s2}", tf_left_align),
		# (overlay_set_position, reg0, pos1),
		# (position_set_y, pos1, 500),
		# (create_text_overlay, reg0, "@{s3}", tf_left_align),
		# (overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 475),
		(create_text_overlay, reg0, "@{s1}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 450),
		(create_text_overlay, reg0, "@{s2}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 425),
		(create_text_overlay, reg0, "@{s3}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 400),
		(create_text_overlay, reg0, "@{s4}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 375),
		(create_text_overlay, reg0, "@{s5}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 350),
		(create_text_overlay, reg0, "@{s6}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 325),
		(create_text_overlay, reg0, "@{s7}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 300),
		(create_text_overlay, reg0, "@{s8}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 275),
		(create_text_overlay, reg0, "@{s9}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 250),
		(create_text_overlay, reg0, "@{s10}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 225),
		(create_text_overlay, reg0, "@{s11}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 200),
		(create_text_overlay, reg0, "@{s12}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 175),
		(create_text_overlay, reg0, "@{s13}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 150),
		(create_text_overlay, reg0, "@{s14}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 125),
		(create_text_overlay, reg0, "@{s15}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		(position_set_y, pos1, 100),
		(create_text_overlay, reg0, "@{s16}", tf_left_align),
		(overlay_set_position, reg0, pos1),
		
		(position_set_x, pos1, 325),
		(position_set_y, pos1, 22),

		(position_set_y, pos1, 472),
		(create_game_button_overlay, "$g_presentation_obj_1", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_1", pos1),
		(overlay_set_size, "$g_presentation_obj_1", pos2),
		(position_set_y, pos1, 447),
		(create_game_button_overlay, "$g_presentation_obj_2", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_2", pos1),
		(overlay_set_size, "$g_presentation_obj_2", pos2),
		(position_set_y, pos1, 422),
		(create_game_button_overlay, "$g_presentation_obj_3", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_3", pos1),
		(overlay_set_size, "$g_presentation_obj_3", pos2),
		(position_set_y, pos1, 397),
		(create_game_button_overlay, "$g_presentation_obj_4", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_4", pos1),
		(overlay_set_size, "$g_presentation_obj_4", pos2),
		(position_set_y, pos1, 372),
		(create_game_button_overlay, "$g_presentation_obj_5", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_5", pos1),
		(overlay_set_size, "$g_presentation_obj_5", pos2),
		(position_set_y, pos1, 347),
		(create_game_button_overlay, "$g_presentation_obj_6", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_6", pos1),
		(overlay_set_size, "$g_presentation_obj_6", pos2),
		(position_set_y, pos1, 322),
		(create_game_button_overlay, "$g_presentation_obj_7", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_7", pos1),
		(overlay_set_size, "$g_presentation_obj_7", pos2),
		(position_set_y, pos1, 297),
		(create_game_button_overlay, "$g_presentation_obj_8", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_8", pos1),
		(overlay_set_size, "$g_presentation_obj_8", pos2),
		(position_set_y, pos1, 272),
		(create_game_button_overlay, "$g_presentation_obj_9", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_9", pos1),
		(overlay_set_size, "$g_presentation_obj_9", pos2),
		(position_set_y, pos1, 247),
		(create_game_button_overlay, "$g_presentation_obj_10", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_10", pos1),
		(overlay_set_size, "$g_presentation_obj_10", pos2),
		(position_set_y, pos1, 222),
		(create_game_button_overlay, "$g_presentation_obj_11", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_11", pos1),
		(overlay_set_size, "$g_presentation_obj_11", pos2),
		(position_set_y, pos1, 197),
		(create_game_button_overlay, "$g_presentation_obj_12", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_12", pos1),
		(overlay_set_size, "$g_presentation_obj_12", pos2),
		(position_set_y, pos1, 172),
		(create_game_button_overlay, "$g_presentation_obj_13", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_13", pos1),
		(overlay_set_size, "$g_presentation_obj_13", pos2),
		(position_set_y, pos1, 147),
		(create_game_button_overlay, "$g_presentation_obj_14", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_14", pos1),
		(overlay_set_size, "$g_presentation_obj_14", pos2),
		(position_set_y, pos1, 122),
		(create_game_button_overlay, "$g_presentation_obj_15", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_15", pos1),
		(overlay_set_size, "$g_presentation_obj_15", pos2),
		(position_set_y, pos1, 97),
		(create_game_button_overlay, "$g_presentation_obj_16", "str_economy_build"),
				(overlay_set_position, "$g_presentation_obj_16", pos1),
		(overlay_set_size, "$g_presentation_obj_16", pos2),
		
		### done
				(create_game_button_overlay, "$g_presentation_obj_20", "@Done"),
				(position_set_x, pos1, 900),
				(position_set_y, pos1, 25),
				(overlay_set_position, "$g_presentation_obj_20", pos1),

			]),

		(ti_on_presentation_event_state_change,
			[
				(store_trigger_param_1, ":object"),
				(store_trigger_param_2, ":value"),

				(try_begin),
		#TOM END
					(eq, ":object", "$g_presentation_obj_20"),
					(presentation_set_duration, 0),
				(try_end),
			]),
		])