from header import *

mod_options = (
	"mod_options", 0, mesh_load_window, [
		(ti_on_presentation_load,
			[
				(presentation_set_duration, 999999),
				(set_fixed_point_multiplier, 1000),

				(str_clear, s0),
				(create_text_overlay, "$g_presentation_obj_6", s0, tf_scrollable),
				(position_set_x, pos1, 50),
				(position_set_y, pos1, 50),
				(overlay_set_position, "$g_presentation_obj_6", pos1),
				(position_set_x, pos1, 550),
				(position_set_y, pos1, 630),
				#(overlay_set_area_size, "$g_presentation_obj_6", pos1),
				#(set_container_overlay, "$g_presentation_obj_6"),

				(position_set_x, pos1, 50),
				
				(create_text_overlay, reg0, "@Travel speed (recommended 75%):", tf_vertical_align_center),
				(position_set_y, pos1, 715),
				(overlay_set_position, reg0, pos1),
				
				(create_text_overlay, reg0, "@Use shield bash (player):", tf_vertical_align_center),
				(position_set_y, pos1, 675),
				(overlay_set_position, reg0, pos1),
				
				(create_text_overlay, reg0, "@Use shield bash (AI):", tf_vertical_align_center),
				(position_set_y, pos1, 635),
				(overlay_set_position, reg0, pos1),

				(create_text_overlay, reg0, "@Spear bracing:", tf_vertical_align_center),
				(position_set_y, pos1, 595),
				(overlay_set_position, reg0, pos1),

				(create_text_overlay, reg0, "@Use historical coat of arm usage:", tf_vertical_align_center),
				(position_set_y, pos1, 555),
				(overlay_set_position, reg0, pos1),

				(create_text_overlay, reg0, "@Apply historical coat of arms to player:", tf_vertical_align_center),
				(position_set_y, pos1, 515),
				(overlay_set_position, reg0, pos1),

				(create_text_overlay, reg0, "@Change party icons on water(Warning: resource intensive!):", tf_vertical_align_center),
				(position_set_y, pos1, 475),
				(overlay_set_position, reg0, pos1),

				(create_text_overlay, reg0, "@Reinforcement waves:", tf_vertical_align_center),
				(position_set_y, pos1, 435),
				(overlay_set_position, reg0, pos1),
				
				# (create_text_overlay, reg0, "@Probability of rain/snow (%):", tf_vertical_align_center),
				# (position_set_y, pos1, 395),
				# (overlay_set_position, reg0, pos1),

				# (create_text_overlay, reg0, "@Cloud amount:", tf_vertical_align_center),
				# (position_set_y, pos1, 355),
				# (overlay_set_position, reg0, pos1),

				# (create_text_overlay, reg0, "@Fog strength:", tf_vertical_align_center),
				# (position_set_y, pos1, 315),
				# (overlay_set_position, reg0, pos1),
		
		#tom
		# (create_text_overlay, reg0, "@Probability of sandstorm/blizzard/storm (%):", tf_vertical_align_center),
				# (position_set_y, pos1, 275),
				# (overlay_set_position, reg0, pos1),
		(create_text_overlay, reg0, "@Troop wages:", tf_vertical_align_center),
				(position_set_y, pos1, 395),
				(overlay_set_position, reg0, pos1),
		
		(create_text_overlay, reg0, "@Fief inefficency:", tf_vertical_align_center),
				(position_set_y, pos1, 355),
				(overlay_set_position, reg0, pos1),

				(create_text_overlay, reg0, "@Enterprise inefficency:", tf_vertical_align_center),
				(position_set_y, pos1, 315),
				(overlay_set_position, reg0, pos1),
		
		(create_text_overlay, reg0, "@Number of times to reduce flora in custom battlefields:", tf_vertical_align_center),
				(position_set_y, pos1, 275),
				(overlay_set_position, reg0, pos1),
		
		(create_text_overlay, reg0, "@Auxiliary player feature:", tf_vertical_align_center),
				(position_set_y, pos1, 235),
				(overlay_set_position, reg0, pos1),
		
		(create_text_overlay, reg0, "@Banners give bonuses:", tf_vertical_align_center),
				(position_set_y, pos1, 195),
				(overlay_set_position, reg0, pos1),
		
		(create_text_overlay, reg0, "@Use banner-man:", tf_vertical_align_center),
				(position_set_y, pos1, 155),
				(overlay_set_position, reg0, pos1),
		
		(create_text_overlay, reg0, "@Use Custom-battlefields:", tf_vertical_align_center),
				(position_set_y, pos1, 115),
				(overlay_set_position, reg0, pos1),
		
		(create_text_overlay, reg0, "@Weapon break:", tf_vertical_align_center),
				(position_set_y, pos1, 75),
				(overlay_set_position, reg0, pos1),   
		#tom end
		
				# lines
				# (call_script, "script_prsnt_lines", 470, 2, 50, 140),
				# (call_script, "script_prsnt_lines", 470, 2, 50, 340),
				# (call_script, "script_prsnt_lines", 470, 2, 50, 590),
				
				## checkboxes
				(position_set_x, pos1, 400),

				(create_check_box_overlay, "$g_presentation_obj_7", "mesh_checkbox_off", "mesh_checkbox_on"),
				(position_set_y, pos1, 665),
				(overlay_set_position, "$g_presentation_obj_7", pos1),
				(overlay_set_val, "$g_presentation_obj_7", "$sp_shield_bash"),

				(create_check_box_overlay, "$g_presentation_obj_8", "mesh_checkbox_off", "mesh_checkbox_on"),
				(position_set_y, pos1, 625),
				(overlay_set_position, "$g_presentation_obj_8", pos1),
				(overlay_set_val, "$g_presentation_obj_8", "$sp_shield_bash_ai"),

				(create_check_box_overlay, "$g_presentation_obj_5", "mesh_checkbox_off", "mesh_checkbox_on"),
				(position_set_y, pos1, 585),
				(overlay_set_position, "$g_presentation_obj_5", pos1),
				(overlay_set_val, "$g_presentation_obj_5", "$setting_use_spearwall"),

				(create_check_box_overlay, "$g_presentation_obj_13", "mesh_checkbox_off", "mesh_checkbox_on"),
				(position_set_y, pos1, 545),
				(overlay_set_position, "$g_presentation_obj_13", pos1),
				(overlay_set_val, "$g_presentation_obj_13", "$historical_banners"),

				(create_check_box_overlay, "$g_presentation_obj_11", "mesh_checkbox_off", "mesh_checkbox_on"),
				(position_set_y, pos1, 505),
				(overlay_set_position, "$g_presentation_obj_11", pos1),
				(overlay_set_val, "$g_presentation_obj_11", "$randomize_player_shield"),
				
				(create_check_box_overlay, "$g_presentation_obj_12", "mesh_checkbox_off", "mesh_checkbox_on"),
				(position_set_y, pos1, 465),
				(overlay_set_position, "$g_presentation_obj_12", pos1),
				(overlay_set_val, "$g_presentation_obj_12", "$tom_use_longships"),
		
		#TOM
		(create_check_box_overlay, "$g_presentation_obj_27", "mesh_checkbox_off", "mesh_checkbox_on"),
				(position_set_y, pos1, 225),
				(overlay_set_position, "$g_presentation_obj_27", pos1),
				(overlay_set_val, "$g_presentation_obj_27", "$use_player_auxiliary"),
		
		(create_check_box_overlay, "$g_presentation_obj_28", "mesh_checkbox_off", "mesh_checkbox_on"),
				(position_set_y, pos1, 185),
				(overlay_set_position, "$g_presentation_obj_28", pos1),
				(overlay_set_val, "$g_presentation_obj_28", "$tom_bonus_banners"),
		
		(create_check_box_overlay, "$g_presentation_obj_29", "mesh_checkbox_off", "mesh_checkbox_on"),
				(position_set_y, pos1, 145),
				(overlay_set_position, "$g_presentation_obj_29", pos1),
				(overlay_set_val, "$g_presentation_obj_29", "$tom_use_banners"),
		
		(create_check_box_overlay, "$g_presentation_obj_30", "mesh_checkbox_off", "mesh_checkbox_on"),
				(position_set_y, pos1, 105),
				(overlay_set_position, "$g_presentation_obj_30", pos1),
				(overlay_set_val, "$g_presentation_obj_30", "$tom_use_battlefields"),
		
		(create_check_box_overlay, "$g_presentation_obj_31", "mesh_checkbox_off", "mesh_checkbox_on"),
				(position_set_y, pos1, 65),
				(overlay_set_position, "$g_presentation_obj_31", pos1),
				(overlay_set_val, "$g_presentation_obj_31", "$tom_weapon_break"),
		#TOM end
				## checkboxes

				## number boxes
				(position_set_x, pos1, 400),

				(create_number_box_overlay, "$g_presentation_obj_10", 0, 101),
				(position_set_y, pos1, 701),
				(overlay_set_position, "$g_presentation_obj_10", pos1),        
				(overlay_set_val, "$g_presentation_obj_10", "$g_travel_speed"),

				(create_number_box_overlay, "$g_presentation_obj_15", 0, 101),
				(position_set_y, pos1, 421),
				(overlay_set_position, "$g_presentation_obj_15", pos1),        
				(overlay_set_val, "$g_presentation_obj_15", "$g_reinforcement_waves"),

		#tom
		#troop wages
		(create_button_overlay, "$g_presentation_obj_18", "@troop wage"),
		(try_begin),
			(eq, "$tom_difficulty_wages", 0), #hard
			(overlay_set_text, "$g_presentation_obj_18", "@Masochistic"),
		(else_try),
			(eq, "$tom_difficulty_wages", 1), #normal
			(overlay_set_text, "$g_presentation_obj_18", "@Normal"),
		(else_try),
			(eq, "$tom_difficulty_wages", 2),  #easy
			(overlay_set_text, "$g_presentation_obj_18", "@Childish"),
		(try_end),
				(position_set_y, pos1, 381),
				(overlay_set_position, "$g_presentation_obj_18", pos1),

		#fief inefficency
		(create_button_overlay, "$g_presentation_obj_25", "@fief"),
		(try_begin),
			(eq, "$tom_difficulty_fief", 0), #hard
			(overlay_set_text, "$g_presentation_obj_25", "@Masochistic"),
		(else_try),
			(eq, "$tom_difficulty_fief", 1), #normal
			(overlay_set_text, "$g_presentation_obj_25", "@Normal"),
		(else_try),
			(eq, "$tom_difficulty_fief", 2),  #easy
			(overlay_set_text, "$g_presentation_obj_25", "@Childish"),
		(try_end),
				(position_set_y, pos1, 341),
				(overlay_set_position, "$g_presentation_obj_25", pos1),

		#enterprise inefficency
		(create_button_overlay, "$g_presentation_obj_24", "@enterprise"),
		(try_begin),
			(eq, "$tom_difficulty_enterprise", 0), #hard
			(overlay_set_text, "$g_presentation_obj_24", "@Masochistic"),
		(else_try),
			(eq, "$tom_difficulty_enterprise", 1), #normal
			(overlay_set_text, "$g_presentation_obj_24", "@Normal"),
		(else_try),
			(eq, "$tom_difficulty_enterprise", 2),  #easy
			(overlay_set_text, "$g_presentation_obj_24", "@Childish"),
		(try_end),
				(position_set_y, pos1, 301),
				(overlay_set_position, "$g_presentation_obj_24", pos1),
		
		(create_number_box_overlay, "$g_presentation_obj_32", 1, 11),
				(position_set_y, pos1, 261),
				(overlay_set_position, "$g_presentation_obj_32", pos1),
				(overlay_set_val, "$g_presentation_obj_32", "$tom_generate_reduction"),
				
		
		(position_set_x, pos1, 520),
		
				(create_text_overlay, reg0, "@AI marshal army gathering inefficency:", tf_vertical_align_center),
				(position_set_y, pos1, 715),
		(overlay_set_position, reg0, pos1),
		
		(create_text_overlay, reg0, "@Lance breaking(Warning: can couse crashes!):", tf_vertical_align_center),
		(position_set_y, pos1, 675),
				(overlay_set_position, reg0, pos1),
		
		#(create_text_overlay, reg0, "@Change party icons on water(Warning: resource intensive!):", tf_vertical_align_center),
		#(position_set_y, pos1, 635),
				#(overlay_set_position, reg0, pos1),
		
		# (create_text_overlay, reg0, "@Auto Garrisions(This is considered cheating!):", tf_vertical_align_center),
		# (position_set_y, pos1, 595),
				# (overlay_set_position, reg0, pos1),
		
		(position_set_x, pos1, 850),
		
		(create_button_overlay, "$g_presentation_obj_33", "@inefficency"),
		(try_begin),
			(eq, "$feudal_inefficency", 0), #hard
			(overlay_set_text, "$g_presentation_obj_33", "@None"),
		(else_try),
			(eq, "$feudal_inefficency", 1), #normal
			(overlay_set_text, "$g_presentation_obj_33", "@Low"),
		(else_try),
			(eq, "$feudal_inefficency", 2),  #easy
			(overlay_set_text, "$g_presentation_obj_33", "@Normal"),
		(else_try),
			(eq, "$feudal_inefficency", 3),  #easy
			(overlay_set_text, "$g_presentation_obj_33", "@Masochistic"),  
		(try_end),
				(position_set_y, pos1, 701),
				(overlay_set_position, "$g_presentation_obj_33", pos1),
		
		(position_set_y, pos1, 661),
		(create_check_box_overlay, "$g_presentation_obj_34", "mesh_checkbox_off", "mesh_checkbox_on"),
				(overlay_set_position, "$g_presentation_obj_34", pos1),
				(overlay_set_val, "$g_presentation_obj_34", "$tom_lance_breaking"),
		
		#(position_set_y, pos1, 621),
		#(create_check_box_overlay, "$g_presentation_obj_35", "mesh_checkbox_off", "mesh_checkbox_on"),
				#(overlay_set_position, "$g_presentation_obj_35", pos1),
				#(overlay_set_val, "$g_presentation_obj_35", "$tom_use_longships"),
		
		# (position_set_y, pos1, 581),
		# (create_check_box_overlay, "$g_presentation_obj_36", "mesh_checkbox_off", "mesh_checkbox_on"),
				# (overlay_set_position, "$g_presentation_obj_36", pos1),
				# (overlay_set_val, "$g_presentation_obj_36", "$auto_recruitment"),
		#tom end
				
		# done
				(create_game_button_overlay, "$g_presentation_obj_20", "@Done"),
				(position_set_x, pos1, 900),
				(position_set_y, pos1, 25),
				(overlay_set_position, "$g_presentation_obj_20", pos1),

			]),

		(ti_on_presentation_event_state_change,
			[
				(store_trigger_param_1, ":object"),
				(store_trigger_param_2, ":value"),

				(try_begin),
					(eq, ":object", "$g_presentation_obj_5"),
					(assign, "$setting_use_spearwall", ":value"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_7"),
					(assign, "$sp_shield_bash", ":value"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_8"),
					(assign, "$sp_shield_bash_ai", ":value"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_10"),
					(assign, "$g_travel_speed", ":value"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_15"),
					(assign, "$g_reinforcement_waves", ":value"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_11"),
					(assign, "$randomize_player_shield", ":value"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_12"),
					(assign, "$tom_use_longships", ":value"),    
			(call_script, "script_set_sea_icons"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_13"),
					(assign, "$historical_banners", ":value"), 
		(else_try),
			(eq, ":object", "$g_presentation_obj_18"), #wages
			#(display_message, "@wages!"),
			(val_sub, "$tom_difficulty_wages", 1),
			(try_begin),
				(eq, "$tom_difficulty_wages", -1),
			(assign, "$tom_difficulty_wages", 2),
			(try_end),
			(try_begin),
				(eq, "$tom_difficulty_wages", 0), #hard
				(overlay_set_text, "$g_presentation_obj_18", "@Masochistic"),
			(else_try),
				(eq, "$tom_difficulty_wages", 1), #normal
				(overlay_set_text, "$g_presentation_obj_18", "@Normal"),
				(else_try),
				(eq, "$tom_difficulty_wages", 2),  #easy
				(overlay_set_text, "$g_presentation_obj_18", "@Childish"),
			(else_try),
			(overlay_set_text, "$g_presentation_obj_18", "@Oy! we have a problem!"),
			(try_end),
		(else_try),
			(eq, ":object", "$g_presentation_obj_25"), #fief
			#(display_message, "@fief!"),
			(val_sub, "$tom_difficulty_fief", 1),
			(try_begin),
				(eq, "$tom_difficulty_fief", -1),
			(assign, "$tom_difficulty_fief", 2),
			(try_end),
			(try_begin),
				(eq, "$tom_difficulty_fief", 0), #hard
				(overlay_set_text, "$g_presentation_obj_25", "@Masochistic"),
			(else_try),
				(eq, "$tom_difficulty_fief", 1), #normal
				(overlay_set_text, "$g_presentation_obj_25", "@Normal"),
			(else_try),
				(eq, "$tom_difficulty_fief", 2),  #easy
				(overlay_set_text, "$g_presentation_obj_25", "@Childish"),
				(else_try),
			(overlay_set_text, "$g_presentation_obj_25", "@Oy! we have a problem!"),
			(try_end),
		(else_try),
			(eq, ":object", "$g_presentation_obj_33"), #enterprise
			#(display_message, "@enterprise!"),
			(val_add, "$feudal_inefficency", 1),
			(try_begin),
				(eq, "$feudal_inefficency", 4),
			(assign, "$feudal_inefficency", 0),
			(try_end),
				(try_begin),
				(eq, "$feudal_inefficency", 0), #None
				(overlay_set_text, "$g_presentation_obj_33", "@None"),
			(else_try),
				(eq, "$feudal_inefficency", 1), #Normal
				(overlay_set_text, "$g_presentation_obj_33", "@Low"),
			(else_try),
				(eq, "$feudal_inefficency", 2),  #High
				(overlay_set_text, "$g_presentation_obj_33", "@Normal"),
			(else_try),
				(eq, "$feudal_inefficency", 3),  #Masochistic
				(overlay_set_text, "$g_presentation_obj_33", "@Masochistic"),  
			(else_try),
			(overlay_set_text, "$g_presentation_obj_33", "@Oy! we have a problem!"),
			(try_end),
		(else_try),
			(eq, ":object", "$g_presentation_obj_24"), #enterprise
			#(display_message, "@enterprise!"),
			(val_sub, "$tom_difficulty_enterprise", 1),
			(try_begin),
				(eq, "$tom_difficulty_enterprise", -1),
			(assign, "$tom_difficulty_enterprise", 2),
			(try_end),
				(try_begin),
				(eq, "$tom_difficulty_enterprise", 0), #hard
				(overlay_set_text, "$g_presentation_obj_24", "@Masochistic"),
			(else_try),
				(eq, "$tom_difficulty_enterprise", 1), #normal
				(overlay_set_text, "$g_presentation_obj_24", "@Normal"),
			(else_try),
				(eq, "$tom_difficulty_enterprise", 2),  #easy
				(overlay_set_text, "$g_presentation_obj_24", "@Childish"),
			(else_try),
			(overlay_set_text, "$g_presentation_obj_24", "@Oy! we have a problem!"),
			(try_end),
		 # (assign, "$tom_difficulty_enterprise", ":value"),
				# (else_try),
					# (eq, ":object", "$g_presentation_obj_18"),
					# (assign, "$g_rand_rain_limit", ":value"),
				# (else_try),
					# (eq, ":object", "$g_presentation_obj_25"),
					# (set_global_cloud_amount, ":value"),
				# (else_try),
					# (eq, ":object", "$g_presentation_obj_24"),
					# (set_global_haze_amount, ":value"),
		#tom Begin  
		# (else_try), 
			# (eq, ":object", "$g_presentation_obj_26"), 
			# (assign, "$tom_sand_storm_chance", ":value"),
		(else_try), 
			(eq, ":object", "$g_presentation_obj_27"),
			(assign, "$use_player_auxiliary", ":value"),
			#(call_script, "script_set_faction_party_names"),
		(else_try), 
			(eq, ":object", "$g_presentation_obj_28"),
			(assign, "$tom_bonus_banners", ":value"),
		(else_try),
			(eq, ":object", "$g_presentation_obj_29"),
			(assign, "$tom_use_banners", ":value"),
		(else_try),
			(eq, ":object", "$g_presentation_obj_30"),
			(assign, "$tom_use_battlefields", ":value"),
		(else_try),
			(eq, ":object", "$g_presentation_obj_31"),
			(assign, "$tom_weapon_break", ":value"),
			(else_try),
			(eq, ":object", "$g_presentation_obj_32"),
			(assign, "$tom_generate_reduction", ":value"), 
		(else_try),
			(eq, ":object", "$g_presentation_obj_34"),
			(assign, "$tom_lance_breaking", ":value"),  
		#(else_try),
		#  (eq, ":object", "$g_presentation_obj_35"),
		#  (assign, "$tom_use_longships", ":value"),    
		#  (call_script, "script_set_sea_icons"),
		# (else_try),
			# (eq, ":object", "$g_presentation_obj_36"),
			# (assign, "$auto_recruitment", ":value"),
		#TOM END
				(else_try),
					(eq, ":object", "$g_presentation_obj_20"),
					(presentation_set_duration, 0),
				(try_end),
			]),
		])


change_all_factions_color = (
	"change_all_factions_color", 0, mesh_load_window, [
		(ti_on_presentation_load,
			[
				(presentation_set_duration, 999999),
				(set_fixed_point_multiplier, 1000),

				#(create_combo_button_overlay, "$g_presentation_obj_1"),
				(create_combo_label_overlay, "$g_presentation_obj_1"),
				
				(position_set_x, pos1, 500),
				(position_set_y, pos1, 680),
				(overlay_set_position, "$g_presentation_obj_1", pos1),

				# faction list
				(troop_set_slot, "trp_temp_array_a", 0, "fac_outlaws"),
				(troop_set_slot, "trp_temp_array_b", 0, 0x888888),
				(troop_set_slot, "trp_temp_array_a", 1, "fac_neutral"),
				(troop_set_slot, "trp_temp_array_b", 1, 0xffffff),
				(troop_set_slot, "trp_temp_array_a", 2, "fac_player_faction"),
				(troop_set_slot, "trp_temp_array_b", 2, 0xcccccc),
				(troop_set_slot, "trp_temp_array_a", 3, "fac_player_supporters_faction"),
				(troop_set_slot, "trp_temp_array_b", 3, 0x468493),
				(troop_set_slot, "trp_temp_array_a", 4, "fac_kingdom_1"),
				(troop_set_slot, "trp_temp_array_b", 4, 0xe9e9e9),
				(troop_set_slot, "trp_temp_array_a", 5, "fac_kingdom_2"),
				(troop_set_slot, "trp_temp_array_b", 5, 0xbadeb2),
				(troop_set_slot, "trp_temp_array_a", 6, "fac_kingdom_3"),
				(troop_set_slot, "trp_temp_array_b", 6, 0xa33e32),
				(troop_set_slot, "trp_temp_array_a", 7, "fac_kingdom_4"),
				(troop_set_slot, "trp_temp_array_b", 7, 0x9b1a1a),
				(troop_set_slot, "trp_temp_array_a", 8, "fac_kingdom_5"),
				(troop_set_slot, "trp_temp_array_b", 8, 0xff0000),
				(troop_set_slot, "trp_temp_array_a", 9, "fac_kingdom_6"),
				(troop_set_slot, "trp_temp_array_b", 9, 0xffcc00),
				(troop_set_slot, "trp_temp_array_a", 10, "fac_kingdom_7"),
				(troop_set_slot, "trp_temp_array_b", 10, 0x289327),
				(troop_set_slot, "trp_temp_array_a", 11, "fac_kingdom_8"),
				(troop_set_slot, "trp_temp_array_b", 11, 0x9e0b6f),
				(troop_set_slot, "trp_temp_array_a", 12, "fac_kingdom_9"),
				(troop_set_slot, "trp_temp_array_b", 12, 0x931124),
				(troop_set_slot, "trp_temp_array_a", 13, "fac_kingdom_10"),
				(troop_set_slot, "trp_temp_array_b", 13, 0x2395),
				(troop_set_slot, "trp_temp_array_a", 14, "fac_kingdom_11"),
				(troop_set_slot, "trp_temp_array_b", 14, 0x6669d6),
				(troop_set_slot, "trp_temp_array_a", 15, "fac_kingdom_12"),
				(troop_set_slot, "trp_temp_array_b", 15, 0x22d8a7),
				(troop_set_slot, "trp_temp_array_a", 16, "fac_kingdom_13"),
				(troop_set_slot, "trp_temp_array_b", 16, 0x77b322),
				(troop_set_slot, "trp_temp_array_a", 17, "fac_kingdom_14"),
				(troop_set_slot, "trp_temp_array_b", 17, 0x3254b5),
				(troop_set_slot, "trp_temp_array_a", 18, "fac_kingdom_15"),
				(troop_set_slot, "trp_temp_array_b", 18, 0xece874),
				(troop_set_slot, "trp_temp_array_a", 19, "fac_kingdom_16"),
				(troop_set_slot, "trp_temp_array_b", 19, 0x3399),
				(troop_set_slot, "trp_temp_array_a", 20, "fac_kingdom_17"),
				(troop_set_slot, "trp_temp_array_b", 20, 0x7b233),
				(troop_set_slot, "trp_temp_array_a", 21, "fac_kingdom_18"),
				(troop_set_slot, "trp_temp_array_b", 21, 0xd85ac4),
				(troop_set_slot, "trp_temp_array_a", 22, "fac_kingdom_19"),
				(troop_set_slot, "trp_temp_array_b", 22, 0xf7f497),
				(troop_set_slot, "trp_temp_array_a", 23, "fac_kingdom_20"),
				(troop_set_slot, "trp_temp_array_b", 23, 0xabc904),
				(troop_set_slot, "trp_temp_array_a", 24, "fac_papacy"),
				(troop_set_slot, "trp_temp_array_b", 24, 0xfff17a),
				(troop_set_slot, "trp_temp_array_a", 25, "fac_kingdom_22"),
				(troop_set_slot, "trp_temp_array_b", 25, 0x760d0d),
				(troop_set_slot, "trp_temp_array_a", 26, "fac_kingdom_23"),
				(troop_set_slot, "trp_temp_array_b", 26, 0xf3efb8),
				(troop_set_slot, "trp_temp_array_a", 27, "fac_kingdom_24"),
				(troop_set_slot, "trp_temp_array_b", 27, 0x799cb5),
				(troop_set_slot, "trp_temp_array_a", 28, "fac_kingdom_25"),
				(troop_set_slot, "trp_temp_array_b", 28, 0xebe800),
				(troop_set_slot, "trp_temp_array_a", 29, "fac_kingdom_26"),
				(troop_set_slot, "trp_temp_array_b", 29, 0xb26248),
				(troop_set_slot, "trp_temp_array_a", 30, "fac_kingdom_27"),
				(troop_set_slot, "trp_temp_array_b", 30, 0xe19004),
				(troop_set_slot, "trp_temp_array_a", 31, "fac_kingdom_28"),
				(troop_set_slot, "trp_temp_array_b", 31, 0xa48460),
				(troop_set_slot, "trp_temp_array_a", 32, "fac_kingdom_29"),
				(troop_set_slot, "trp_temp_array_b", 32, 0xb38263),
				(troop_set_slot, "trp_temp_array_a", 33, "fac_kingdom_30"),
				(troop_set_slot, "trp_temp_array_b", 33, 0x76a296),
				(troop_set_slot, "trp_temp_array_a", 34, "fac_kingdom_31"),
				(troop_set_slot, "trp_temp_array_b", 34, 0xc1272d),
				(troop_set_slot, "trp_temp_array_a", 35, "fac_kingdom_32"),
				(troop_set_slot, "trp_temp_array_b", 35, 0xc1172d),
				(troop_set_slot, "trp_temp_array_a", 36, "fac_kingdom_33"),
				(troop_set_slot, "trp_temp_array_b", 36, 0x3e7583),
				(troop_set_slot, "trp_temp_array_a", 37, "fac_kingdom_34"),
				(troop_set_slot, "trp_temp_array_b", 37, 0x65c0d7),
				(troop_set_slot, "trp_temp_array_a", 38, "fac_kingdom_35"),
				(troop_set_slot, "trp_temp_array_b", 38, 0x3e7583),
				(troop_set_slot, "trp_temp_array_a", 39, "fac_kingdom_36"),
				(troop_set_slot, "trp_temp_array_b", 39, 0x529cae),
				(troop_set_slot, "trp_temp_array_a", 40, "fac_kingdom_37"),
				(troop_set_slot, "trp_temp_array_b", 40, 0xdc00),
				(troop_set_slot, "trp_temp_array_a", 41, "fac_kingdom_38"),
				(troop_set_slot, "trp_temp_array_b", 41, 0xe1900a),
				(troop_set_slot, "trp_temp_array_a", 42, "fac_kingdom_39"),
				(troop_set_slot, "trp_temp_array_b", 42, 0x7e233),
				(troop_set_slot, "trp_temp_array_a", 43, "fac_kingdom_40"),
				(troop_set_slot, "trp_temp_array_b", 43, 0x3254e5),
				(troop_set_slot, "trp_temp_array_a", 44, "fac_kingdom_41"),
				(troop_set_slot, "trp_temp_array_b", 44, 0x9e026a),
				(troop_set_slot, "trp_temp_array_a", 45, "fac_kingdom_42"),
				(troop_set_slot, "trp_temp_array_b", 45, 0xe8e8e8),
				(troop_set_slot, "trp_temp_array_a", 46, "fac_deserters"),
				(troop_set_slot, "trp_temp_array_b", 46, 0x888888),
				(troop_set_slot, "trp_temp_array_a", 47, "fac_mountain_bandits"),
				(troop_set_slot, "trp_temp_array_b", 47, 0x888888),
				(troop_set_slot, "trp_temp_array_a", 48, "fac_forest_bandits"),
				(troop_set_slot, "trp_temp_array_b", 48, 0x888888),
				(troop_set_slot, "trp_temp_array_a", 49, "fac_crusade"),
				(troop_set_slot, "trp_temp_array_b", 49, 0xfff17a),

				(try_for_range, ":cur_slot", 0, 50),
					(troop_get_slot, ":cur_faction", "trp_temp_array_a", ":cur_slot"),
					(str_store_faction_name, s0, ":cur_faction"), 
					(overlay_add_item, "$g_presentation_obj_1", s0),
				(try_end),
				(overlay_set_val, "$g_presentation_obj_1", "$temp"),

				

				## name and color
				(troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
				(str_store_faction_name, s0, ":cur_faction"),
				(create_text_overlay, reg1, "@Faction color of {s0}:", tf_center_justify),
				(position_set_x, pos1, 500),
				(position_set_y, pos1, 600),
				(overlay_set_position, reg1, pos1),
				(create_mesh_overlay, "$g_presentation_obj_2", "mesh_white_plane"),
				(position_set_x, pos1, 450),
				(position_set_y, pos1, 480),
				(overlay_set_position, "$g_presentation_obj_2", pos1),
				(position_set_x, pos1, 5000),
				(position_set_y, pos1, 5000),
				(overlay_set_size, "$g_presentation_obj_2", pos1),
				(faction_get_color, ":faction_color", ":cur_faction"),
				(overlay_set_color, "$g_presentation_obj_2", ":faction_color"),

				## sliders
				(position_set_x, pos1, 500),
				(create_slider_overlay, "$g_presentation_obj_3", 0, 255),
				(position_set_y, pos1, 400),
				(overlay_set_position, "$g_presentation_obj_3", pos1),
				(create_slider_overlay, "$g_presentation_obj_4", 0, 255),
				(position_set_y, pos1, 350),
				(overlay_set_position, "$g_presentation_obj_4", pos1),
				(create_slider_overlay, "$g_presentation_obj_5", 0, 255),
				(position_set_y, pos1, 300),
				(overlay_set_position, "$g_presentation_obj_5", pos1),
				(store_mod, ":blue", ":faction_color", 0x100),
				(val_div, ":faction_color", 0x100),
				(store_mod, ":green", ":faction_color", 0x100),
				(val_div, ":faction_color", 0x100),
				(store_mod, ":red", ":faction_color", 0x100),
				(overlay_set_val, "$g_presentation_obj_3", ":red"),
				(overlay_set_val, "$g_presentation_obj_4", ":green"),
				(overlay_set_val, "$g_presentation_obj_5", ":blue"),
				## num boxes
				(position_set_x, pos1, 650),
				(create_number_box_overlay, "$g_presentation_obj_6", 0, 256),
				(position_set_y, pos1, 400),
				(overlay_set_position, "$g_presentation_obj_6", pos1),
				(create_number_box_overlay, "$g_presentation_obj_7", 0, 256),
				(position_set_y, pos1, 350),
				(overlay_set_position, "$g_presentation_obj_7", pos1),
				(create_number_box_overlay, "$g_presentation_obj_8", 0, 256),
				(position_set_y, pos1, 300),
				(overlay_set_position, "$g_presentation_obj_8", pos1),
				(overlay_set_val, "$g_presentation_obj_6", ":red"),
				(overlay_set_val, "$g_presentation_obj_7", ":green"),
				(overlay_set_val, "$g_presentation_obj_8", ":blue"),
				(assign, reg2, ":red"),
				(assign, reg3, ":green"),
				(assign, reg4, ":blue"),
				## text: r g b
				(position_set_x, pos1, 330),
				(create_text_overlay, reg1, "@Red:", tf_center_justify),
				(position_set_y, pos1, 400),
				(overlay_set_position, reg1, pos1),
				(create_text_overlay, reg1, "@Green:", tf_center_justify),
				(position_set_y, pos1, 350),
				(overlay_set_position, reg1, pos1),
				(create_text_overlay, reg1, "@Blue:", tf_center_justify),
				(position_set_y, pos1, 300),
				(overlay_set_position, reg1, pos1),

				## Hexadecimal code
				(create_text_overlay, "$g_presentation_obj_9", "@ ", tf_center_justify),
				(position_set_x, pos1, 500),
				(position_set_y, pos1, 450),
				(overlay_set_position, "$g_presentation_obj_9", pos1),
				(call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
				(overlay_set_text, "$g_presentation_obj_9", "@Hexadecimal code: {s0}"),

				## default and random
				(create_game_button_overlay, "$g_presentation_obj_11", "@Default"),
				(position_set_x, pos1, 420),
				(position_set_y, pos1, 230),
				(overlay_set_position, "$g_presentation_obj_11", pos1),
				(create_game_button_overlay, "$g_presentation_obj_12", "@Randomise"),
				(position_set_x, pos1, 580),
				(position_set_y, pos1, 230),
				(overlay_set_position, "$g_presentation_obj_12", pos1),

				## color picker
				(create_mesh_overlay, reg1, "mesh_white_plane"),
				(position_set_x, pos1, 138),
				(position_set_y, pos1, 78),
				(overlay_set_position, reg1, pos1),
				(position_set_x, pos1, 36100),
				(position_set_y, pos1, 6100),
				(overlay_set_size, reg1, pos1),
				(overlay_set_color, reg1, 0),

				(assign, ":pos_x", 140),
				(assign, ":pos_y", 80),
				(try_for_range, ":cur_slot", 0, 216),
					(create_image_button_overlay, reg1, "mesh_white_plane", "mesh_white_plane"),
					(position_set_x, pos1, ":pos_x"),
					(position_set_y, pos1, ":pos_y"),
					(overlay_set_position, reg1, pos1),
					(position_set_x, pos1, 900),
					(position_set_y, pos1, 900),
					(overlay_set_size, reg1, pos1),
					(assign, ":cur_color", ":cur_slot"),
					(call_script, "script_convert_slot_no_to_color", ":cur_color"),
					(assign, ":dest_color", reg0),
					(overlay_set_color, reg1, ":dest_color"),
					(val_add, ":pos_x", 20),
					(try_begin),
						(eq, ":pos_x", 860),
						(assign, ":pos_x", 140),
						(val_add, ":pos_y", 20),
					(try_end),
					(troop_set_slot, "trp_temp_array_c", ":cur_slot", reg1),
				(try_end),

				## done
				(create_game_button_overlay, "$g_presentation_obj_10", "@Done"),
				(position_set_x, pos1, 900),
				(position_set_y, pos1, 25),
				(overlay_set_position, "$g_presentation_obj_10", pos1),
				####### mouse fix pos system #######
				#(call_script, "script_mouse_fix_pos_ready"),
				####### mouse fix pos system #######
			]),

			#(ti_on_presentation_run,
				#[
				####### mouse fix pos system #######
				#(call_script, "script_mouse_fix_pos_run"),
				####### mouse fix pos system #######
			#]),

		(ti_on_presentation_event_state_change,
			[
				(store_trigger_param_1, ":object"),
				(store_trigger_param_2, ":value"),

				(try_for_range, ":cur_slot", 0, 216),
					(troop_slot_eq, "trp_temp_array_c", ":cur_slot", ":object"),
					(assign, ":cur_color", ":cur_slot"),
					(call_script, "script_convert_slot_no_to_color", ":cur_color"),
					(assign, ":dest_color", reg0),
					(troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
					(faction_set_color, ":cur_faction", ":dest_color"),
					(overlay_set_color, "$g_presentation_obj_2", ":dest_color"),
					(store_mod, ":blue", ":dest_color", 0x100),
					(val_div, ":dest_color", 0x100),
					(store_mod, ":green", ":dest_color", 0x100),
					(val_div, ":dest_color", 0x100),
					(store_mod, ":red", ":dest_color", 0x100),
					(overlay_set_val, "$g_presentation_obj_3", ":red"),
					(overlay_set_val, "$g_presentation_obj_4", ":green"),
					(overlay_set_val, "$g_presentation_obj_5", ":blue"),
					(overlay_set_val, "$g_presentation_obj_6", ":red"),
					(overlay_set_val, "$g_presentation_obj_7", ":green"),
					(overlay_set_val, "$g_presentation_obj_8", ":blue"),
					(assign, reg2, ":red"),
					(assign, reg3, ":green"),
					(assign, reg4, ":blue"),
					(call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
					(overlay_set_text, "$g_presentation_obj_9", "@Hexadecimal code: {s0}"),
				(try_end),

				(try_begin),
					(eq, ":object", "$g_presentation_obj_1"),
					(assign, "$temp", ":value"),
					(start_presentation, "prsnt_change_all_factions_color"),
				(else_try),
					(this_or_next|eq, ":object", "$g_presentation_obj_3"),
					(eq, ":object", "$g_presentation_obj_6"),
					(overlay_set_val, "$g_presentation_obj_3", ":value"),
					(overlay_set_val, "$g_presentation_obj_6", ":value"),
					(assign, reg2, ":value"),
					(call_script, "script_get_dest_color_from_rgb", reg2, reg3, reg4),
					(assign, ":cur_color", reg0),
					(overlay_set_color, "$g_presentation_obj_2", ":cur_color"),
					(troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
					(faction_set_color, ":cur_faction", ":cur_color"),
					(call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
					(overlay_set_text, "$g_presentation_obj_9", "@Hexadecimal code: {s0}"),
				(else_try),
					(this_or_next|eq, ":object", "$g_presentation_obj_4"),
					(eq, ":object", "$g_presentation_obj_7"),
					(overlay_set_val, "$g_presentation_obj_4", ":value"),
					(overlay_set_val, "$g_presentation_obj_7", ":value"),
					(assign, reg3, ":value"),
					(call_script, "script_get_dest_color_from_rgb", reg2, reg3, reg4),
					(assign, ":cur_color", reg0),
					(overlay_set_color, "$g_presentation_obj_2", ":cur_color"),
					(troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
					(faction_set_color, ":cur_faction", ":cur_color"),
					(call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
					(overlay_set_text, "$g_presentation_obj_9", "@Hexadecimal code: {s0}"),
				(else_try),
					(this_or_next|eq, ":object", "$g_presentation_obj_5"),
					(eq, ":object", "$g_presentation_obj_8"),
					(overlay_set_val, "$g_presentation_obj_5", ":value"),
					(overlay_set_val, "$g_presentation_obj_8", ":value"),
					(assign, reg4, ":value"),
					(call_script, "script_get_dest_color_from_rgb", reg2, reg3, reg4),
					(assign, ":cur_color", reg0),
					(overlay_set_color, "$g_presentation_obj_2", ":cur_color"),
					(troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
					(faction_set_color, ":cur_faction", ":cur_color"),
					(call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
					(overlay_set_text, "$g_presentation_obj_9", "@Hexadecimal code: {s0}"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_11"),
					(troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
					(troop_get_slot, ":default_color", "trp_temp_array_b", "$temp"),
					(faction_set_color, ":cur_faction", ":default_color"),
					(overlay_set_color, "$g_presentation_obj_2", ":default_color"),
					(store_mod, ":blue", ":default_color", 0x100),
					(val_div, ":default_color", 0x100),
					(store_mod, ":green", ":default_color", 0x100),
					(val_div, ":default_color", 0x100),
					(store_mod, ":red", ":default_color", 0x100),
					(overlay_set_val, "$g_presentation_obj_3", ":red"),
					(overlay_set_val, "$g_presentation_obj_4", ":green"),
					(overlay_set_val, "$g_presentation_obj_5", ":blue"),
					(overlay_set_val, "$g_presentation_obj_6", ":red"),
					(overlay_set_val, "$g_presentation_obj_7", ":green"),
					(overlay_set_val, "$g_presentation_obj_8", ":blue"),
					(assign, reg2, ":red"),
					(assign, reg3, ":green"),
					(assign, reg4, ":blue"),
					(call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
					(overlay_set_text, "$g_presentation_obj_9", "@Hexadecimal code: {s0}"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_12"),
					(store_random_in_range, reg2, 0, 256),
					(store_random_in_range, reg3, 0, 256),
					(store_random_in_range, reg4, 0, 256),
					(overlay_set_val, "$g_presentation_obj_3", reg2),
					(overlay_set_val, "$g_presentation_obj_4", reg3),
					(overlay_set_val, "$g_presentation_obj_5", reg4),
					(overlay_set_val, "$g_presentation_obj_6", reg2),
					(overlay_set_val, "$g_presentation_obj_7", reg3),
					(overlay_set_val, "$g_presentation_obj_8", reg4),
					(call_script, "script_get_dest_color_from_rgb", reg2, reg3, reg4),
					(assign, ":cur_color", reg0),
					(overlay_set_color, "$g_presentation_obj_2", ":cur_color"),
					(troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
					(faction_set_color, ":cur_faction", ":cur_color"),
					(call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
					(overlay_set_text, "$g_presentation_obj_9", "@Hexadecimal code: {s0}"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_10"),
					(presentation_set_duration, 0),
				(try_end),
		]),
	])