from header import *

game_custom_battle_designer = (
	"game_custom_battle_designer", prsntf_manual_end_only, mesh_cb_ui_main, [
		(ti_on_presentation_load,
		 [(set_fixed_point_multiplier, 1000),

			(create_text_overlay, reg0, "str_player", tf_center_justify|tf_single_line|tf_with_outline),
			(overlay_set_color, reg0, 0xFFFFFFFF),
			(position_set_x, pos1, 1500),
			(position_set_y, pos1, 1500),
			(overlay_set_size, reg0, pos1),
			(position_set_x, pos1, 175),
			(position_set_y, pos1, 700),
			(overlay_set_position, reg0, pos1),

			(create_text_overlay, reg0, "str_enemy",  tf_center_justify|tf_single_line|tf_with_outline),
			(overlay_set_color, reg0, 0xFFFFFFFF),
			(position_set_x, pos1, 1500),
			(position_set_y, pos1, 1500),
			(overlay_set_size, reg0, pos1),
			(position_set_x, pos1, 820),
			(position_set_y, pos1, 700),
			(overlay_set_position, reg0, pos1),

			(create_text_overlay, reg0, "str_character", tf_center_justify),
			(position_set_x, pos1, 175),
			(position_set_y, pos1, 670),
			(overlay_set_position, reg0, pos1),

			(create_combo_label_overlay, "$g_presentation_obj_custom_battle_designer_18"),
			(position_set_x, pos1, 800),
			(position_set_y, pos1, 800),
			(overlay_set_size, "$g_presentation_obj_custom_battle_designer_18", pos1),
			(position_set_x, pos1, 175),
			(position_set_y, pos1, 635),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_18", pos1),
			(try_for_range, ":cur_troop", quick_battle_troops_begin, quick_battle_troops_end),
				(str_store_troop_name, s0, ":cur_troop"),
				(overlay_add_item, "$g_presentation_obj_custom_battle_designer_18", s0),
			(try_end),
			(store_sub, ":cur_troop", "$g_quick_battle_troop", quick_battle_troops_begin),
			(overlay_set_val, "$g_presentation_obj_custom_battle_designer_18", ":cur_troop"),

			(store_mul, ":cur_troop", "$g_quick_battle_troop", 2), #with weapons
			(create_mesh_overlay_with_tableau_material, reg0, -1, "tableau_game_party_window", ":cur_troop"),
			(position_set_x, pos1, 25),
			(position_set_y, pos1, 370),
			(overlay_set_position, reg0, pos1),

			(try_begin),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_1"),
				(assign, ":cur_troop", "trp_teu_horse_4"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_2"),
				(assign, ":cur_troop", "trp_balt_noble_3"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_3"),
				(assign, ":cur_troop", "trp_tatar_veteran_horse_archer"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_4"),
				(assign, ":cur_troop", "trp_nordic_knight"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_5"),
				(assign, ":cur_troop", "trp_euro_horse_4"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_6"),
				(assign, ":cur_troop", "trp_euro_horse_4"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_7"),
				(assign, ":cur_troop", "trp_euro_horse_4"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_8"),
				(assign, ":cur_troop", "trp_rus_horse_4"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_9"),
				(assign, ":cur_troop", "trp_euro_horse_4"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_10"),
				(assign, ":cur_troop", "trp_euro_horse_4"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_11"),
				(assign, ":cur_troop", "trp_nordic_knight"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_12"),
				(assign, ":cur_troop", "trp_euro_horse_4"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_13"),
				(assign, ":cur_troop", "trp_gaelic_knight"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_14"),
				(assign, ":cur_troop", "trp_nordic_knight"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_15"),
				(assign, ":cur_troop", "trp_rus_horse_4"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_16"),
				(assign, ":cur_troop", "trp_iberian_knight"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_17"),
				(assign, ":cur_troop", "trp_iberian_knight"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_18"),
				(assign, ":cur_troop", "trp_iberian_knight"),
			# (else_try),
				# (eq, "$g_quick_battle_team_2_faction", "fac_kingdom_19"),
				# (assign, ":cur_troop", "trp_euro_horse_4"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_20"),
				(assign, ":cur_troop", "trp_andalus_horse_4"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_papacy"),
				(assign, ":cur_troop", "trp_iberian_knight"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_22"),
				(assign, ":cur_troop", "trp_byz_castle_4"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_23"),
				(assign, ":cur_troop", "trp_templar_knight"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_24"),
				(assign, ":cur_troop", "trp_iberian_knight"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_25"),
				(assign, ":cur_troop", "trp_mamluke_elite_horse_archer"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_26"),
				(assign, ":cur_troop", "trp_iberian_knight"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_27"),
				(assign, ":cur_troop", "trp_tatar_heavy_lancer"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_28"),
				(assign, ":cur_troop", "trp_marinid_mounted_skirmisher_3"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_29"),
				(assign, ":cur_troop", "trp_rus_horse_4"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_30"),
				(assign, ":cur_troop", "trp_rus_horse_4"),
			(else_try),
				(eq, "$g_quick_battle_team_2_faction", "fac_kingdom_31"),
				(assign, ":cur_troop", "trp_marinid_mounted_skirmisher_3"),
			(else_try),
				(assign, ":cur_troop", "trp_taiga_bandit"),
			(try_end),
			(val_mul, ":cur_troop", 2), #with weapons
			(create_mesh_overlay_with_tableau_material, reg0, -1, "tableau_game_party_window", ":cur_troop"),
			(position_set_x, pos1, 670),
			(position_set_y, pos1, 370),
			(overlay_set_position, reg0, pos1),

			(create_text_overlay, reg0, "str_biography", tf_center_justify),
			(position_set_x, pos1, 500),
			(position_set_y, pos1, 700),
			(overlay_set_position, reg0, pos1),

			(store_sub, ":cur_troop_text", "$g_quick_battle_troop", quick_battle_troops_begin),
			(val_add, ":cur_troop_text", quick_battle_troop_texts_begin),
			(create_text_overlay, reg0, ":cur_troop_text", tf_scrollable),
			(position_set_x, pos1, 850),
			(position_set_y, pos1, 850),
			(overlay_set_size, reg0, pos1),
			(position_set_x, pos1, 320),
			(position_set_y, pos1, 560),
			(overlay_set_position, reg0, pos1),
			(position_set_x, pos1, 360),
			(position_set_y, pos1, 130),
			(overlay_set_area_size, reg0, pos1),

			(create_text_overlay, reg0, "str_map_basic", tf_center_justify),
			(overlay_set_color, reg0, 0xFFFFFF),
			(position_set_x, pos1, 1500),
			(position_set_y, pos1, 1500),
			(overlay_set_size, reg0, pos1),
			(position_set_x, pos1, 500),
			(position_set_y, pos1, 450),
			(overlay_set_position, reg0, pos1),

			(create_combo_label_overlay, "$g_presentation_obj_custom_battle_designer_1"),
			(position_set_x, pos1, 700),
			(position_set_y, pos1, 700),
			(overlay_set_size, "$g_presentation_obj_custom_battle_designer_1", pos1),
			(position_set_x, pos1, 500),
			(position_set_y, pos1, 415),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_1", pos1),
			(try_begin),
				(eq, "$g_quick_battle_game_type", 0), #battle
				(try_for_range, ":cur_scene", quick_battle_battle_scenes_begin, quick_battle_battle_scenes_end),
					(store_sub, ":cur_scene_name", ":cur_scene", quick_battle_scenes_begin),
					(val_add, ":cur_scene_name", quick_battle_scene_names_begin),
					(overlay_add_item, "$g_presentation_obj_custom_battle_designer_1", ":cur_scene_name"),
				(try_end),
				(try_begin),
					(is_between, "$g_quick_battle_map", quick_battle_battle_scenes_begin, quick_battle_battle_scenes_end),
					(store_sub, ":cur_map", "$g_quick_battle_map", quick_battle_battle_scenes_begin),
					(overlay_set_val, "$g_presentation_obj_custom_battle_designer_1", ":cur_map"),
				(else_try),
					(overlay_set_val, "$g_presentation_obj_custom_battle_designer_1", 0),
					(assign, "$g_quick_battle_map", quick_battle_battle_scenes_begin),
				(try_end),
			(else_try),
				(try_for_range, ":cur_scene", quick_battle_siege_scenes_begin, quick_battle_siege_scenes_end),
					(store_sub, ":cur_scene_name", ":cur_scene", quick_battle_scenes_begin),
					(val_add, ":cur_scene_name", quick_battle_scene_names_begin),
					(overlay_add_item, "$g_presentation_obj_custom_battle_designer_1", ":cur_scene_name"),
				(try_end),
				(try_begin),
					(is_between, "$g_quick_battle_map", quick_battle_siege_scenes_begin, quick_battle_siege_scenes_end),
					(store_sub, ":cur_map", "$g_quick_battle_map", quick_battle_siege_scenes_begin),
					(overlay_set_val, "$g_presentation_obj_custom_battle_designer_1", ":cur_map"),
				(else_try),
					(overlay_set_val, "$g_presentation_obj_custom_battle_designer_1", 0),
					(assign, "$g_quick_battle_map", quick_battle_siege_scenes_begin),
				(try_end),
			(try_end),

			(store_sub, ":cur_mesh", "$g_quick_battle_map", quick_battle_scenes_begin),
			(val_add, ":cur_mesh", quick_battle_scene_images_begin),
			(create_mesh_overlay, reg0, ":cur_mesh"),
			(position_set_x, pos1, 700),
			(position_set_y, pos1, 700),
			(overlay_set_size, reg0, pos1),
			(position_set_x, pos1, 380),
			(position_set_y, pos1, 220),
			(overlay_set_position, reg0, pos1),

			(create_text_overlay, reg0, "str_game_type_basic", tf_center_justify),
			(overlay_set_color, reg0, 0xFFFFFF),
			(position_set_x, pos1, 1500),
			(position_set_y, pos1, 1500),
			(overlay_set_size, reg0, pos1),
			(position_set_x, pos1, 500),
			(position_set_y, pos1, 180),
			(overlay_set_position, reg0, pos1),

			(create_combo_label_overlay, "$g_presentation_obj_custom_battle_designer_23"),
			(position_set_x, pos1, 700),
			(position_set_y, pos1, 700),
			(overlay_set_size, "$g_presentation_obj_custom_battle_designer_23", pos1),
			(position_set_x, pos1, 500),
			(position_set_y, pos1, 150),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_23", pos1),
			(overlay_add_item, "$g_presentation_obj_custom_battle_designer_23", "str_battle"),
			(overlay_add_item, "$g_presentation_obj_custom_battle_designer_23", "str_siege_offense"),
			(overlay_add_item, "$g_presentation_obj_custom_battle_designer_23", "str_siege_defense"),
			(overlay_set_val, "$g_presentation_obj_custom_battle_designer_23", "$g_quick_battle_game_type"),

			(create_game_button_overlay, "$g_presentation_obj_custom_battle_designer_24", "str_randomize"),
			(position_set_x, pos1, 500),
			(position_set_y, pos1, 60),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_24", pos1),

			(assign, ":cur_y", 330),
			(assign, ":cur_y", 350),
			(assign, ":cur_y_adder", 40),

			(create_text_overlay, reg0, "str_faction", tf_center_justify),
			(position_set_x, pos1, 175),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_text_overlay, reg0, "str_faction", tf_center_justify),
			(position_set_x, pos1, 820),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_combo_label_overlay, "$g_presentation_obj_custom_battle_designer_4"),
##      (position_set_x, pos1, 800),
##      (position_set_y, pos1, 800),
##      (overlay_set_size, "$g_presentation_obj_custom_battle_designer_4", pos1),
			(position_set_x, pos1, 175),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_4", pos1),
			(try_begin),
				(is_trial_version),
				(str_store_faction_name, s0, npc_kingdoms_begin),
				(overlay_add_item, "$g_presentation_obj_custom_battle_designer_4", s0),
				(store_add, ":cur_faction", npc_kingdoms_begin, 1),
				(str_store_faction_name, s0, ":cur_faction"),
				(overlay_add_item, "$g_presentation_obj_custom_battle_designer_4", s0),
			(else_try),
				(try_for_range, ":cur_faction", npc_kingdoms_begin, npc_kingdoms_end),
					(str_store_faction_name, s0, ":cur_faction"),
					(overlay_add_item, "$g_presentation_obj_custom_battle_designer_4", s0),
				(try_end),
				(str_store_faction_name, s0, "fac_outlaws"),
				(overlay_add_item, "$g_presentation_obj_custom_battle_designer_4", s0),
			(try_end),
			(try_begin),
				(eq, "$g_quick_battle_team_1_faction", "fac_outlaws"),
				(store_sub, ":overlay_value", npc_kingdoms_end, npc_kingdoms_begin),
				(overlay_set_val, "$g_presentation_obj_custom_battle_designer_4", ":overlay_value"),
			(else_try),
				(store_sub, ":team_1_faction", "$g_quick_battle_team_1_faction", npc_kingdoms_begin),
				(overlay_set_val, "$g_presentation_obj_custom_battle_designer_4", ":team_1_faction"),
			(try_end),

			(create_combo_label_overlay, "$g_presentation_obj_custom_battle_designer_5"),
##      (position_set_x, pos1, 800),
##      (position_set_y, pos1, 800),
##      (overlay_set_size, "$g_presentation_obj_custom_battle_designer_5", pos1),
			(position_set_x, pos1, 820),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_5", pos1),
			(try_begin),
				(is_trial_version),
				(str_store_faction_name, s0, npc_kingdoms_begin),
				(overlay_add_item, "$g_presentation_obj_custom_battle_designer_5", s0),
				(store_add, ":cur_faction", npc_kingdoms_begin, 1),
				(str_store_faction_name, s0, ":cur_faction"),
				(overlay_add_item, "$g_presentation_obj_custom_battle_designer_5", s0),
			(else_try),
				(try_for_range, ":cur_faction", npc_kingdoms_begin, npc_kingdoms_end),
					(str_store_faction_name, s0, ":cur_faction"),
					(overlay_add_item, "$g_presentation_obj_custom_battle_designer_5", s0),
				(try_end),
				(str_store_faction_name, s0, "fac_outlaws"),
				(overlay_add_item, "$g_presentation_obj_custom_battle_designer_5", s0),
			(try_end),
			(try_begin),
				(eq, "$g_quick_battle_team_2_faction", "fac_outlaws"),
				(store_sub, ":overlay_value", npc_kingdoms_end, npc_kingdoms_begin),
				(overlay_set_val, "$g_presentation_obj_custom_battle_designer_5", ":overlay_value"),
			(else_try),
				(store_sub, ":team_2_faction", "$g_quick_battle_team_2_faction", npc_kingdoms_begin),
				(overlay_set_val, "$g_presentation_obj_custom_battle_designer_5", ":team_2_faction"),
			(try_end),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_army_composition", tf_center_justify),
			(position_set_x, pos1, 175),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_text_overlay, reg0, "str_army_composition", tf_center_justify),
			(position_set_x, pos1, 820),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(try_begin),
				(eq, "$g_presentation_obj_custom_battle_designer_6_last_value", 0),
				(eq, "$g_presentation_obj_custom_battle_designer_7_last_value", 0),
				(eq, "$g_presentation_obj_custom_battle_designer_8_last_value", 0),
				(eq, "$g_presentation_obj_custom_battle_designer_9_last_value", 0),
				(eq, "$g_presentation_obj_custom_battle_designer_10_last_value", 0),
				(eq, "$g_presentation_obj_custom_battle_designer_11_last_value", 0),
				(assign, "$g_presentation_obj_custom_battle_designer_6_last_value", 34),
				(assign, "$g_presentation_obj_custom_battle_designer_7_last_value", 33),
				(assign, "$g_presentation_obj_custom_battle_designer_8_last_value", 33),
				(assign, "$g_presentation_obj_custom_battle_designer_9_last_value", 34),
				(assign, "$g_presentation_obj_custom_battle_designer_10_last_value", 33),
				(assign, "$g_presentation_obj_custom_battle_designer_11_last_value", 33),
				(assign, "$g_presentation_obj_custom_battle_designer_6_locked", 0),
				(assign, "$g_presentation_obj_custom_battle_designer_7_locked", 0),
				(assign, "$g_presentation_obj_custom_battle_designer_8_locked", 0),
				(assign, "$g_presentation_obj_custom_battle_designer_9_locked", 0),
				(assign, "$g_presentation_obj_custom_battle_designer_10_locked", 0),
				(assign, "$g_presentation_obj_custom_battle_designer_11_locked", 0),
			(try_end),

			(create_mesh_overlay, reg0, "mesh_cb_ui_icon_infantry"),
			(position_set_x, pos1, 5),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),
			(position_set_x, pos1, 400),
			(position_set_y, pos1, 400),
			(overlay_set_size, reg0, pos1),

			(create_mesh_overlay, reg0, "mesh_cb_ui_icon_infantry"),
			(position_set_x, pos1, 650),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),
			(position_set_x, pos1, 400),
			(position_set_y, pos1, 400),
			(overlay_set_size, reg0, pos1),

			(create_slider_overlay, "$g_presentation_obj_custom_battle_designer_6", 0, 100),
			(overlay_set_val, "$g_presentation_obj_custom_battle_designer_6", "$g_presentation_obj_custom_battle_designer_6_last_value"),
			(position_set_x, pos1, 900),
			(position_set_y, pos1, 1000),
			(overlay_set_size, "$g_presentation_obj_custom_battle_designer_6", pos1),
			(position_set_x, pos1, 175),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_6", pos1),

			(assign, reg0, "$g_presentation_obj_custom_battle_designer_6_last_value"),
			(create_text_overlay, "$g_presentation_obj_custom_battle_designer_12", "str_reg0_percent", 0),
			(position_set_x, pos1, 295),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_12", pos1),

			(create_slider_overlay, "$g_presentation_obj_custom_battle_designer_9", 0, 100),
			(overlay_set_val, "$g_presentation_obj_custom_battle_designer_9", "$g_presentation_obj_custom_battle_designer_9_last_value"),
			(position_set_x, pos1, 900),
			(position_set_y, pos1, 1000),
			(overlay_set_size, "$g_presentation_obj_custom_battle_designer_9", pos1),
			(position_set_x, pos1, 820),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_9", pos1),

			(assign, reg0, "$g_presentation_obj_custom_battle_designer_9_last_value"),
			(create_text_overlay, "$g_presentation_obj_custom_battle_designer_15", "str_reg0_percent", 0),
			(position_set_x, pos1, 940),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_15", pos1),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_mesh_overlay, reg0, "mesh_cb_ui_icon_archer"),
			(position_set_x, pos1, 15),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),
			(position_set_x, pos1, 400),
			(position_set_y, pos1, 400),
			(overlay_set_size, reg0, pos1),

			(create_mesh_overlay, reg0, "mesh_cb_ui_icon_archer"),
			(position_set_x, pos1, 660),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),
			(position_set_x, pos1, 400),
			(position_set_y, pos1, 400),
			(overlay_set_size, reg0, pos1),

			(create_slider_overlay, "$g_presentation_obj_custom_battle_designer_7", 0, 100),
			(overlay_set_val, "$g_presentation_obj_custom_battle_designer_7", "$g_presentation_obj_custom_battle_designer_7_last_value"),
			(position_set_x, pos1, 900),
			(position_set_y, pos1, 1000),
			(overlay_set_size, "$g_presentation_obj_custom_battle_designer_7", pos1),
			(position_set_x, pos1, 175),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_7", pos1),

			(assign, reg0, "$g_presentation_obj_custom_battle_designer_7_last_value"),
			(create_text_overlay, "$g_presentation_obj_custom_battle_designer_13", "str_reg0_percent", 0),
			(position_set_x, pos1, 295),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_13", pos1),

			(create_slider_overlay, "$g_presentation_obj_custom_battle_designer_10", 0, 100),
			(overlay_set_val, "$g_presentation_obj_custom_battle_designer_10", "$g_presentation_obj_custom_battle_designer_10_last_value"),
			(position_set_x, pos1, 900),
			(position_set_y, pos1, 1000),
			(overlay_set_size, "$g_presentation_obj_custom_battle_designer_10", pos1),
			(position_set_x, pos1, 820),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_10", pos1),

			(assign, reg0, "$g_presentation_obj_custom_battle_designer_10_last_value"),
			(create_text_overlay, "$g_presentation_obj_custom_battle_designer_16", "str_reg0_percent", 0),
			(position_set_x, pos1, 940),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_16", pos1),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_mesh_overlay, reg0, "mesh_cb_ui_icon_horseman"),
			(position_set_x, pos1, 10),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),
			(position_set_x, pos1, 400),
			(position_set_y, pos1, 400),
			(overlay_set_size, reg0, pos1),

			(create_mesh_overlay, reg0, "mesh_cb_ui_icon_horseman"),
			(position_set_x, pos1, 655),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),
			(position_set_x, pos1, 400),
			(position_set_y, pos1, 400),
			(overlay_set_size, reg0, pos1),

			(create_slider_overlay, "$g_presentation_obj_custom_battle_designer_8", 0, 100),
			(overlay_set_val, "$g_presentation_obj_custom_battle_designer_8", "$g_presentation_obj_custom_battle_designer_8_last_value"),
			(position_set_x, pos1, 900),
			(position_set_y, pos1, 1000),
			(overlay_set_size, "$g_presentation_obj_custom_battle_designer_8", pos1),
			(position_set_x, pos1, 175),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_8", pos1),

			(assign, reg0, "$g_presentation_obj_custom_battle_designer_8_last_value"),
			(create_text_overlay, "$g_presentation_obj_custom_battle_designer_14", "str_reg0_percent", 0),
			(position_set_x, pos1, 295),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_14", pos1),

			(create_slider_overlay, "$g_presentation_obj_custom_battle_designer_11", 0, 100),
			(overlay_set_val, "$g_presentation_obj_custom_battle_designer_11", "$g_presentation_obj_custom_battle_designer_11_last_value"),
			(position_set_x, pos1, 900),
			(position_set_y, pos1, 1000),
			(overlay_set_size, "$g_presentation_obj_custom_battle_designer_11", pos1),
			(position_set_x, pos1, 820),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_11", pos1),

			(assign, reg0, "$g_presentation_obj_custom_battle_designer_11_last_value"),
			(create_text_overlay, "$g_presentation_obj_custom_battle_designer_17", "str_reg0_percent", 0),
			(position_set_x, pos1, 940),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_17", pos1),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_army_size", tf_center_justify),
			(position_set_x, pos1, 175),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_text_overlay, reg0, "str_army_size", tf_center_justify),
			(position_set_x, pos1, 820),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(try_begin),
				(is_trial_version),
				(val_min, "$g_quick_battle_army_1_size", 25),
				(val_min, "$g_quick_battle_army_2_size", 25),
			(try_end),

			(create_slider_overlay, "$g_presentation_obj_custom_battle_designer_2", 0, 100),
			(overlay_set_boundaries, "$g_presentation_obj_custom_battle_designer_2", 1000, 75000),
			(overlay_set_val, "$g_presentation_obj_custom_battle_designer_2", "$g_quick_battle_army_1_size"),
			(position_set_x, pos1, 900),
			(position_set_y, pos1, 1000),
			(overlay_set_size, "$g_presentation_obj_custom_battle_designer_2", pos1),
			(position_set_x, pos1, 135),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_2", pos1),

			(call_script, "script_get_army_size_from_slider_value", "$g_quick_battle_army_1_size"),
			(create_text_overlay, "$g_presentation_obj_custom_battle_designer_21", "str_reg0_men", 0),
			(position_set_x, pos1, 255),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_21", pos1),

			(create_slider_overlay, "$g_presentation_obj_custom_battle_designer_3", 200),
			(overlay_set_boundaries, "$g_presentation_obj_custom_battle_designer_3", 1000, 75000),
			(overlay_set_val, "$g_presentation_obj_custom_battle_designer_3", "$g_quick_battle_army_2_size"),
			(position_set_x, pos1, 900),
			(position_set_y, pos1, 1000),
			(overlay_set_size, "$g_presentation_obj_custom_battle_designer_3", pos1),
			(position_set_x, pos1, 780),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_3", pos1),

			(call_script, "script_get_army_size_from_slider_value", "$g_quick_battle_army_2_size"),
			(create_text_overlay, "$g_presentation_obj_custom_battle_designer_22", "str_reg0_men", 0),
			(position_set_x, pos1, 900),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_22", pos1),

			(create_game_button_overlay, "$g_presentation_obj_custom_battle_designer_19", "str_start", 0),
			(position_set_x, pos1, 415),
			(position_set_y, pos1, 10),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_19", pos1),

			(create_game_button_overlay, "$g_presentation_obj_custom_battle_designer_20", "str_back", 0),
			(position_set_x, pos1, 585),
			(position_set_y, pos1, 10),
			(overlay_set_position, "$g_presentation_obj_custom_battle_designer_20", pos1),

			(presentation_set_duration, 999999),
			]),

		(ti_on_presentation_event_state_change,
		 [
			 (store_trigger_param_1, ":object"),
			 (store_trigger_param_2, ":value"),
			 (try_begin),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_1"),
				 (try_begin),
					 (eq, "$g_quick_battle_game_type", 0),
					 (store_add, "$g_quick_battle_map", ":value", quick_battle_battle_scenes_begin),
				 (else_try),
					 (store_add, "$g_quick_battle_map", ":value", quick_battle_siege_scenes_begin),
				 (try_end),
				 (presentation_set_duration, 0),
				 (start_presentation, "prsnt_game_custom_battle_designer"),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_23"),
				 (assign, "$g_quick_battle_game_type", ":value"),
				 (presentation_set_duration, 0),
				 (start_presentation, "prsnt_game_custom_battle_designer"),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_24"),
				 (store_random_in_range, "$g_quick_battle_game_type", 0, 3),
				 (store_random_in_range, "$g_quick_battle_troop", quick_battle_troops_begin, quick_battle_troops_end),
				 (try_begin),
					 (is_trial_version),
					 (store_random_in_range, "$g_quick_battle_team_1_faction", 0, 2),
					 (try_begin),
						 (eq, "$g_quick_battle_team_1_faction", 0),
						 (assign, "$g_quick_battle_team_2_faction", 1),
					 (else_try),
						 (assign, "$g_quick_battle_team_2_faction", 0),
					 (try_end),
					 (val_add, "$g_quick_battle_team_1_faction", npc_kingdoms_begin),
					 (val_add, "$g_quick_battle_team_2_faction", npc_kingdoms_begin),
					 (store_random_in_range, "$g_quick_battle_army_1_size", 10, 16),
					 (store_random_in_range, ":random_army_size", 0, 6),
					 (val_add, "$g_quick_battle_army_1_size", ":random_army_size"),
					 (store_random_in_range, ":random_army_size", 0, 6),
					 (val_add, "$g_quick_battle_army_1_size", ":random_army_size"),
				 (else_try),
					 (store_sub, ":num_factions", npc_kingdoms_end, npc_kingdoms_begin),
					 (val_add, ":num_factions", 1),
					 (store_random_in_range, "$g_quick_battle_team_1_faction", 0, ":num_factions"),
					 (try_begin),
						 (eq, "$g_quick_battle_team_1_faction", 0),
						 (assign, "$g_quick_battle_team_1_faction", "fac_outlaws"),
					 (else_try),
						 (val_add, "$g_quick_battle_team_1_faction", npc_kingdoms_begin),
						 (val_sub, "$g_quick_battle_team_1_faction", 1),
					 (try_end),
					 (assign, ":end_cond", 1000),
					 (try_for_range, ":unused", 0, ":end_cond"),
						 (store_random_in_range, "$g_quick_battle_team_2_faction", 0, ":num_factions"),
						 (try_begin),
							 (eq, "$g_quick_battle_team_2_faction", 0),
							 (assign, "$g_quick_battle_team_2_faction", "fac_outlaws"),
						 (else_try),
							 (val_add, "$g_quick_battle_team_2_faction", npc_kingdoms_begin),
							 (val_sub, "$g_quick_battle_team_2_faction", 1),
						 (try_end),
						 (neq, "$g_quick_battle_team_1_faction", "$g_quick_battle_team_2_faction"),
						 (assign, ":end_cond", 0),
					 (try_end),
					 (store_random_in_range, "$g_quick_battle_army_1_size", 10, 21),
					 (store_random_in_range, ":random_army_size", 0, 11),
					 (val_add, "$g_quick_battle_army_1_size", ":random_army_size"),
					 (store_random_in_range, ":random_army_size", 0, 11),
					 (val_add, "$g_quick_battle_army_1_size", ":random_army_size"),
				 (try_end),
				 (assign, "$g_quick_battle_army_2_size", "$g_quick_battle_army_1_size"),
				 (try_begin),
					 (eq, "$g_quick_battle_game_type", 0), #battle
					 (store_random_in_range, "$g_quick_battle_map", quick_battle_battle_scenes_begin, quick_battle_battle_scenes_end),
					 (store_random_in_range, ":random_type", 0, 3),
					 (store_random_in_range, ":random_type_2", 0, 2),
					 (store_random_in_range, ":random_composition", 0, 100),
					 (store_sub, ":left_max", 100, ":random_composition"),
					 (store_random_in_range, ":random_composition_2", 0, ":left_max"),
					 (store_sub, ":random_composition_3", ":left_max", ":random_composition_2"),
					 (try_begin),
						 (eq, ":random_type", 0),
						 (assign, "$g_presentation_obj_custom_battle_designer_6_last_value", ":random_composition"),
						 (try_begin),
							 (eq, ":random_type_2", 0),
							 (assign, "$g_presentation_obj_custom_battle_designer_7_last_value", ":random_composition_2"),
							 (assign, "$g_presentation_obj_custom_battle_designer_8_last_value", ":random_composition_3"),
						 (else_try),
							 (assign, "$g_presentation_obj_custom_battle_designer_8_last_value", ":random_composition_2"),
							 (assign, "$g_presentation_obj_custom_battle_designer_7_last_value", ":random_composition_3"),
						 (try_end),
					 (else_try),
						 (eq, ":random_type", 1),
						 (assign, "$g_presentation_obj_custom_battle_designer_7_last_value", ":random_composition"),
						 (try_begin),
							 (eq, ":random_type_2", 0),
							 (assign, "$g_presentation_obj_custom_battle_designer_6_last_value", ":random_composition_2"),
							 (assign, "$g_presentation_obj_custom_battle_designer_8_last_value", ":random_composition_3"),
						 (else_try),
							 (assign, "$g_presentation_obj_custom_battle_designer_8_last_value", ":random_composition_2"),
							 (assign, "$g_presentation_obj_custom_battle_designer_6_last_value", ":random_composition_3"),
						 (try_end),
					 (else_try),
						 (assign, "$g_presentation_obj_custom_battle_designer_8_last_value", ":random_composition"),
						 (try_begin),
							 (eq, ":random_type_2", 0),
							 (assign, "$g_presentation_obj_custom_battle_designer_6_last_value", ":random_composition_2"),
							 (assign, "$g_presentation_obj_custom_battle_designer_7_last_value", ":random_composition_3"),
						 (else_try),
							 (assign, "$g_presentation_obj_custom_battle_designer_7_last_value", ":random_composition_2"),
							 (assign, "$g_presentation_obj_custom_battle_designer_6_last_value", ":random_composition_3"),
						 (try_end),
					 (try_end),
					 (store_random_in_range, ":random_type", 0, 3),
					 (store_random_in_range, ":random_type_2", 0, 2),
					 (store_random_in_range, ":random_composition", 0, 100),
					 (store_sub, ":left_max", 100, ":random_composition"),
					 (store_random_in_range, ":random_composition_2", 0, ":left_max"),
					 (store_sub, ":random_composition_3", ":left_max", ":random_composition_2"),
					 (try_begin),
						 (eq, ":random_type", 0),
						 (assign, "$g_presentation_obj_custom_battle_designer_9_last_value", ":random_composition"),
						 (try_begin),
							 (eq, ":random_type_2", 0),
							 (assign, "$g_presentation_obj_custom_battle_designer_10_last_value", ":random_composition_2"),
							 (assign, "$g_presentation_obj_custom_battle_designer_11_last_value", ":random_composition_3"),
						 (else_try),
							 (assign, "$g_presentation_obj_custom_battle_designer_11_last_value", ":random_composition_2"),
							 (assign, "$g_presentation_obj_custom_battle_designer_10_last_value", ":random_composition_3"),
						 (try_end),
					 (else_try),
						 (eq, ":random_type", 1),
						 (assign, "$g_presentation_obj_custom_battle_designer_10_last_value", ":random_composition"),
						 (try_begin),
							 (eq, ":random_type_2", 0),
							 (assign, "$g_presentation_obj_custom_battle_designer_9_last_value", ":random_composition_2"),
							 (assign, "$g_presentation_obj_custom_battle_designer_11_last_value", ":random_composition_3"),
						 (else_try),
							 (assign, "$g_presentation_obj_custom_battle_designer_11_last_value", ":random_composition_2"),
							 (assign, "$g_presentation_obj_custom_battle_designer_9_last_value", ":random_composition_3"),
						 (try_end),
					 (else_try),
						 (assign, "$g_presentation_obj_custom_battle_designer_11_last_value", ":random_composition"),
						 (try_begin),
							 (eq, ":random_type_2", 0),
							 (assign, "$g_presentation_obj_custom_battle_designer_9_last_value", ":random_composition_2"),
							 (assign, "$g_presentation_obj_custom_battle_designer_10_last_value", ":random_composition_3"),
						 (else_try),
							 (assign, "$g_presentation_obj_custom_battle_designer_10_last_value", ":random_composition_2"),
							 (assign, "$g_presentation_obj_custom_battle_designer_9_last_value", ":random_composition_3"),
						 (try_end),
					 (try_end),
				 (else_try),
					 (eq, "$g_quick_battle_game_type", 1), #siege offense
					 (store_random_in_range, "$g_quick_battle_map", quick_battle_siege_scenes_begin, quick_battle_siege_scenes_end),
					 #defender is enemy
					 (store_random_in_range, "$g_presentation_obj_custom_battle_designer_10_last_value", 30, 100), #min 30% archer
					 (store_sub, "$g_presentation_obj_custom_battle_designer_9_last_value", 100, "$g_presentation_obj_custom_battle_designer_10_last_value"),
					 (assign, "$g_presentation_obj_custom_battle_designer_11_last_value", 0), #no cavalry
					 (store_random_in_range, "$g_presentation_obj_custom_battle_designer_6_last_value", 20, 100), #min 20% infantry
					 (store_sub, "$g_presentation_obj_custom_battle_designer_7_last_value", 100, "$g_presentation_obj_custom_battle_designer_6_last_value"),
					 (assign, "$g_presentation_obj_custom_battle_designer_8_last_value", 0), #no cavalry
				 (else_try),
					 #siege defense
					 (store_random_in_range, "$g_quick_battle_map", quick_battle_siege_scenes_begin, quick_battle_siege_scenes_end),
					 #defender is player
					 (store_random_in_range, "$g_presentation_obj_custom_battle_designer_7_last_value", 30, 100), #min 30% archer
					 (store_sub, "$g_presentation_obj_custom_battle_designer_6_last_value", 100, "$g_presentation_obj_custom_battle_designer_7_last_value"),
					 (assign, "$g_presentation_obj_custom_battle_designer_8_last_value", 0), #no cavalry
					 (store_random_in_range, "$g_presentation_obj_custom_battle_designer_9_last_value", 20, 100), #min 20% infantry
					 (store_sub, "$g_presentation_obj_custom_battle_designer_10_last_value", 100, "$g_presentation_obj_custom_battle_designer_9_last_value"),
					 (assign, "$g_presentation_obj_custom_battle_designer_11_last_value", 0), #no cavalry
				 (try_end),
				 (presentation_set_duration, 0),
				 (start_presentation, "prsnt_game_custom_battle_designer"),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_2"),
				 (assign, "$g_quick_battle_army_1_size", ":value"),
				 (try_begin),
					 (is_trial_version),
					 (gt, "$g_quick_battle_army_1_size", 25),
					 (assign, "$g_quick_battle_army_1_size", 25),
					 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_2", 25),
				 (try_end),
				 (call_script, "script_get_army_size_from_slider_value", "$g_quick_battle_army_1_size"),
				 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_21", "str_reg0_men"),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_3"),
				 (assign, "$g_quick_battle_army_2_size", ":value"),
				 (try_begin),
					 (is_trial_version),
					 (gt, "$g_quick_battle_army_2_size", 25),
					 (assign, "$g_quick_battle_army_2_size", 25),
					 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_3", 25),
				 (try_end),
				 (call_script, "script_get_army_size_from_slider_value", "$g_quick_battle_army_2_size"),
				 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_22", "str_reg0_men"),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_4"),
				 (try_begin),
					 (store_sub, ":outlaw_index", npc_kingdoms_end, npc_kingdoms_begin),
					 (eq, ":value", ":outlaw_index"),
					 (assign, "$g_quick_battle_team_1_faction", "fac_outlaws"),
				 (else_try),
					 (store_add, "$g_quick_battle_team_1_faction", ":value", npc_kingdoms_begin),
				 (try_end),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_5"),
				 (try_begin),
					 (store_sub, ":outlaw_index", npc_kingdoms_end, npc_kingdoms_begin),
					 (eq, ":value", ":outlaw_index"),
					 (assign, "$g_quick_battle_team_2_faction", "fac_outlaws"),
				 (else_try),
					 (store_add, "$g_quick_battle_team_2_faction", ":value", npc_kingdoms_begin),
				 (try_end),
				 (presentation_set_duration, 0),
				 (start_presentation, "prsnt_game_custom_battle_designer"),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_18"),
				 (store_add, "$g_quick_battle_troop", ":value", quick_battle_troops_begin),
				 (presentation_set_duration, 0),
				 (start_presentation, "prsnt_game_custom_battle_designer"),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_6"),
				 (try_begin),
					 (eq, "$g_presentation_obj_custom_battle_designer_6_locked", 1),
					 (neq, ":value", "$g_presentation_obj_custom_battle_designer_6_last_value"),
					 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_6", "$g_presentation_obj_custom_battle_designer_6_last_value"),
				 (else_try),
					 (try_begin),
						 (lt, ":value", "$g_presentation_obj_custom_battle_designer_6_last_value"),
						 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_6_last_value", ":value"),
						 (try_begin),
							 (eq, "$g_presentation_obj_custom_battle_designer_7_locked", 1),
							 (assign, ":first_dif", 0),
							 (assign, ":second_dif", ":dif"),
						 (else_try),
							 (eq, "$g_presentation_obj_custom_battle_designer_8_locked", 1),
							 (assign, ":first_dif", ":dif"),
							 (assign, ":second_dif", 0),
						 (else_try),
							 (store_div, ":first_dif", ":dif", 2),
							 (store_sub, ":second_dif", ":dif", ":first_dif"),
							 (try_begin),
								 (neq, ":first_dif", ":second_dif"),
								 (store_random_in_range, ":random_no", 0, 2),
								 (eq, ":random_no", 0),
								 (val_sub, ":second_dif", 1),
								 (val_add, ":first_dif", 1),
							 (try_end),
						 (try_end),
						 (assign, "$g_presentation_obj_custom_battle_designer_6_last_value", ":value"),
						 (val_add, "$g_presentation_obj_custom_battle_designer_7_last_value", ":first_dif"),
						 (val_add, "$g_presentation_obj_custom_battle_designer_8_last_value", ":second_dif"),
						 (try_begin),
							 (gt, "$g_presentation_obj_custom_battle_designer_7_last_value", 100),
							 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_7_last_value", 100),
							 (val_add, "$g_presentation_obj_custom_battle_designer_8_last_value", ":dif"),
							 (assign, "$g_presentation_obj_custom_battle_designer_7_last_value", 100),
						 (else_try),
							 (gt, "$g_presentation_obj_custom_battle_designer_8_last_value", 100),
							 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_8_last_value", 100),
							 (val_add, "$g_presentation_obj_custom_battle_designer_7_last_value", ":dif"),
							 (assign, "$g_presentation_obj_custom_battle_designer_8_last_value", 100),
						 (try_end),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_7", "$g_presentation_obj_custom_battle_designer_7_last_value"),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_8", "$g_presentation_obj_custom_battle_designer_8_last_value"),
					 (else_try),
						 (gt, ":value", "$g_presentation_obj_custom_battle_designer_6_last_value"),
						 (store_sub, ":dif", ":value", "$g_presentation_obj_custom_battle_designer_6_last_value"),
						 (try_begin),
							 (eq, "$g_presentation_obj_custom_battle_designer_7_locked", 1),
							 (assign, ":first_dif", 0),
							 (assign, ":second_dif", ":dif"),
						 (else_try),
							 (eq, "$g_presentation_obj_custom_battle_designer_8_locked", 1),
							 (assign, ":first_dif", ":dif"),
							 (assign, ":second_dif", 0),
						 (else_try),
							 (store_div, ":first_dif", ":dif", 2),
							 (store_sub, ":second_dif", ":dif", ":first_dif"),
							 (try_begin),
								 (neq, ":first_dif", ":second_dif"),
								 (store_random_in_range, ":random_no", 0, 2),
								 (eq, ":random_no", 0),
								 (val_sub, ":second_dif", 1),
								 (val_add, ":first_dif", 1),
							 (try_end),
						 (try_end),
						 (assign, "$g_presentation_obj_custom_battle_designer_6_last_value", ":value"),
						 (val_sub, "$g_presentation_obj_custom_battle_designer_7_last_value", ":first_dif"),
						 (val_sub, "$g_presentation_obj_custom_battle_designer_8_last_value", ":second_dif"),
						 (try_begin),
							 (lt, "$g_presentation_obj_custom_battle_designer_7_last_value", 0),
							 (val_add, "$g_presentation_obj_custom_battle_designer_8_last_value", "$g_presentation_obj_custom_battle_designer_7_last_value"),
							 (assign, "$g_presentation_obj_custom_battle_designer_7_last_value", 0),
						 (else_try),
							 (lt, "$g_presentation_obj_custom_battle_designer_8_last_value", 0),
							 (val_add, "$g_presentation_obj_custom_battle_designer_7_last_value", "$g_presentation_obj_custom_battle_designer_8_last_value"),
							 (assign, "$g_presentation_obj_custom_battle_designer_8_last_value", 0),
						 (try_end),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_7", "$g_presentation_obj_custom_battle_designer_7_last_value"),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_8", "$g_presentation_obj_custom_battle_designer_8_last_value"),
					 (try_end),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_6_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_12", "str_reg0_percent"),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_7_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_13", "str_reg0_percent"),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_8_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_14", "str_reg0_percent"),
				 (try_end),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_7"),
				 (try_begin),
					 (eq, "$g_presentation_obj_custom_battle_designer_7_locked", 1),
					 (neq, ":value", "$g_presentation_obj_custom_battle_designer_7_last_value"),
					 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_7", "$g_presentation_obj_custom_battle_designer_7_last_value"),
				 (else_try),
					 (try_begin),
						 (lt, ":value", "$g_presentation_obj_custom_battle_designer_7_last_value"),
						 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_7_last_value", ":value"),
						 (try_begin),
							 (eq, "$g_presentation_obj_custom_battle_designer_6_locked", 1),
							 (assign, ":first_dif", 0),
							 (assign, ":second_dif", ":dif"),
						 (else_try),
							 (eq, "$g_presentation_obj_custom_battle_designer_8_locked", 1),
							 (assign, ":first_dif", ":dif"),
							 (assign, ":second_dif", 0),
						 (else_try),
							 (store_div, ":first_dif", ":dif", 2),
							 (store_sub, ":second_dif", ":dif", ":first_dif"),
							 (try_begin),
								 (neq, ":first_dif", ":second_dif"),
								 (store_random_in_range, ":random_no", 0, 2),
								 (eq, ":random_no", 0),
								 (val_sub, ":second_dif", 1),
								 (val_add, ":first_dif", 1),
							 (try_end),
						 (try_end),
						 (assign, "$g_presentation_obj_custom_battle_designer_7_last_value", ":value"),
						 (val_add, "$g_presentation_obj_custom_battle_designer_6_last_value", ":first_dif"),
						 (val_add, "$g_presentation_obj_custom_battle_designer_8_last_value", ":second_dif"),
						 (try_begin),
							 (gt, "$g_presentation_obj_custom_battle_designer_6_last_value", 100),
							 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_6_last_value", 100),
							 (val_add, "$g_presentation_obj_custom_battle_designer_8_last_value", ":dif"),
							 (assign, "$g_presentation_obj_custom_battle_designer_6_last_value", 100),
						 (else_try),
							 (gt, "$g_presentation_obj_custom_battle_designer_8_last_value", 100),
							 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_8_last_value", 100),
							 (val_add, "$g_presentation_obj_custom_battle_designer_6_last_value", ":dif"),
							 (assign, "$g_presentation_obj_custom_battle_designer_8_last_value", 100),
						 (try_end),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_6", "$g_presentation_obj_custom_battle_designer_6_last_value"),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_8", "$g_presentation_obj_custom_battle_designer_8_last_value"),
					 (else_try),
						 (gt, ":value", "$g_presentation_obj_custom_battle_designer_7_last_value"),
						 (store_sub, ":dif", ":value", "$g_presentation_obj_custom_battle_designer_7_last_value"),
						 (try_begin),
							 (eq, "$g_presentation_obj_custom_battle_designer_6_locked", 1),
							 (assign, ":first_dif", 0),
							 (assign, ":second_dif", ":dif"),
						 (else_try),
							 (eq, "$g_presentation_obj_custom_battle_designer_8_locked", 1),
							 (assign, ":first_dif", ":dif"),
							 (assign, ":second_dif", 0),
						 (else_try),
							 (store_div, ":first_dif", ":dif", 2),
							 (store_sub, ":second_dif", ":dif", ":first_dif"),
							 (try_begin),
								 (neq, ":first_dif", ":second_dif"),
								 (store_random_in_range, ":random_no", 0, 2),
								 (eq, ":random_no", 0),
								 (val_sub, ":second_dif", 1),
								 (val_add, ":first_dif", 1),
							 (try_end),
						 (try_end),
						 (assign, "$g_presentation_obj_custom_battle_designer_7_last_value", ":value"),
						 (val_sub, "$g_presentation_obj_custom_battle_designer_6_last_value", ":first_dif"),
						 (val_sub, "$g_presentation_obj_custom_battle_designer_8_last_value", ":second_dif"),
						 (try_begin),
							 (lt, "$g_presentation_obj_custom_battle_designer_6_last_value", 0),
							 (val_add, "$g_presentation_obj_custom_battle_designer_8_last_value", "$g_presentation_obj_custom_battle_designer_6_last_value"),
							 (assign, "$g_presentation_obj_custom_battle_designer_6_last_value", 0),
						 (else_try),
							 (lt, "$g_presentation_obj_custom_battle_designer_8_last_value", 0),
							 (val_add, "$g_presentation_obj_custom_battle_designer_6_last_value", "$g_presentation_obj_custom_battle_designer_8_last_value"),
							 (assign, "$g_presentation_obj_custom_battle_designer_8_last_value", 0),
						 (try_end),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_6", "$g_presentation_obj_custom_battle_designer_6_last_value"),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_8", "$g_presentation_obj_custom_battle_designer_8_last_value"),
					 (try_end),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_6_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_12", "str_reg0_percent"),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_7_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_13", "str_reg0_percent"),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_8_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_14", "str_reg0_percent"),
				 (try_end),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_8"),
					 (try_begin),
						 (eq, "$g_presentation_obj_custom_battle_designer_8_locked", 1),
						 (neq, ":value", "$g_presentation_obj_custom_battle_designer_8_last_value"),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_8", "$g_presentation_obj_custom_battle_designer_8_last_value"),
					 (else_try),
					 (try_begin),
						 (lt, ":value", "$g_presentation_obj_custom_battle_designer_8_last_value"),
						 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_8_last_value", ":value"),
						 (try_begin),
							 (eq, "$g_presentation_obj_custom_battle_designer_7_locked", 1),
							 (assign, ":first_dif", 0),
							 (assign, ":second_dif", ":dif"),
						 (else_try),
							 (eq, "$g_presentation_obj_custom_battle_designer_6_locked", 1),
							 (assign, ":first_dif", ":dif"),
							 (assign, ":second_dif", 0),
						 (else_try),
							 (store_div, ":first_dif", ":dif", 2),
							 (store_sub, ":second_dif", ":dif", ":first_dif"),
							 (try_begin),
								 (neq, ":first_dif", ":second_dif"),
								 (store_random_in_range, ":random_no", 0, 2),
								 (eq, ":random_no", 0),
								 (val_sub, ":second_dif", 1),
								 (val_add, ":first_dif", 1),
							 (try_end),
						 (try_end),
						 (assign, "$g_presentation_obj_custom_battle_designer_8_last_value", ":value"),
						 (val_add, "$g_presentation_obj_custom_battle_designer_7_last_value", ":first_dif"),
						 (val_add, "$g_presentation_obj_custom_battle_designer_6_last_value", ":second_dif"),
						 (try_begin),
							 (gt, "$g_presentation_obj_custom_battle_designer_7_last_value", 100),
							 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_7_last_value", 100),
							 (val_add, "$g_presentation_obj_custom_battle_designer_6_last_value", ":dif"),
							 (assign, "$g_presentation_obj_custom_battle_designer_7_last_value", 100),
						 (else_try),
							 (gt, "$g_presentation_obj_custom_battle_designer_6_last_value", 100),
							 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_6_last_value", 100),
							 (val_add, "$g_presentation_obj_custom_battle_designer_7_last_value", ":dif"),
							 (assign, "$g_presentation_obj_custom_battle_designer_6_last_value", 100),
						 (try_end),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_7", "$g_presentation_obj_custom_battle_designer_7_last_value"),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_6", "$g_presentation_obj_custom_battle_designer_6_last_value"),
					 (else_try),
						 (gt, ":value", "$g_presentation_obj_custom_battle_designer_8_last_value"),
						 (store_sub, ":dif", ":value", "$g_presentation_obj_custom_battle_designer_8_last_value"),
						 (try_begin),
							 (eq, "$g_presentation_obj_custom_battle_designer_7_locked", 1),
							 (assign, ":first_dif", 0),
							 (assign, ":second_dif", ":dif"),
						 (else_try),
							 (eq, "$g_presentation_obj_custom_battle_designer_6_locked", 1),
							 (assign, ":first_dif", ":dif"),
							 (assign, ":second_dif", 0),
						 (else_try),
							 (store_div, ":first_dif", ":dif", 2),
							 (store_sub, ":second_dif", ":dif", ":first_dif"),
							 (try_begin),
								 (neq, ":first_dif", ":second_dif"),
								 (store_random_in_range, ":random_no", 0, 2),
								 (eq, ":random_no", 0),
								 (val_sub, ":second_dif", 1),
								 (val_add, ":first_dif", 1),
							 (try_end),
						 (try_end),
						 (assign, "$g_presentation_obj_custom_battle_designer_8_last_value", ":value"),
						 (val_sub, "$g_presentation_obj_custom_battle_designer_7_last_value", ":first_dif"),
						 (val_sub, "$g_presentation_obj_custom_battle_designer_6_last_value", ":second_dif"),
						 (try_begin),
							 (lt, "$g_presentation_obj_custom_battle_designer_7_last_value", 0),
							 (val_add, "$g_presentation_obj_custom_battle_designer_6_last_value", "$g_presentation_obj_custom_battle_designer_7_last_value"),
							 (assign, "$g_presentation_obj_custom_battle_designer_7_last_value", 0),
						 (else_try),
							 (lt, "$g_presentation_obj_custom_battle_designer_6_last_value", 0),
							 (val_add, "$g_presentation_obj_custom_battle_designer_7_last_value", "$g_presentation_obj_custom_battle_designer_6_last_value"),
							 (assign, "$g_presentation_obj_custom_battle_designer_6_last_value", 0),
						 (try_end),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_7", "$g_presentation_obj_custom_battle_designer_7_last_value"),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_6", "$g_presentation_obj_custom_battle_designer_6_last_value"),
					 (try_end),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_6_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_12", "str_reg0_percent"),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_7_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_13", "str_reg0_percent"),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_8_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_14", "str_reg0_percent"),
				 (try_end),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_9"),
				 (try_begin),
					 (eq, "$g_presentation_obj_custom_battle_designer_9_locked", 1),
					 (neq, ":value", "$g_presentation_obj_custom_battle_designer_9_last_value"),
					 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_9", "$g_presentation_obj_custom_battle_designer_9_last_value"),
				 (else_try),
					 (try_begin),
						 (lt, ":value", "$g_presentation_obj_custom_battle_designer_9_last_value"),
						 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_9_last_value", ":value"),
						 (try_begin),
							 (eq, "$g_presentation_obj_custom_battle_designer_10_locked", 1),
							 (assign, ":first_dif", 0),
							 (assign, ":second_dif", ":dif"),
						 (else_try),
							 (eq, "$g_presentation_obj_custom_battle_designer_11_locked", 1),
							 (assign, ":first_dif", ":dif"),
							 (assign, ":second_dif", 0),
						 (else_try),
							 (store_div, ":first_dif", ":dif", 2),
							 (store_sub, ":second_dif", ":dif", ":first_dif"),
							 (try_begin),
								 (neq, ":first_dif", ":second_dif"),
								 (store_random_in_range, ":random_no", 0, 2),
								 (eq, ":random_no", 0),
								 (val_sub, ":second_dif", 1),
								 (val_add, ":first_dif", 1),
							 (try_end),
						 (try_end),
						 (assign, "$g_presentation_obj_custom_battle_designer_9_last_value", ":value"),
						 (val_add, "$g_presentation_obj_custom_battle_designer_10_last_value", ":first_dif"),
						 (val_add, "$g_presentation_obj_custom_battle_designer_11_last_value", ":second_dif"),
						 (try_begin),
							 (gt, "$g_presentation_obj_custom_battle_designer_10_last_value", 100),
							 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_10_last_value", 100),
							 (val_add, "$g_presentation_obj_custom_battle_designer_11_last_value", ":dif"),
							 (assign, "$g_presentation_obj_custom_battle_designer_10_last_value", 100),
						 (else_try),
							 (gt, "$g_presentation_obj_custom_battle_designer_11_last_value", 100),
							 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_11_last_value", 100),
							 (val_add, "$g_presentation_obj_custom_battle_designer_10_last_value", ":dif"),
							 (assign, "$g_presentation_obj_custom_battle_designer_11_last_value", 100),
						 (try_end),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_10", "$g_presentation_obj_custom_battle_designer_10_last_value"),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_11", "$g_presentation_obj_custom_battle_designer_11_last_value"),
					 (else_try),
						 (gt, ":value", "$g_presentation_obj_custom_battle_designer_9_last_value"),
						 (store_sub, ":dif", ":value", "$g_presentation_obj_custom_battle_designer_9_last_value"),
						 (try_begin),
							 (eq, "$g_presentation_obj_custom_battle_designer_10_locked", 1),
							 (assign, ":first_dif", 0),
							 (assign, ":second_dif", ":dif"),
						 (else_try),
							 (eq, "$g_presentation_obj_custom_battle_designer_11_locked", 1),
							 (assign, ":first_dif", ":dif"),
							 (assign, ":second_dif", 0),
						 (else_try),
							 (store_div, ":first_dif", ":dif", 2),
							 (store_sub, ":second_dif", ":dif", ":first_dif"),
							 (try_begin),
								 (neq, ":first_dif", ":second_dif"),
								 (store_random_in_range, ":random_no", 0, 2),
								 (eq, ":random_no", 0),
								 (val_sub, ":second_dif", 1),
								 (val_add, ":first_dif", 1),
							 (try_end),
						 (try_end),
						 (assign, "$g_presentation_obj_custom_battle_designer_9_last_value", ":value"),
						 (val_sub, "$g_presentation_obj_custom_battle_designer_10_last_value", ":first_dif"),
						 (val_sub, "$g_presentation_obj_custom_battle_designer_11_last_value", ":second_dif"),
						 (try_begin),
							 (lt, "$g_presentation_obj_custom_battle_designer_10_last_value", 0),
							 (val_add, "$g_presentation_obj_custom_battle_designer_11_last_value", "$g_presentation_obj_custom_battle_designer_10_last_value"),
							 (assign, "$g_presentation_obj_custom_battle_designer_10_last_value", 0),
						 (else_try),
							 (lt, "$g_presentation_obj_custom_battle_designer_11_last_value", 0),
							 (val_add, "$g_presentation_obj_custom_battle_designer_10_last_value", "$g_presentation_obj_custom_battle_designer_11_last_value"),
							 (assign, "$g_presentation_obj_custom_battle_designer_11_last_value", 0),
						 (try_end),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_10", "$g_presentation_obj_custom_battle_designer_10_last_value"),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_11", "$g_presentation_obj_custom_battle_designer_11_last_value"),
					 (try_end),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_9_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_15", "str_reg0_percent"),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_10_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_16", "str_reg0_percent"),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_11_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_17", "str_reg0_percent"),
				 (try_end),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_10"),
				 (try_begin),
					 (eq, "$g_presentation_obj_custom_battle_designer_10_locked", 1),
					 (neq, ":value", "$g_presentation_obj_custom_battle_designer_10_last_value"),
					 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_10", "$g_presentation_obj_custom_battle_designer_10_last_value"),
				 (else_try),
					 (try_begin),
						 (lt, ":value", "$g_presentation_obj_custom_battle_designer_10_last_value"),
						 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_10_last_value", ":value"),
						 (try_begin),
							 (eq, "$g_presentation_obj_custom_battle_designer_9_locked", 1),
							 (assign, ":first_dif", 0),
							 (assign, ":second_dif", ":dif"),
						 (else_try),
							 (eq, "$g_presentation_obj_custom_battle_designer_11_locked", 1),
							 (assign, ":first_dif", ":dif"),
							 (assign, ":second_dif", 0),
						 (else_try),
							 (store_div, ":first_dif", ":dif", 2),
							 (store_sub, ":second_dif", ":dif", ":first_dif"),
							 (try_begin),
								 (neq, ":first_dif", ":second_dif"),
								 (store_random_in_range, ":random_no", 0, 2),
								 (eq, ":random_no", 0),
								 (val_sub, ":second_dif", 1),
								 (val_add, ":first_dif", 1),
							 (try_end),
						 (try_end),
						 (assign, "$g_presentation_obj_custom_battle_designer_10_last_value", ":value"),
						 (val_add, "$g_presentation_obj_custom_battle_designer_9_last_value", ":first_dif"),
						 (val_add, "$g_presentation_obj_custom_battle_designer_11_last_value", ":second_dif"),
						 (try_begin),
							 (gt, "$g_presentation_obj_custom_battle_designer_9_last_value", 100),
							 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_9_last_value", 100),
							 (val_add, "$g_presentation_obj_custom_battle_designer_11_last_value", ":dif"),
							 (assign, "$g_presentation_obj_custom_battle_designer_9_last_value", 100),
						 (else_try),
							 (gt, "$g_presentation_obj_custom_battle_designer_11_last_value", 100),
							 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_11_last_value", 100),
							 (val_add, "$g_presentation_obj_custom_battle_designer_9_last_value", ":dif"),
							 (assign, "$g_presentation_obj_custom_battle_designer_11_last_value", 100),
						 (try_end),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_9", "$g_presentation_obj_custom_battle_designer_9_last_value"),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_11", "$g_presentation_obj_custom_battle_designer_11_last_value"),
					 (else_try),
						 (gt, ":value", "$g_presentation_obj_custom_battle_designer_10_last_value"),
						 (store_sub, ":dif", ":value", "$g_presentation_obj_custom_battle_designer_10_last_value"),
						 (try_begin),
							 (eq, "$g_presentation_obj_custom_battle_designer_9_locked", 1),
							 (assign, ":first_dif", 0),
							 (assign, ":second_dif", ":dif"),
						 (else_try),
							 (eq, "$g_presentation_obj_custom_battle_designer_11_locked", 1),
							 (assign, ":first_dif", ":dif"),
							 (assign, ":second_dif", 0),
						 (else_try),
							 (store_div, ":first_dif", ":dif", 2),
							 (store_sub, ":second_dif", ":dif", ":first_dif"),
							 (try_begin),
								 (neq, ":first_dif", ":second_dif"),
								 (store_random_in_range, ":random_no", 0, 2),
								 (eq, ":random_no", 0),
								 (val_sub, ":second_dif", 1),
								 (val_add, ":first_dif", 1),
							 (try_end),
						 (try_end),
						 (assign, "$g_presentation_obj_custom_battle_designer_10_last_value", ":value"),
						 (val_sub, "$g_presentation_obj_custom_battle_designer_9_last_value", ":first_dif"),
						 (val_sub, "$g_presentation_obj_custom_battle_designer_11_last_value", ":second_dif"),
						 (try_begin),
							 (lt, "$g_presentation_obj_custom_battle_designer_9_last_value", 0),
							 (val_add, "$g_presentation_obj_custom_battle_designer_11_last_value", "$g_presentation_obj_custom_battle_designer_9_last_value"),
							 (assign, "$g_presentation_obj_custom_battle_designer_9_last_value", 0),
						 (else_try),
							 (lt, "$g_presentation_obj_custom_battle_designer_11_last_value", 0),
							 (val_add, "$g_presentation_obj_custom_battle_designer_9_last_value", "$g_presentation_obj_custom_battle_designer_11_last_value"),
							 (assign, "$g_presentation_obj_custom_battle_designer_11_last_value", 0),
						 (try_end),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_9", "$g_presentation_obj_custom_battle_designer_9_last_value"),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_11", "$g_presentation_obj_custom_battle_designer_11_last_value"),
					 (try_end),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_9_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_15", "str_reg0_percent"),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_10_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_16", "str_reg0_percent"),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_11_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_17", "str_reg0_percent"),
				 (try_end),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_11"),
				 (try_begin),
					 (eq, "$g_presentation_obj_custom_battle_designer_11_locked", 1),
					 (neq, ":value", "$g_presentation_obj_custom_battle_designer_11_last_value"),
					 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_11", "$g_presentation_obj_custom_battle_designer_11_last_value"),
				 (else_try),
					 (try_begin),
						 (lt, ":value", "$g_presentation_obj_custom_battle_designer_11_last_value"),
						 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_11_last_value", ":value"),
						 (try_begin),
							 (eq, "$g_presentation_obj_custom_battle_designer_10_locked", 1),
							 (assign, ":first_dif", 0),
							 (assign, ":second_dif", ":dif"),
						 (else_try),
							 (eq, "$g_presentation_obj_custom_battle_designer_9_locked", 1),
							 (assign, ":first_dif", ":dif"),
							 (assign, ":second_dif", 0),
						 (else_try),
							 (store_div, ":first_dif", ":dif", 2),
							 (store_sub, ":second_dif", ":dif", ":first_dif"),
							 (try_begin),
								 (neq, ":first_dif", ":second_dif"),
								 (store_random_in_range, ":random_no", 0, 2),
								 (eq, ":random_no", 0),
								 (val_sub, ":second_dif", 1),
								 (val_add, ":first_dif", 1),
							 (try_end),
						 (try_end),
						 (assign, "$g_presentation_obj_custom_battle_designer_11_last_value", ":value"),
						 (val_add, "$g_presentation_obj_custom_battle_designer_10_last_value", ":first_dif"),
						 (val_add, "$g_presentation_obj_custom_battle_designer_9_last_value", ":second_dif"),
						 (try_begin),
							 (gt, "$g_presentation_obj_custom_battle_designer_10_last_value", 100),
							 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_10_last_value", 100),
							 (val_add, "$g_presentation_obj_custom_battle_designer_9_last_value", ":dif"),
							 (assign, "$g_presentation_obj_custom_battle_designer_10_last_value", 100),
						 (else_try),
							 (gt, "$g_presentation_obj_custom_battle_designer_9_last_value", 100),
							 (store_sub, ":dif", "$g_presentation_obj_custom_battle_designer_9_last_value", 100),
							 (val_add, "$g_presentation_obj_custom_battle_designer_10_last_value", ":dif"),
							 (assign, "$g_presentation_obj_custom_battle_designer_9_last_value", 100),
						 (try_end),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_10", "$g_presentation_obj_custom_battle_designer_10_last_value"),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_9", "$g_presentation_obj_custom_battle_designer_9_last_value"),
					 (else_try),
						 (gt, ":value", "$g_presentation_obj_custom_battle_designer_11_last_value"),
						 (store_sub, ":dif", ":value", "$g_presentation_obj_custom_battle_designer_11_last_value"),
						 (try_begin),
							 (eq, "$g_presentation_obj_custom_battle_designer_10_locked", 1),
							 (assign, ":first_dif", 0),
							 (assign, ":second_dif", ":dif"),
						 (else_try),
							 (eq, "$g_presentation_obj_custom_battle_designer_9_locked", 1),
							 (assign, ":first_dif", ":dif"),
							 (assign, ":second_dif", 0),
						 (else_try),
							 (store_div, ":first_dif", ":dif", 2),
							 (store_sub, ":second_dif", ":dif", ":first_dif"),
							 (try_begin),
								 (neq, ":first_dif", ":second_dif"),
								 (store_random_in_range, ":random_no", 0, 2),
								 (eq, ":random_no", 0),
								 (val_sub, ":second_dif", 1),
								 (val_add, ":first_dif", 1),
							 (try_end),
						 (try_end),
						 (assign, "$g_presentation_obj_custom_battle_designer_11_last_value", ":value"),
						 (val_sub, "$g_presentation_obj_custom_battle_designer_10_last_value", ":first_dif"),
						 (val_sub, "$g_presentation_obj_custom_battle_designer_9_last_value", ":second_dif"),
						 (try_begin),
							 (lt, "$g_presentation_obj_custom_battle_designer_10_last_value", 0),
							 (val_add, "$g_presentation_obj_custom_battle_designer_9_last_value", "$g_presentation_obj_custom_battle_designer_10_last_value"),
							 (assign, "$g_presentation_obj_custom_battle_designer_10_last_value", 0),
						 (else_try),
							 (lt, "$g_presentation_obj_custom_battle_designer_9_last_value", 0),
							 (val_add, "$g_presentation_obj_custom_battle_designer_10_last_value", "$g_presentation_obj_custom_battle_designer_9_last_value"),
							 (assign, "$g_presentation_obj_custom_battle_designer_9_last_value", 0),
						 (try_end),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_10", "$g_presentation_obj_custom_battle_designer_10_last_value"),
						 (overlay_set_val, "$g_presentation_obj_custom_battle_designer_9", "$g_presentation_obj_custom_battle_designer_9_last_value"),
					 (try_end),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_9_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_15", "str_reg0_percent"),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_10_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_16", "str_reg0_percent"),
					 (assign, reg0, "$g_presentation_obj_custom_battle_designer_11_last_value"),
					 (overlay_set_text, "$g_presentation_obj_custom_battle_designer_17", "str_reg0_percent"),
				 (try_end),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_19"),
				 (assign, "$g_is_quick_battle", 1),
				 (assign, ":cur_scene", "$g_quick_battle_map"),
				 (try_begin),
					 (eq, "$g_quick_battle_game_type", 0), #battle
					 (assign, ":cur_mission_template", "mt_quick_battle_battle"),
					 (modify_visitors_at_site, ":cur_scene"),
					 (call_script, "script_spawn_quick_battle_army", 0, "$g_quick_battle_team_1_faction", "$g_presentation_obj_custom_battle_designer_6_last_value", "$g_presentation_obj_custom_battle_designer_7_last_value", "$g_presentation_obj_custom_battle_designer_8_last_value", 0, 1),
					 (call_script, "script_spawn_quick_battle_army", 16, "$g_quick_battle_team_2_faction", "$g_presentation_obj_custom_battle_designer_9_last_value", "$g_presentation_obj_custom_battle_designer_10_last_value", "$g_presentation_obj_custom_battle_designer_11_last_value", 0, 0),
				 (else_try),
					 (eq, "$g_quick_battle_game_type", 1), #siege offense
					 (assign, ":cur_mission_template", "mt_quick_battle_siege"),
					 (modify_visitors_at_site, ":cur_scene"),
					 (call_script, "script_spawn_quick_battle_army", 16, "$g_quick_battle_team_1_faction", "$g_presentation_obj_custom_battle_designer_6_last_value", "$g_presentation_obj_custom_battle_designer_7_last_value", "$g_presentation_obj_custom_battle_designer_8_last_value", 0, 1),
					 (call_script, "script_spawn_quick_battle_army", 0, "$g_quick_battle_team_2_faction", "$g_presentation_obj_custom_battle_designer_9_last_value", "$g_presentation_obj_custom_battle_designer_10_last_value", "$g_presentation_obj_custom_battle_designer_11_last_value", 1, 0),
				 (else_try),
					 #siege defense
					 (assign, ":cur_mission_template", "mt_quick_battle_siege"),
					 (modify_visitors_at_site, ":cur_scene"),
					 (call_script, "script_spawn_quick_battle_army", 0, "$g_quick_battle_team_1_faction", "$g_presentation_obj_custom_battle_designer_6_last_value", "$g_presentation_obj_custom_battle_designer_7_last_value", "$g_presentation_obj_custom_battle_designer_8_last_value", 1, 1),
					 (call_script, "script_spawn_quick_battle_army", 16, "$g_quick_battle_team_2_faction", "$g_presentation_obj_custom_battle_designer_9_last_value", "$g_presentation_obj_custom_battle_designer_10_last_value", "$g_presentation_obj_custom_battle_designer_11_last_value", 0, 0),
				 (try_end),
				 (set_jump_mission,":cur_mission_template"),
				 (jump_to_menu, "mnu_custom_battle_end"),
				 (jump_to_scene, ":cur_scene"),
				 (change_screen_mission),
				 (presentation_set_duration, 0),
			 (else_try),
				 (eq, ":object", "$g_presentation_obj_custom_battle_designer_20"),
				 (presentation_set_duration, 0),
			 (try_end),
			]),
		(ti_on_presentation_mouse_enter_leave,
		 [
			 (store_trigger_param_1, ":object"),
			 (store_trigger_param_2, ":enter_leave"),
			 (this_or_next|eq, ":object", "$g_presentation_obj_custom_battle_designer_6"),
			 (this_or_next|eq, ":object", "$g_presentation_obj_custom_battle_designer_7"),
			 (this_or_next|eq, ":object", "$g_presentation_obj_custom_battle_designer_8"),
			 (this_or_next|eq, ":object", "$g_presentation_obj_custom_battle_designer_9"),
			 (this_or_next|eq, ":object", "$g_presentation_obj_custom_battle_designer_10"),
			 (eq, ":object", "$g_presentation_obj_custom_battle_designer_11"),
			 (try_begin),
				 (eq, ":enter_leave", 1),
				 (try_begin),
					 (eq, ":object", "$g_presentation_obj_custom_battle_last_mouse_over_object"),
					 (assign, "$g_presentation_obj_custom_battle_last_mouse_over_object", -1),
				 (try_end),
			 (else_try),
				 (assign, "$g_presentation_obj_custom_battle_last_mouse_over_object", ":object"),
			 (try_end),
			 ]),
		(ti_on_presentation_run,
		 [
			(try_begin),
				(this_or_next|key_clicked, key_escape),
		(key_clicked, key_xbox_start),
				(presentation_set_duration, 0),
			(else_try),
				(key_clicked, key_right_mouse_button),
				(neq, "$g_presentation_obj_custom_battle_last_mouse_over_object", -1),
				(try_begin),
					(eq, "$g_presentation_obj_custom_battle_last_mouse_over_object", "$g_presentation_obj_custom_battle_designer_6"),
					(try_begin),
						(eq, "$g_presentation_obj_custom_battle_designer_6_locked", 0),
						(assign, "$g_presentation_obj_custom_battle_designer_6_locked", 1),
						(assign, "$g_presentation_obj_custom_battle_designer_7_locked", 0),
						(assign, "$g_presentation_obj_custom_battle_designer_8_locked", 0),
					(else_try),
						(assign, "$g_presentation_obj_custom_battle_designer_6_locked", 0),
					(try_end),
				(else_try),
					(eq, "$g_presentation_obj_custom_battle_last_mouse_over_object", "$g_presentation_obj_custom_battle_designer_7"),
					(try_begin),
						(eq, "$g_presentation_obj_custom_battle_designer_7_locked", 0),
						(assign, "$g_presentation_obj_custom_battle_designer_6_locked", 0),
						(assign, "$g_presentation_obj_custom_battle_designer_7_locked", 1),
						(assign, "$g_presentation_obj_custom_battle_designer_8_locked", 0),
					(else_try),
						(assign, "$g_presentation_obj_custom_battle_designer_7_locked", 0),
					(try_end),
				(else_try),
					(eq, "$g_presentation_obj_custom_battle_last_mouse_over_object", "$g_presentation_obj_custom_battle_designer_8"),
					(try_begin),
						(eq, "$g_presentation_obj_custom_battle_designer_8_locked", 0),
						(assign, "$g_presentation_obj_custom_battle_designer_6_locked", 0),
						(assign, "$g_presentation_obj_custom_battle_designer_7_locked", 0),
						(assign, "$g_presentation_obj_custom_battle_designer_8_locked", 1),
					(else_try),
						(assign, "$g_presentation_obj_custom_battle_designer_8_locked", 0),
					(try_end),
				(else_try),
					(eq, "$g_presentation_obj_custom_battle_last_mouse_over_object", "$g_presentation_obj_custom_battle_designer_9"),
					(try_begin),
						(eq, "$g_presentation_obj_custom_battle_designer_9_locked", 0),
						(assign, "$g_presentation_obj_custom_battle_designer_9_locked", 1),
						(assign, "$g_presentation_obj_custom_battle_designer_10_locked", 0),
						(assign, "$g_presentation_obj_custom_battle_designer_11_locked", 0),
					(else_try),
						(assign, "$g_presentation_obj_custom_battle_designer_9_locked", 0),
					(try_end),
				(else_try),
					(eq, "$g_presentation_obj_custom_battle_last_mouse_over_object", "$g_presentation_obj_custom_battle_designer_10"),
					(try_begin),
						(eq, "$g_presentation_obj_custom_battle_designer_10_locked", 0),
						(assign, "$g_presentation_obj_custom_battle_designer_9_locked", 0),
						(assign, "$g_presentation_obj_custom_battle_designer_10_locked", 1),
						(assign, "$g_presentation_obj_custom_battle_designer_11_locked", 0),
					(else_try),
						(assign, "$g_presentation_obj_custom_battle_designer_10_locked", 0),
					(try_end),
				(else_try),
					(eq, "$g_presentation_obj_custom_battle_last_mouse_over_object", "$g_presentation_obj_custom_battle_designer_11"),
					(try_begin),
						(eq, "$g_presentation_obj_custom_battle_designer_11_locked", 0),
						(assign, "$g_presentation_obj_custom_battle_designer_9_locked", 0),
						(assign, "$g_presentation_obj_custom_battle_designer_10_locked", 0),
						(assign, "$g_presentation_obj_custom_battle_designer_11_locked", 1),
					(else_try),
						(assign, "$g_presentation_obj_custom_battle_designer_11_locked", 0),
					(try_end),
				(try_end),
			(try_end),
			]),
		])
