from header import *
## CC
autoloot_upgrade_management =	(
	"autoloot_upgrade_management", 0, mesh_load_window, [
		(ti_on_presentation_load,
		 [
			(set_fixed_point_multiplier, 1000),
			(presentation_set_duration, 999999),

			# done
			(create_game_button_overlay, "$g_presentation_obj_10", "@Done"),
			(position_set_x, pos1, 900),
			(position_set_y, pos1, 25),
			(overlay_set_position, "$g_presentation_obj_10", pos1),

			## current hero
			# character picture
			(create_mesh_overlay_with_tableau_material, reg0, -1, "tableau_troop_note_mesh", "$temp"),
			(position_set_x, pos1, 500),
			(position_set_y, pos1, 500),
			(overlay_set_size, reg0, pos1),
			(position_set_x, pos1, 200),
			(position_set_y, pos1, 560),
			(overlay_set_position, reg0, pos1),

			(str_store_troop_name, s1, "$temp"),
			(store_character_level, ":troop_level", "$temp"),
			(assign, reg1, ":troop_level"),
			(str_store_string, s1, "@Name: {s1}^Level: {reg1}"),

			(store_troop_health, ":cur_hp", "$temp", 1),
			(call_script, "script_get_troop_max_hp", "$temp"),
			(assign, reg1, ":cur_hp"),
			(assign, reg2, reg0),
			(str_store_string, s1, "@{s1}^HP: {reg1}/{reg2}"),

			(create_text_overlay, reg1, "@{s1}", tf_double_space),
			(position_set_x, pos1, 380),
			(position_set_y, pos1, 560),
			(overlay_set_position, reg1, pos1),

			# title
			(create_text_overlay, reg1, "@Weapon upgrade settings:", tf_center_justify|tf_vertical_align_center),
			(position_set_x, pos1, 445),
			(position_set_y, pos1, 530),
			(overlay_set_position, reg1, pos1),

			# init trp_temp_array_c 
			(assign, ":sub_overlay_id", 0),
			(try_for_range_backwards, ":item_type", 0, itp_type_animal),
				(this_or_next|is_between, ":item_type", itp_type_one_handed_wpn, itp_type_goods),
				(this_or_next|is_between, ":item_type", itp_type_pistol, itp_type_animal),
				(eq, ":item_type", 0),
				(troop_set_slot, "trp_temp_array_c", ":sub_overlay_id", ":item_type"),
				(val_add, ":sub_overlay_id", 1),
			(try_end),
			
			(troop_get_slot,":upgrade_wpn_set_sel", "$temp", slot_upgrade_wpn_set_sel),
			(store_sub, ":upgrade_wpn_set_sel_2", 1, ":upgrade_wpn_set_sel"),
			# settings 1
			(create_text_overlay, reg1, "@Plan <1> ", tf_center_justify|tf_vertical_align_center),
			(position_set_x, pos1, 270),
			(position_set_y, pos1, 500),
			(overlay_set_position, reg1, pos1),
			# set 1: wpn slot button
			(position_set_x, pos1, 270),
			(position_set_y, pos1, 450),
			(create_combo_button_overlay, "$g_presentation_obj_1"),
			(overlay_set_position, "$g_presentation_obj_1", pos1),
			(assign, ":sub_overlay_id", 0),
			(call_script, "script_get_current_item_for_autoloot", ":upgrade_wpn_set_sel", 0),
			(try_for_range_backwards, ":item_type", 0, itp_type_animal),
				(this_or_next|is_between, ":item_type", itp_type_one_handed_wpn, itp_type_goods),
				(this_or_next|is_between, ":item_type", itp_type_pistol, itp_type_animal),
				(eq, ":item_type", 0),
				(store_add, ":out_string", "str_hero_wpn_slot_none", ":item_type"),
				(str_store_string, s0, ":out_string"),
				(overlay_add_item, "$g_presentation_obj_1", s0),
				(try_begin),
					(troop_slot_eq, "$temp", slot_upgrade_wpn_0, ":item_type"),
					(overlay_set_val, "$g_presentation_obj_1", ":sub_overlay_id"),
				(try_end),
				(val_add, ":sub_overlay_id", 1),
			(try_end),
 
			(position_set_y, pos1, 420),
			(create_combo_button_overlay, "$g_presentation_obj_2"),
			(overlay_set_position, "$g_presentation_obj_2", pos1),
			(assign, ":sub_overlay_id", 0),
			(call_script, "script_get_current_item_for_autoloot", ":upgrade_wpn_set_sel", 1),
			(try_for_range_backwards, ":item_type", 0, itp_type_animal),
				(this_or_next|is_between, ":item_type", itp_type_one_handed_wpn, itp_type_goods),
				(this_or_next|is_between, ":item_type", itp_type_pistol, itp_type_animal),
				(eq, ":item_type", 0),
				(store_add, ":out_string", "str_hero_wpn_slot_none", ":item_type"),
				(str_store_string, s0, ":out_string"),
				(overlay_add_item, "$g_presentation_obj_2", s0),
				(try_begin),
					(troop_slot_eq, "$temp", slot_upgrade_wpn_1, ":item_type"),
					(overlay_set_val, "$g_presentation_obj_2", ":sub_overlay_id"),
				(try_end),
				(val_add, ":sub_overlay_id", 1),
			(try_end),
			
			(position_set_y, pos1, 390),
			(create_combo_button_overlay, "$g_presentation_obj_3"),
			(overlay_set_position, "$g_presentation_obj_3", pos1),
			(assign, ":sub_overlay_id", 0),
			(call_script, "script_get_current_item_for_autoloot", ":upgrade_wpn_set_sel", 2),
			(try_for_range_backwards, ":item_type", 0, itp_type_animal),
				(this_or_next|is_between, ":item_type", itp_type_one_handed_wpn, itp_type_goods),
				(this_or_next|is_between, ":item_type", itp_type_pistol, itp_type_animal),
				(eq, ":item_type", 0),
				(store_add, ":out_string", "str_hero_wpn_slot_none", ":item_type"),
				(str_store_string, s0, ":out_string"),
				(overlay_add_item, "$g_presentation_obj_3", s0),
				(try_begin),
					(troop_slot_eq, "$temp", slot_upgrade_wpn_2, ":item_type"),
					(overlay_set_val, "$g_presentation_obj_3", ":sub_overlay_id"),
				(try_end),
				(val_add, ":sub_overlay_id", 1),
			(try_end),
			
			(position_set_y, pos1, 360),
			(create_combo_button_overlay, "$g_presentation_obj_4"),
			(overlay_set_position, "$g_presentation_obj_4", pos1),
			(assign, ":sub_overlay_id", 0),
			(call_script, "script_get_current_item_for_autoloot", ":upgrade_wpn_set_sel", 3),
			(try_for_range_backwards, ":item_type", 0, itp_type_animal),
				(this_or_next|is_between, ":item_type", itp_type_one_handed_wpn, itp_type_goods),
				(this_or_next|is_between, ":item_type", itp_type_pistol, itp_type_animal),
				(eq, ":item_type", 0),
				(store_add, ":out_string", "str_hero_wpn_slot_none", ":item_type"),
				(str_store_string, s0, ":out_string"),
				(overlay_add_item, "$g_presentation_obj_4", s0),
				(try_begin),
					(troop_slot_eq, "$temp", slot_upgrade_wpn_3, ":item_type"),
					(overlay_set_val, "$g_presentation_obj_4", ":sub_overlay_id"),
				(try_end),
				(val_add, ":sub_overlay_id", 1),
			(try_end),
			
			(position_set_x, pos1, 1000),
			(position_set_y, pos1, 800),
			(overlay_set_size, "$g_presentation_obj_1", pos1),
			(overlay_set_size, "$g_presentation_obj_2", pos1),
			(overlay_set_size, "$g_presentation_obj_3", pos1),
			(overlay_set_size, "$g_presentation_obj_4", pos1),
			# set 1: apply to all
			(position_set_x, pos1, 128),
			(position_set_y, pos1, 310),
			(create_image_button_overlay, "$g_presentation_obj_11", "mesh_longer_button", "mesh_longer_button_down"),
			(overlay_set_position, "$g_presentation_obj_11", pos1),
			(position_set_x, pos1, 270),
			(position_set_y, pos1, 325),
			(create_text_overlay, reg1, "@Apply to everyone", tf_center_justify|tf_vertical_align_center),
			(overlay_set_position, reg1, pos1),

			# settings 2
			(create_text_overlay, reg1, "@Plan <2> ", tf_center_justify|tf_vertical_align_center),
			(position_set_x, pos1, 620),
			(position_set_y, pos1, 500),
			(overlay_set_position, reg1, pos1),
			# set 2: wpn slot button
			(position_set_x, pos1, 620),
			(position_set_y, pos1, 450),
			(create_combo_button_overlay, "$g_presentation_obj_5"),
			(overlay_set_position, "$g_presentation_obj_5", pos1),
			(assign, ":sub_overlay_id", 0),
			(call_script, "script_get_current_item_for_autoloot", ":upgrade_wpn_set_sel_2", 0),
			(try_for_range_backwards, ":item_type", 0, itp_type_animal),
				(this_or_next|is_between, ":item_type", itp_type_one_handed_wpn, itp_type_goods),
				(this_or_next|is_between, ":item_type", itp_type_pistol, itp_type_animal),
				(eq, ":item_type", 0),
				(store_add, ":out_string", "str_hero_wpn_slot_none", ":item_type"),
				(str_store_string, s0, ":out_string"),
				(overlay_add_item, "$g_presentation_obj_5", s0),
				(try_begin),
					(troop_slot_eq, "$temp", slot_upgrade_wpn_0_set_2, ":item_type"),
					(overlay_set_val, "$g_presentation_obj_5", ":sub_overlay_id"),
				(try_end),
				(val_add, ":sub_overlay_id", 1),
			(try_end),
			
			(position_set_y, pos1, 420),
			(create_combo_button_overlay, "$g_presentation_obj_6"),
			(overlay_set_position, "$g_presentation_obj_6", pos1),
			(assign, ":sub_overlay_id", 0),
			(call_script, "script_get_current_item_for_autoloot", ":upgrade_wpn_set_sel_2", 1),
			(try_for_range_backwards, ":item_type", 0, itp_type_animal),
				(this_or_next|is_between, ":item_type", itp_type_one_handed_wpn, itp_type_goods),
				(this_or_next|is_between, ":item_type", itp_type_pistol, itp_type_animal),
				(eq, ":item_type", 0),
				(store_add, ":out_string", "str_hero_wpn_slot_none", ":item_type"),
				(str_store_string, s0, ":out_string"),
				(overlay_add_item, "$g_presentation_obj_6", s0),
				(try_begin),
					(troop_slot_eq, "$temp", slot_upgrade_wpn_1_set_2, ":item_type"),
					(overlay_set_val, "$g_presentation_obj_6", ":sub_overlay_id"),
				(try_end),
				(val_add, ":sub_overlay_id", 1),
			(try_end),
			
			(position_set_y, pos1, 390),
			(create_combo_button_overlay, "$g_presentation_obj_7"),
			(overlay_set_position, "$g_presentation_obj_7", pos1),
			(assign, ":sub_overlay_id", 0),
			(call_script, "script_get_current_item_for_autoloot", ":upgrade_wpn_set_sel_2", 2),
			(try_for_range_backwards, ":item_type", 0, itp_type_animal),
				(this_or_next|is_between, ":item_type", itp_type_one_handed_wpn, itp_type_goods),
				(this_or_next|is_between, ":item_type", itp_type_pistol, itp_type_animal),
				(eq, ":item_type", 0),
				(store_add, ":out_string", "str_hero_wpn_slot_none", ":item_type"),
				(str_store_string, s0, ":out_string"),
				(overlay_add_item, "$g_presentation_obj_7", s0),
				(try_begin),
					(troop_slot_eq, "$temp", slot_upgrade_wpn_2_set_2, ":item_type"),
					(overlay_set_val, "$g_presentation_obj_7", ":sub_overlay_id"),
				(try_end),
				(val_add, ":sub_overlay_id", 1),
			(try_end),
			
			(position_set_y, pos1, 360),
			(create_combo_button_overlay, "$g_presentation_obj_8"),
			(overlay_set_position, "$g_presentation_obj_8", pos1),
			(assign, ":sub_overlay_id", 0),
			(call_script, "script_get_current_item_for_autoloot", ":upgrade_wpn_set_sel_2", 3),
			(try_for_range_backwards, ":item_type", 0, itp_type_animal),
				(this_or_next|is_between, ":item_type", itp_type_one_handed_wpn, itp_type_goods),
				(this_or_next|is_between, ":item_type", itp_type_pistol, itp_type_animal),
				(eq, ":item_type", 0),
				(store_add, ":out_string", "str_hero_wpn_slot_none", ":item_type"),
				(str_store_string, s0, ":out_string"),
				(overlay_add_item, "$g_presentation_obj_8", s0),
				(try_begin),
					(troop_slot_eq, "$temp", slot_upgrade_wpn_3_set_2, ":item_type"),
					(overlay_set_val, "$g_presentation_obj_8", ":sub_overlay_id"),
				(try_end),
				(val_add, ":sub_overlay_id", 1),
			(try_end),
			
			(position_set_x, pos1, 1000),
			(position_set_y, pos1, 800),
			(overlay_set_size, "$g_presentation_obj_5", pos1),
			(overlay_set_size, "$g_presentation_obj_6", pos1),
			(overlay_set_size, "$g_presentation_obj_7", pos1),
			(overlay_set_size, "$g_presentation_obj_8", pos1),
			# set 2: apply to all
			(position_set_x, pos1, 478),
			(position_set_y, pos1, 310),
			(create_image_button_overlay, "$g_presentation_obj_12", "mesh_longer_button", "mesh_longer_button_down"),
			(overlay_set_position, "$g_presentation_obj_12", pos1),
			(position_set_x, pos1, 620),
			(position_set_y, pos1, 325),
			(create_text_overlay, reg1, "@Apply to everyone", tf_center_justify|tf_vertical_align_center),
			(overlay_set_position, reg1, pos1),

			# current settings and equipment
			# text
			(position_set_x, pos1, 300),
			(position_set_y, pos1, 265),
			(create_text_overlay, reg1, "@Use plan <1> ", tf_center_justify|tf_vertical_align_center),
			(overlay_set_position, reg1, pos1),
			(position_set_y, pos1, 215),
			(create_text_overlay, reg1, "@Use plan <2> ", tf_center_justify|tf_vertical_align_center),
			(overlay_set_position, reg1, pos1),
			# checkbox
			(position_set_x, pos1, 180),
			(position_set_y, pos1, 258),
			(create_check_box_overlay, "$g_presentation_obj_17", "mesh_checkbox_off", "mesh_checkbox_on"),
			(overlay_set_position, "$g_presentation_obj_17", pos1),
			(position_set_y, pos1, 208),
			(create_check_box_overlay, "$g_presentation_obj_18", "mesh_checkbox_off", "mesh_checkbox_on"),
			(overlay_set_position, "$g_presentation_obj_18", pos1),
			(try_begin),
				(troop_slot_eq, "$temp", slot_upgrade_wpn_set_sel, 0),
				(overlay_set_val, "$g_presentation_obj_17", 1),
				(overlay_set_val, "$g_presentation_obj_18", 0),
			(else_try),
				(overlay_set_val, "$g_presentation_obj_17", 0),
				(overlay_set_val, "$g_presentation_obj_18", 1),
			(try_end),
			# long button
			(position_set_x, pos1, 418),
			(position_set_y, pos1, 225),
			(create_image_button_overlay, "$g_presentation_obj_19", "mesh_longer_button", "mesh_longer_button_down"),
			(overlay_set_position, "$g_presentation_obj_19", pos1),
			(position_set_x, pos1, 560),
			(position_set_y, pos1, 240),
			(create_text_overlay, reg1, "@Apply to everyone", tf_center_justify|tf_vertical_align_center),
			(overlay_set_position, reg1, pos1),

			# upgrade armor and horse
			# text
			(position_set_x, pos1, 300),
			(position_set_y, pos1, 155),
			(create_text_overlay, reg1, "@Upgrade armor ", tf_center_justify|tf_vertical_align_center),
			(overlay_set_position, reg1, pos1),
			(position_set_y, pos1, 105),
			(create_text_overlay, reg1, "@Upgrade horse ", tf_center_justify|tf_vertical_align_center),
			(overlay_set_position, reg1, pos1),
			# checkbox
			(position_set_x, pos1, 180),
			(position_set_y, pos1, 148),
			(create_check_box_overlay, "$g_presentation_obj_13", "mesh_checkbox_off", "mesh_checkbox_on"),
			(overlay_set_position, "$g_presentation_obj_13", pos1),
			(troop_get_slot,":upg_armor", "$temp",slot_upgrade_armor),
			(overlay_set_val, "$g_presentation_obj_13", ":upg_armor"),
			(position_set_y, pos1, 98),
			(create_check_box_overlay, "$g_presentation_obj_14", "mesh_checkbox_off", "mesh_checkbox_on"),
			(overlay_set_position, "$g_presentation_obj_14", pos1),
			(troop_get_slot,":upg_horse", "$temp",slot_upgrade_horse),
			(overlay_set_val, "$g_presentation_obj_14", ":upg_horse"),
			# long button
			(position_set_x, pos1, 418),
			(position_set_y, pos1, 140),
			(create_image_button_overlay, "$g_presentation_obj_15", "mesh_longer_button", "mesh_longer_button_down"),
			(overlay_set_position, "$g_presentation_obj_15", pos1),
			(position_set_y, pos1, 90),
			(create_image_button_overlay, "$g_presentation_obj_16", "mesh_longer_button", "mesh_longer_button_down"),
			(overlay_set_position, "$g_presentation_obj_16", pos1),
			(position_set_x, pos1, 560),
			(position_set_y, pos1, 155),
			(create_text_overlay, reg1, "@Apply to everyone", tf_center_justify|tf_vertical_align_center),
			(overlay_set_position, reg1, pos1),
			(position_set_y, pos1, 105),
			(create_text_overlay, reg1, "@Apply to everyone", tf_center_justify|tf_vertical_align_center),
			(overlay_set_position, reg1, pos1),

			# price_threshold_for_picking
			(position_set_x, pos1, 175),
			(position_set_y, pos1, 45),
			(create_text_overlay, reg1, "@Price threshold of items for picking:", tf_vertical_align_center),
			(overlay_set_position, reg1, pos1),
			
			(create_number_box_overlay, "$g_presentation_obj_9", 0, 1001),
			(position_set_x, pos1, 600),
			(position_set_y, pos1, 31),
			(overlay_set_position, "$g_presentation_obj_9", pos1),
			(overlay_set_val, "$g_presentation_obj_9", "$g_price_threshold_for_picking"),
			
			# lines
			(call_script, "script_prsnt_lines", 640, 2, 125, 290),
			(call_script, "script_prsnt_lines", 640, 2, 125, 185),
			(call_script, "script_prsnt_lines", 640, 2, 125, 75),
			
			# hero list
			(assign, ":pos_x", 900),
			(assign, ":pos_y", 600),
			(assign, ":num_of_heros", 0),
			(party_get_num_companion_stacks, ":num_stacks","p_main_party"),
			(try_for_range, ":i_stack", 1, ":num_stacks"),
				(party_stack_get_troop_id,":stack_troop","p_main_party",":i_stack"),
				(is_between, ":stack_troop", companions_begin, companions_end),
				(str_store_troop_name, s1, ":stack_troop"),
				(position_set_x, pos1, ":pos_x"),
				(position_set_y, pos1, ":pos_y"),
				(val_sub, ":pos_y", 30),
				(create_button_overlay, reg0, "@{s1}", tf_center_justify|tf_vertical_align_center),
				(overlay_set_position, reg0, pos1),

				(assign, ":trp_slot_prsnt_no", ":num_of_heros"),
				(troop_set_slot, "trp_temp_array_a", ":trp_slot_prsnt_no", reg0),
				(troop_set_slot, "trp_temp_array_b", ":trp_slot_prsnt_no", ":stack_troop"),
				(val_add, ":num_of_heros", 1),
			(try_end),
#      ####### mouse fix pos system #######
#      (call_script, "script_mouse_fix_pos_ready"),
#      ####### mouse fix pos system #######
		 ]),

#    (ti_on_presentation_run,
#      [
#      ####### mouse fix pos system #######
#      (call_script, "script_mouse_fix_pos_run"),
#      ####### mouse fix pos system #######
#    ]),

		(ti_on_presentation_event_state_change,
		 [
				(store_trigger_param_1, ":object"),
				(store_trigger_param_2, ":value"),

				(try_begin),
					(eq, ":object", "$g_presentation_obj_1"),
					(troop_get_slot, ":item_type", "trp_temp_array_c", ":value"),
					(troop_set_slot, "$temp", slot_upgrade_wpn_0, ":item_type"),
					(start_presentation, "prsnt_autoloot_upgrade_management"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_2"),
					(troop_get_slot, ":item_type", "trp_temp_array_c", ":value"),
					(troop_set_slot, "$temp", slot_upgrade_wpn_1, ":item_type"),
					(start_presentation, "prsnt_autoloot_upgrade_management"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_3"),
					(troop_get_slot, ":item_type", "trp_temp_array_c", ":value"),
					(troop_set_slot, "$temp", slot_upgrade_wpn_2, ":item_type"),
					(start_presentation, "prsnt_autoloot_upgrade_management"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_4"),
					(troop_get_slot, ":item_type", "trp_temp_array_c", ":value"),
					(troop_set_slot, "$temp", slot_upgrade_wpn_3, ":item_type"),
					(start_presentation, "prsnt_autoloot_upgrade_management"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_5"),
					(troop_get_slot, ":item_type", "trp_temp_array_c", ":value"),
					(troop_set_slot, "$temp", slot_upgrade_wpn_0_set_2, ":item_type"),
					(start_presentation, "prsnt_autoloot_upgrade_management"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_6"),
					(troop_get_slot, ":item_type", "trp_temp_array_c", ":value"),
					(troop_set_slot, "$temp", slot_upgrade_wpn_1_set_2, ":item_type"),
					(start_presentation, "prsnt_autoloot_upgrade_management"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_7"),
					(troop_get_slot, ":item_type", "trp_temp_array_c", ":value"),
					(troop_set_slot, "$temp", slot_upgrade_wpn_2_set_2, ":item_type"),
					(start_presentation, "prsnt_autoloot_upgrade_management"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_8"),
					(troop_get_slot, ":item_type", "trp_temp_array_c", ":value"),
					(troop_set_slot, "$temp", slot_upgrade_wpn_3_set_2, ":item_type"),
					(start_presentation, "prsnt_autoloot_upgrade_management"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_9"),
					(assign, "$g_price_threshold_for_picking", ":value"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_10"),
					(presentation_set_duration, 0),
				(else_try),
					(eq, ":object", "$g_presentation_obj_11"),
					(call_script, "script_copy_upgrade_to_all_heroes", "$temp", wpn_setting_1),
				(else_try),
					(eq, ":object", "$g_presentation_obj_12"),
					(call_script, "script_copy_upgrade_to_all_heroes", "$temp", wpn_setting_2),
				(else_try),
					(eq, ":object", "$g_presentation_obj_13"),
					(troop_set_slot, "$temp", slot_upgrade_armor, ":value"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_14"),
					(troop_set_slot, "$temp", slot_upgrade_horse, ":value"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_15"),
					(call_script, "script_copy_upgrade_to_all_heroes", "$temp", armor_setting),
				(else_try),
					(eq, ":object", "$g_presentation_obj_16"),
					(call_script, "script_copy_upgrade_to_all_heroes", "$temp", horse_setting),
				(else_try),
					(eq, ":object", "$g_presentation_obj_17"),
					(overlay_set_val, "$g_presentation_obj_17", 1),
					(overlay_set_val, "$g_presentation_obj_18", 0),
					(try_begin),
						(troop_slot_eq, "$temp", slot_upgrade_wpn_set_sel, 1),
						(troop_set_slot, "$temp", slot_upgrade_wpn_set_sel, 0),
						(call_script, "script_exchange_equipments_between_two_sets", "$temp"),
						(start_presentation, "prsnt_autoloot_upgrade_management"),
					(try_end),
				(else_try),
					(eq, ":object", "$g_presentation_obj_18"),
					(overlay_set_val, "$g_presentation_obj_18", 1),
					(overlay_set_val, "$g_presentation_obj_17", 0),
					(try_begin),
						(troop_slot_eq, "$temp", slot_upgrade_wpn_set_sel, 0),
						(troop_set_slot, "$temp", slot_upgrade_wpn_set_sel, 1),
						(call_script, "script_exchange_equipments_between_two_sets", "$temp"),
						(start_presentation, "prsnt_autoloot_upgrade_management"),
					(try_end),
				(else_try),
					(eq, ":object", "$g_presentation_obj_19"),
					(troop_get_slot, ":upgrade_wpn_set_sel", "$temp", slot_upgrade_wpn_set_sel),
					(try_for_range, ":hero", companions_begin, companions_end),
						(troop_get_slot, ":upgrade_wpn_set_sel_2", ":hero", slot_upgrade_wpn_set_sel),
						(neq, ":upgrade_wpn_set_sel_2", ":upgrade_wpn_set_sel"),
						(troop_set_slot, ":hero", slot_upgrade_wpn_set_sel, ":upgrade_wpn_set_sel"),
						(call_script, "script_exchange_equipments_between_two_sets", ":hero"),
					(try_end),
				(try_end),

				(assign, ":num_of_heros", 0),
				(party_get_num_companion_stacks, ":num_stacks","p_main_party"),
				(try_for_range, ":i_stack", 0, ":num_stacks"),
					(party_stack_get_troop_id,":stack_troop","p_main_party",":i_stack"),
					(is_between, ":stack_troop", companions_begin, companions_end),
					(assign, ":trp_slot_prsnt_no", ":num_of_heros"),
					(val_add, ":num_of_heros", 1),
					(troop_slot_eq, "trp_temp_array_a", ":trp_slot_prsnt_no", ":object"),
					(troop_get_slot, ":cur_troop", "trp_temp_array_b", ":trp_slot_prsnt_no"),
					(assign, "$temp", ":cur_troop"),
					(start_presentation, "prsnt_autoloot_upgrade_management"),
				(try_end),
		]),
	])

auto_sell_options = (
	"auto_sell_options", 0, mesh_load_window, [
		(ti_on_presentation_load,
			[
				(presentation_set_duration, 999999),
				(set_fixed_point_multiplier, 1000),

				## do auto-sell automaticly when leaving
				(create_text_overlay, reg0, "@Sell items automaticly when leaving:", tf_vertical_align_center),
				(position_set_x, pos1, 170),
				(position_set_y, pos1, 660),
				(overlay_set_position, reg0, pos1),

				(create_check_box_overlay, "$g_presentation_obj_1", "mesh_checkbox_off", "mesh_checkbox_on"),
				(position_set_x, pos1, 150),
				(position_set_y, pos1, 652),
				(overlay_set_position, "$g_presentation_obj_1", pos1),
				(overlay_set_val, "$g_presentation_obj_1", "$g_sell_items_when_leaving"),

				## price_limit
				(create_text_overlay, reg0, "@Price limit for auto-sell:", tf_vertical_align_center),
				(position_set_x, pos1, 150),
				(position_set_y, pos1, 610),
				(overlay_set_position, reg0, pos1),

				(create_number_box_overlay, "$g_presentation_obj_2", 10, 10000),
				(position_set_x, pos1, 600),
				(position_set_y, pos1, 596),
				(overlay_set_val, "$g_presentation_obj_2", "$g_auto_sell_price_limit"),
				(overlay_set_position, "$g_presentation_obj_2", pos1),

				# done
				(create_game_button_overlay, "$g_presentation_obj_3", "@Done"),
				(position_set_x, pos1, 900),
				(position_set_y, pos1, 25),
				(overlay_set_position, "$g_presentation_obj_3", pos1),

				## Item types
				(create_text_overlay, reg0, "@Item types for auto-sell:", tf_vertical_align_center),
				(position_set_x, pos1, 150),
				(position_set_y, pos1, 578),
				(overlay_set_position, reg0, pos1),

				# select all
				(create_image_button_overlay, "$g_presentation_obj_5", "mesh_drop_button_child", "mesh_drop_button_child_down"),
				(position_set_x, pos1, 160),
				(position_set_y, pos1, 528),
				(overlay_set_position, "$g_presentation_obj_5", pos1),
				(create_text_overlay, reg1, "@Select all", tf_center_justify|tf_vertical_align_center),
				(position_set_x, pos1, 265),
				(position_set_y, pos1, 538),
				(overlay_set_position, reg1, pos1),

				# select invert
				(create_image_button_overlay, "$g_presentation_obj_6", "mesh_drop_button_child", "mesh_drop_button_child_down"),
				(position_set_x, pos1, 385),
				(position_set_y, pos1, 528),
				(overlay_set_position, "$g_presentation_obj_6", pos1),
				(create_text_overlay, reg1, "@Select invert", tf_center_justify|tf_vertical_align_center),
				(position_set_x, pos1, 490),
				(position_set_y, pos1, 538),
				(overlay_set_position, reg1, pos1),

				(assign, ":pos_x", 160),
				(assign, ":pos_y", 500),
				(try_for_range, ":cur_type", 0, 20),
					(store_add, ":cur_item_type", itp_type_horse, ":cur_type"),
					(neq, ":cur_item_type", itp_type_goods),
					(neq, ":cur_item_type", itp_type_animal),
					(neq, ":cur_item_type", itp_type_book),
					# button
					(position_set_x, pos1, ":pos_x"),
					(position_set_y, pos1, ":pos_y"),
					(create_mesh_overlay, reg1, "mesh_drop_button_child"),
					(overlay_set_position, reg1, pos1),
					# text
					(store_add, ":text_pos_x", ":pos_x", 120),
					(store_add, ":text_pos_y", ":pos_y", 10),
					(position_set_x, pos1, ":text_pos_x"),
					(position_set_y, pos1, ":text_pos_y"),
					(store_add, ":out_string", "str_hero_wpn_slot_horse", ":cur_type"),
					(str_store_string, s1, ":out_string"),
					(create_text_overlay, reg1, "@{s1}", tf_center_justify|tf_vertical_align_center),
					(overlay_set_position, reg1, pos1),
					# checkbox
					(store_add, ":checkbox_pos_x", ":pos_x", 0),
					(store_add, ":checkbox_pos_y", ":pos_y", 4),
					(position_set_x, pos1, ":checkbox_pos_x"),
					(position_set_y, pos1, ":checkbox_pos_y"),
					(create_check_box_overlay, reg1, "mesh_checkbox_off", "mesh_checkbox_on"),
					(overlay_set_position, reg1, pos1),
					(store_add, ":item_type", itp_type_horse, ":cur_type"),
					(item_get_slot, ":for_sell", ":item_type", slot_item_type_not_for_sell),
					(store_sub, ":for_sell", 1, ":for_sell"),
					(overlay_set_val, reg1, ":for_sell"),
					(troop_set_slot, "trp_temp_array_b", ":cur_type", reg1),
					# focous
					(val_add, ":pos_x", 225),
					(try_begin),
						(eq, ":pos_x", 835),
						(assign, ":pos_x", 160),
						(val_sub, ":pos_y", 28),
					(try_end),
				(try_end),

				####### mouse fix pos system #######
				#(call_script, "script_mouse_fix_pos_ready"),
				####### mouse fix pos system #######
			]),

			#(ti_on_presentation_run,
				#[
				####### mouse fix pos system #######
				#(call_script, "script_mouse_fix_pos_run"),
				####### mouse fix pos system #######
			#]),

		(ti_on_presentation_event_state_change,
			[
				(store_trigger_param_1, ":object"),
				(store_trigger_param_2, ":value"),

				(try_begin),
					(eq, ":object", "$g_presentation_obj_1"),
					(assign, "$g_sell_items_when_leaving", ":value"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_2"),
					(assign, "$g_auto_sell_price_limit", ":value"),
				(else_try),
					(eq, ":object", "$g_presentation_obj_3"),
					(presentation_set_duration, 0),
				(else_try),
					## select all
					(eq, ":object", "$g_presentation_obj_5"),
					(try_for_range, ":cur_type", 0, 20),
						(store_add, ":cur_item_type", itp_type_horse, ":cur_type"),
						(neq, ":cur_item_type", itp_type_goods),
						(neq, ":cur_item_type", itp_type_animal),
						(neq, ":cur_item_type", itp_type_book),
						(item_set_slot, ":cur_item_type", slot_item_type_not_for_sell, 0),
						(troop_get_slot, ":dest_checkbox", "trp_temp_array_b", ":cur_type"),
						(overlay_set_val, ":dest_checkbox", 1),
					(try_end),
				(else_try),
					## select invert
					(eq, ":object", "$g_presentation_obj_6"),
					(try_for_range, ":cur_type", 0, 20),
						(store_add, ":cur_item_type", itp_type_horse, ":cur_type"),
						(neq, ":cur_item_type", itp_type_goods),
						(neq, ":cur_item_type", itp_type_animal),
						(neq, ":cur_item_type", itp_type_book),
						(item_get_slot, ":for_sell", ":cur_item_type", slot_item_type_not_for_sell),
						(val_add, ":for_sell", 1),
						(val_mod, ":for_sell", 2),
						(item_set_slot, ":cur_item_type", slot_item_type_not_for_sell, ":for_sell"),
						(troop_get_slot, ":dest_checkbox", "trp_temp_array_b", ":cur_type"),
						(store_sub, ":dest_val", 1, ":for_sell"),
						(overlay_set_val, ":dest_checkbox", ":dest_val"),
					(try_end),
				(try_end),

				## checkboxes
				(try_for_range, ":slot_item_type_checkbox", 0, 20),
					(troop_slot_eq, "trp_temp_array_b", ":slot_item_type_checkbox", ":object"),
					(store_add, ":item_type", itp_type_horse, ":slot_item_type_checkbox"),
					(store_sub, ":for_sell", 1, ":value"),
					(item_set_slot, ":item_type", slot_item_type_not_for_sell, ":for_sell"),
				(try_end),
			]),
		])