from header import *

game_multiplayer_admin_panel = (
	"game_multiplayer_admin_panel", prsntf_manual_end_only, 0, [
		(ti_on_presentation_load,
		 [(set_fixed_point_multiplier, 1000),

			(try_begin),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_1"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_1"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_2"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_2"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_3"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_3"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_4"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_4"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_5"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_5"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_6"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_6"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_7"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_7"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_8"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_8"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_9"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_9"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_10"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_10"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_11"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_11"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_12"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_12"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_13"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_13"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_14"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_14"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_15"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_15"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_16"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_16"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_17"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_17"),
			(else_try),
				(eq, "$g_multiplayer_selected_map", "scn_multi_scene_18"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_18"),
			(else_try),
			# (eq, "$g_multiplayer_selected_map", "scn_multi_scene_19"),
				# (assign, ":map_image", "mesh_mp_ui_host_maps_19"),
			# (else_try),
				# (eq, "$g_multiplayer_selected_map", "scn_multi_scene_20"),
				# (assign, ":map_image", "mesh_mp_ui_host_maps_20"),
			# (else_try),
				(this_or_next|eq, "$g_multiplayer_selected_map", "scn_random_multi_plain_medium"),
				(eq, "$g_multiplayer_selected_map", "scn_random_multi_plain_large"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_randomp"),
			(else_try),
				(this_or_next|eq, "$g_multiplayer_selected_map", "scn_random_multi_steppe_medium"),
				(eq, "$g_multiplayer_selected_map", "scn_random_multi_steppe_large"),
				(assign, ":map_image", "mesh_mp_ui_host_maps_randoms"),
			(else_try),
				(assign, ":map_image", "mesh_mp_ui_host_maps_randomp"),
			(try_end),

			(create_mesh_overlay, reg0, ":map_image"),
			(position_set_x, pos1, -1),
			(position_set_y, pos1, 550),
			(overlay_set_position, reg0, pos1),
			(position_set_x, pos1, 1002),
			(position_set_y, pos1, 1002),
			(overlay_set_size, reg0, pos1),

			(create_mesh_overlay, reg0, "mesh_mp_ui_host_main"),
			(position_set_x, pos1, -1),
			(position_set_y, pos1, -1),
			(overlay_set_position, reg0, pos1),
			(position_set_x, pos1, 1002),
			(position_set_y, pos1, 1002),
			(overlay_set_size, reg0, pos1),

			(assign, ":cur_y", 1240),
			(assign, ":cur_y_adder", 40),

			(try_begin),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_team_deathmatch),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_battle),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_destroy),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_capture_the_flag),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_headquarters),
				(eq, "$g_multiplayer_game_type", multiplayer_game_type_siege),
				(val_add, ":cur_y", ":cur_y_adder"), #two more options for these mods (friendly fire options)
				(val_add, ":cur_y", ":cur_y_adder"),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_capture_the_flag),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_battle),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_destroy),
				(eq, "$g_multiplayer_game_type", multiplayer_game_type_siege),
				(val_add, ":cur_y", ":cur_y_adder"), #one more option for these mods
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_battle),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_destroy),
				(eq, "$g_multiplayer_game_type", multiplayer_game_type_siege),
				(val_add, ":cur_y", ":cur_y_adder"), #one more option for these mods
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_battle),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_destroy),
				(eq, "$g_multiplayer_game_type", multiplayer_game_type_siege),
				(val_add, ":cur_y", ":cur_y_adder"), #one more option for these mods
			(try_end),

			(str_clear, s0),
			(create_text_overlay, "$g_presentation_obj_admin_panel_container", s0, tf_scrollable),
			(position_set_x, pos1, 59),
			(position_set_y, pos1, 50),
			(overlay_set_position, "$g_presentation_obj_admin_panel_container", pos1),
			(position_set_x, pos1, 640),
			(position_set_y, pos1, 520),
			(overlay_set_area_size, "$g_presentation_obj_admin_panel_container", pos1),
			(set_container_overlay, "$g_presentation_obj_admin_panel_container"),


			(create_text_overlay, reg0, "str_add_to_official_game_servers_list", 0),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_check_box_overlay, "$g_presentation_obj_admin_panel_14", "mesh_checkbox_off", "mesh_checkbox_on"),
			(position_set_x, pos1, 7),
			(store_add, ":special_cur_y", ":cur_y", 7),
			(position_set_y, pos1, ":special_cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_14", pos1),
			(server_get_add_to_game_servers_list, ":add_to_servers_list"),
			(overlay_set_val, "$g_presentation_obj_admin_panel_14", ":add_to_servers_list"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_enable_valve_anti_cheat", 0),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_check_box_overlay, "$g_presentation_obj_admin_panel_41", "mesh_checkbox_off", "mesh_checkbox_on"),
			(position_set_x, pos1, 7),
			(store_add, ":special_cur_y", ":cur_y", 7),
			(position_set_y, pos1, ":special_cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_41", pos1),
			(server_get_anti_cheat, ":server_anti_cheat"),
			(overlay_set_val, "$g_presentation_obj_admin_panel_41", ":server_anti_cheat"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_server_name", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(str_store_server_name, s0),
			(try_begin),
				(eq, "$g_multiplayer_renaming_server_allowed", 1),
				(create_simple_text_box_overlay, "$g_presentation_obj_admin_panel_20"),
				(position_set_x, pos1, 390),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, "$g_presentation_obj_admin_panel_20", pos1),
				(overlay_set_text, "$g_presentation_obj_admin_panel_20", s0),
			(else_try),
				(assign, "$g_presentation_obj_admin_panel_20", -1),
				(create_text_overlay, reg0, s0, 0),
				(position_set_x, pos1, 385),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, reg0, pos1),
			(try_end),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_game_password", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_simple_text_box_overlay, "$g_presentation_obj_admin_panel_9"),
			(position_set_x, pos1, 390),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_9", pos1),
			(str_store_server_password, s0),
			(overlay_set_text, "$g_presentation_obj_admin_panel_9", s0),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_welcome_message", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_simple_text_box_overlay, "$g_presentation_obj_admin_panel_32"),
			(position_set_x, pos1, 390),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_32", pos1),
			(str_store_welcome_message, s0),
			(overlay_set_text, "$g_presentation_obj_admin_panel_32", s0),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_map", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(call_script, "script_multiplayer_fill_map_game_types", "$g_multiplayer_game_type"),
			(assign, ":num_maps", reg0),
			(assign, ":selected_index", 0),

			(try_begin),
				(gt, ":num_maps", 12),
				(create_combo_label_overlay, "$g_presentation_obj_admin_panel_1"),
			(else_try),
			(create_combo_button_overlay, "$g_presentation_obj_admin_panel_1"),
			(try_end),
			(position_set_x, pos1, 800),
			(position_set_y, pos1, 800),
			(overlay_set_size, "$g_presentation_obj_admin_panel_1", pos1),
			(try_begin),
				(gt, ":num_maps", 14),
				(position_set_x, pos1, 465),
			(else_try),
			(position_set_x, pos1, 490),
			(try_end),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_1", pos1),
			(troop_get_slot, ":first_map", "trp_multiplayer_data", multi_data_maps_for_game_type_begin),
			(assign, ":selected_map_available", 0),
			(try_for_range, ":i_map", 0, ":num_maps"),
				(store_add, ":map_slot", ":i_map", multi_data_maps_for_game_type_begin),
				(troop_get_slot, ":map_no", "trp_multiplayer_data", ":map_slot"),
				(store_sub, ":string_index", ":map_no", multiplayer_scenes_begin),
				(val_add, ":string_index", multiplayer_scene_names_begin),
				(str_store_string, s0, ":string_index"),
				(overlay_add_item, "$g_presentation_obj_admin_panel_1", s0),
				(try_begin),
					(eq, ":map_no", "$g_multiplayer_selected_map"),
					(assign, ":selected_index", ":i_map"),
					(assign, ":selected_map_available", 1),
				(try_end),
			(try_end),
			(overlay_set_val, "$g_presentation_obj_admin_panel_1", ":selected_index"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_game_type", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(try_begin),
				(eq, "$g_multiplayer_changing_game_type_allowed", 1),
				(create_combo_button_overlay, "$g_presentation_obj_admin_panel_10"),
				(position_set_x, pos1, 800),
				(position_set_y, pos1, 800),
				(overlay_set_size, "$g_presentation_obj_admin_panel_10", pos1),
				(position_set_x, pos1, 490),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, "$g_presentation_obj_admin_panel_10", pos1),
				(try_for_range, ":i_game_type", 0, multiplayer_num_game_types),
					(store_add, ":string_index", ":i_game_type", multiplayer_game_type_names_begin),
					(str_store_string, s0, ":string_index"),
					(overlay_add_item, "$g_presentation_obj_admin_panel_10", s0),
				(try_end),
				(overlay_set_val, "$g_presentation_obj_admin_panel_10", "$g_multiplayer_game_type"),
			(else_try),
				(assign, "$g_presentation_obj_admin_panel_10", -1),
				(store_add, ":string_index", "$g_multiplayer_game_type", multiplayer_game_type_names_begin),
				(str_store_string, s0, ":string_index"),
				(create_text_overlay, reg0, s0, 0),
				(position_set_x, pos1, 385),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, reg0, pos1),
			(try_end),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(assign, reg1, 1),
			(create_text_overlay, reg0, "str_team_reg1_faction", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_combo_button_overlay, "$g_presentation_obj_admin_panel_11"),
			(position_set_x, pos1, 800),
			(position_set_y, pos1, 800),
			(overlay_set_size, "$g_presentation_obj_admin_panel_11", pos1),
			(position_set_x, pos1, 490),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_11", pos1),
			(call_script, "script_multiplayer_fill_available_factions_combo_button", "$g_presentation_obj_admin_panel_11", "$g_multiplayer_next_team_1_faction", "$g_multiplayer_next_team_2_faction"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(assign, reg1, 2),
			(create_text_overlay, reg0, "str_team_reg1_faction", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_combo_button_overlay, "$g_presentation_obj_admin_panel_12"),
			(position_set_x, pos1, 800),
			(position_set_y, pos1, 800),
			(overlay_set_size, "$g_presentation_obj_admin_panel_12", pos1),
			(position_set_x, pos1, 490),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_12", pos1),
			(call_script, "script_multiplayer_fill_available_factions_combo_button", "$g_presentation_obj_admin_panel_12", "$g_multiplayer_next_team_2_faction", "$g_multiplayer_next_team_1_faction"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(assign, reg1, 1),
			(create_text_overlay, reg0, "str_max_number_of_players", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_number_box_overlay, "$g_presentation_obj_admin_panel_21", 2, 201),
			(position_set_x, pos1, 390),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_21", pos1),
			(server_get_max_num_players, ":max_players"),
			(overlay_set_val, "$g_presentation_obj_admin_panel_21", ":max_players"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(assign, reg1, 1),
			(create_text_overlay, reg0, "str_number_of_bots_in_team_reg1", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_number_box_overlay, "$g_presentation_obj_admin_panel_3", 0, "$g_multiplayer_max_num_bots"),
			(position_set_x, pos1, 390),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_3", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_3", "$g_multiplayer_num_bots_team_1"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(assign, reg1, 2),
			(create_text_overlay, reg0, "str_number_of_bots_in_team_reg1", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_number_box_overlay, "$g_presentation_obj_admin_panel_4", 0, "$g_multiplayer_max_num_bots"),
			(position_set_x, pos1, 390),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_4", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_4", "$g_multiplayer_num_bots_team_2"),

			(try_begin),
				(neq, "$g_multiplayer_game_type", multiplayer_game_type_deathmatch),
				(neq, "$g_multiplayer_game_type", multiplayer_game_type_duel),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_allow_friendly_fire", 0),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_check_box_overlay, "$g_presentation_obj_admin_panel_5", "mesh_checkbox_off", "mesh_checkbox_on"),
			(position_set_x, pos1, 7),
			(store_add, ":special_cur_y", ":cur_y", 7),
			(position_set_y, pos1, ":special_cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_5", pos1),
			(server_get_friendly_fire, ":server_friendly_fire"),
			(overlay_set_val, "$g_presentation_obj_admin_panel_5", ":server_friendly_fire"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_allow_melee_friendly_fire", 0),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_check_box_overlay, "$g_presentation_obj_admin_panel_36", "mesh_checkbox_off", "mesh_checkbox_on"),
			(position_set_x, pos1, 7),
			(store_add, ":special_cur_y", ":cur_y", 7),
			(position_set_y, pos1, ":special_cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_36", pos1),
			(server_get_melee_friendly_fire, ":melee_friendly_fire"),
			(overlay_set_val, "$g_presentation_obj_admin_panel_36", ":melee_friendly_fire"),
			(try_end),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_friendly_fire_damage_self_ratio", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_number_box_overlay, "$g_presentation_obj_admin_panel_37", 0, 101),
			(position_set_x, pos1, 390),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_37", pos1),
			(server_get_friendly_fire_damage_self_ratio, ":friendly_fire_damage_self_ratio"),
			(overlay_set_val, "$g_presentation_obj_admin_panel_37", ":friendly_fire_damage_self_ratio"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_friendly_fire_damage_friend_ratio", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_number_box_overlay, "$g_presentation_obj_admin_panel_38", 0, 101),
			(position_set_x, pos1, 390),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_38", pos1),
			(server_get_friendly_fire_damage_friend_ratio, ":friendly_fire_damage_friend_ratio"),
			(overlay_set_val, "$g_presentation_obj_admin_panel_38", ":friendly_fire_damage_friend_ratio"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_spectator_camera", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_combo_button_overlay, "$g_presentation_obj_admin_panel_19"),
			(position_set_x, pos1, 800),
			(position_set_y, pos1, 800),
			(overlay_set_size, "$g_presentation_obj_admin_panel_19", pos1),
			(position_set_x, pos1, 490),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_19", pos1),
			(overlay_add_item, "$g_presentation_obj_admin_panel_19", "str_free"),
			(overlay_add_item, "$g_presentation_obj_admin_panel_19", "str_stick_to_any_player"),
			(overlay_add_item, "$g_presentation_obj_admin_panel_19", "str_stick_to_team_members"),
			(overlay_add_item, "$g_presentation_obj_admin_panel_19", "str_stick_to_team_members_view"),
			(server_get_ghost_mode, ":server_ghost_mode"),
			(overlay_set_val, "$g_presentation_obj_admin_panel_19", ":server_ghost_mode"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_control_block_direction", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_combo_button_overlay, "$g_presentation_obj_admin_panel_15"),
			(position_set_x, pos1, 800),
			(position_set_y, pos1, 800),
			(overlay_set_size, "$g_presentation_obj_admin_panel_15", pos1),
			(position_set_x, pos1, 490),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_15", pos1),
			(overlay_add_item, "$g_presentation_obj_admin_panel_15", "str_automatic"),
			(overlay_add_item, "$g_presentation_obj_admin_panel_15", "str_by_mouse_movement"),
			(server_get_control_block_dir, ":server_control_block_dir"),
			(overlay_set_val, "$g_presentation_obj_admin_panel_15", ":server_control_block_dir"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_combat_speed", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_combo_button_overlay, "$g_presentation_obj_admin_panel_26"),
			(position_set_x, pos1, 800),
			(position_set_y, pos1, 800),
			(overlay_set_size, "$g_presentation_obj_admin_panel_26", pos1),
			(position_set_x, pos1, 490),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_26", pos1),
			(overlay_add_item, "$g_presentation_obj_admin_panel_26", "str_combat_speed_0"),
			(overlay_add_item, "$g_presentation_obj_admin_panel_26", "str_combat_speed_1"),
			(overlay_add_item, "$g_presentation_obj_admin_panel_26", "str_combat_speed_2"),
			(overlay_add_item, "$g_presentation_obj_admin_panel_26", "str_combat_speed_3"),
			(overlay_add_item, "$g_presentation_obj_admin_panel_26", "str_combat_speed_4"),
			(server_get_combat_speed, ":server_combat_speed"),
			(overlay_set_val, "$g_presentation_obj_admin_panel_26", ":server_combat_speed"),

			(try_begin),
				(neq, "$g_multiplayer_game_type", multiplayer_game_type_headquarters),

				(val_sub, ":cur_y", ":cur_y_adder"),

				(create_text_overlay, reg0, "str_map_time_limit", 0),
				(position_set_x, pos1, 0),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, reg0, pos1),

				(create_number_box_overlay, "$g_presentation_obj_admin_panel_7", 5, 121),
				(position_set_x, pos1, 390),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, "$g_presentation_obj_admin_panel_7", pos1),
				(overlay_set_val, "$g_presentation_obj_admin_panel_7", "$g_multiplayer_game_max_minutes"),
			(else_try),
				(assign, "$g_presentation_obj_admin_panel_7", -1),
			(try_end),

			(try_begin),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_battle),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_destroy),
				(eq, "$g_multiplayer_game_type", multiplayer_game_type_siege),

				(val_sub, ":cur_y", ":cur_y_adder"),

				(create_text_overlay, reg0, "str_round_time_limit", 0),
				(position_set_x, pos1, 0),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, reg0, pos1),

				(create_number_box_overlay, "$g_presentation_obj_admin_panel_16", multiplayer_round_max_seconds_min, multiplayer_round_max_seconds_max),
				(position_set_x, pos1, 390),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, "$g_presentation_obj_admin_panel_16", pos1),
				(overlay_set_val, "$g_presentation_obj_admin_panel_16", "$g_multiplayer_round_max_seconds"),

			(else_try),
				(assign, "$g_presentation_obj_admin_panel_16", -1),
			(try_end),

			(try_begin),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_battle),
				(eq, "$g_multiplayer_game_type", multiplayer_game_type_destroy),

				(val_sub, ":cur_y", ":cur_y_adder"),

				(create_text_overlay, reg0, "str_players_take_control_of_a_bot_after_death", 0),
				(position_set_x, pos1, 30),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, reg0, pos1),

				(create_check_box_overlay, "$g_presentation_obj_admin_panel_25", "mesh_checkbox_off", "mesh_checkbox_on"),
				(position_set_x, pos1, 7),
				(store_add, ":special_cur_y", ":cur_y", 7),
				(position_set_y, pos1, ":special_cur_y"),
				(overlay_set_position, "$g_presentation_obj_admin_panel_25", pos1),
				(overlay_set_val, "$g_presentation_obj_admin_panel_25", "$g_multiplayer_player_respawn_as_bot"),
			(else_try),
				(assign, "$g_presentation_obj_admin_panel_25", -1),
			(try_end),

			(try_begin),
				(eq, "$g_multiplayer_game_type", multiplayer_game_type_siege),

				(val_sub, ":cur_y", ":cur_y_adder"),

				(create_text_overlay, reg0, "str_defender_spawn_count_limit", 0),
				(position_set_x, pos1, 0),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, reg0, pos1),

				(create_combo_button_overlay, "$g_presentation_obj_admin_panel_27"),
				(position_set_x, pos1, 800),
				(position_set_y, pos1, 800),
				(overlay_set_size, "$g_presentation_obj_admin_panel_27", pos1),
				(position_set_x, pos1, 490),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, "$g_presentation_obj_admin_panel_27", pos1),
				(assign, reg0, 5),
				(overlay_add_item, "$g_presentation_obj_admin_panel_27", "str_reg0"),
				(assign, reg0, 4),
				(overlay_add_item, "$g_presentation_obj_admin_panel_27", "str_reg0"),
				(assign, reg0, 3),
				(overlay_add_item, "$g_presentation_obj_admin_panel_27", "str_reg0"),
				(assign, reg0, 2),
				(overlay_add_item, "$g_presentation_obj_admin_panel_27", "str_reg0"),
				(assign, reg0, 1),
				(overlay_add_item, "$g_presentation_obj_admin_panel_27", "str_reg0"),
				(overlay_add_item, "$g_presentation_obj_admin_panel_27", "str_unlimited"),

				(store_sub, ":value_to_set", 5, "$g_multiplayer_number_of_respawn_count"),
				(overlay_set_val, "$g_presentation_obj_admin_panel_27", ":value_to_set"),
				#(val_sub, ":cur_y", ":cur_y_adder"),
			(else_try),
				(assign, "$g_presentation_obj_admin_panel_27", -1),
			(try_end),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_team_points_limit", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_number_box_overlay, "$g_presentation_obj_admin_panel_8", 3, 1001),
			(position_set_x, pos1, 390),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_8", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_8", "$g_multiplayer_game_max_points"),

			(try_begin),
				(eq, "$g_multiplayer_game_type", multiplayer_game_type_headquarters),

				(val_sub, ":cur_y", ":cur_y_adder"),

				(create_text_overlay, reg0, "str_point_gained_from_flags", 0),
				(position_set_x, pos1, 0),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, reg0, pos1),

				(create_number_box_overlay, "$g_presentation_obj_admin_panel_17", 25, 401),
				(position_set_x, pos1, 390),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, "$g_presentation_obj_admin_panel_17", pos1),
				(overlay_set_val, "$g_presentation_obj_admin_panel_17", "$g_multiplayer_point_gained_from_flags"),
			(else_try),
				(assign, "$g_presentation_obj_admin_panel_17", -1),
			(try_end),

			(try_begin),
				(eq, "$g_multiplayer_game_type", multiplayer_game_type_capture_the_flag),

				(val_sub, ":cur_y", ":cur_y_adder"),

				(create_text_overlay, reg0, "str_point_gained_from_capturing_flag", 0),
				(position_set_x, pos1, 0),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, reg0, pos1),

				(create_number_box_overlay, "$g_presentation_obj_admin_panel_18", 0, 11),
				(position_set_x, pos1, 390),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, "$g_presentation_obj_admin_panel_18", pos1),
				(overlay_set_val, "$g_presentation_obj_admin_panel_18", "$g_multiplayer_point_gained_from_capturing_flag"),
			(else_try),
				(assign, "$g_presentation_obj_admin_panel_18", -1),
			(try_end),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_respawn_period", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_number_box_overlay, "$g_presentation_obj_admin_panel_6", multiplayer_respawn_period_min, multiplayer_respawn_period_max),
			(position_set_x, pos1, 390),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_6", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_6", "$g_multiplayer_respawn_period"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_initial_gold_multiplier", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_number_box_overlay, "$g_presentation_obj_admin_panel_33", 0, 1001),
			(position_set_x, pos1, 390),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_33", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_33", "$g_multiplayer_initial_gold_multiplier"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_battle_earnings_multiplier", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_number_box_overlay, "$g_presentation_obj_admin_panel_34", 0, 1001),
			(position_set_x, pos1, 390),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_34", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_34", "$g_multiplayer_battle_earnings_multiplier"),

			(try_begin),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_battle),
				(this_or_next|eq, "$g_multiplayer_game_type", multiplayer_game_type_destroy),
				(eq, "$g_multiplayer_game_type", multiplayer_game_type_siege),

				(val_sub, ":cur_y", ":cur_y_adder"),

				(create_text_overlay, reg0, "str_round_earnings_multiplier", 0),
				(position_set_x, pos1, 0),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, reg0, pos1),

				(create_number_box_overlay, "$g_presentation_obj_admin_panel_35", 0, 1001),
				(position_set_x, pos1, 390),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, "$g_presentation_obj_admin_panel_35", pos1),
				(overlay_set_val, "$g_presentation_obj_admin_panel_35", "$g_multiplayer_round_earnings_multiplier"),
			(else_try),
				(assign, "$g_presentation_obj_admin_panel_35", -1),
			(try_end),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_make_kick_voteable", 0),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_check_box_overlay, "$g_presentation_obj_admin_panel_28", "mesh_checkbox_off", "mesh_checkbox_on"),
			(position_set_x, pos1, 7),
			(store_add, ":special_cur_y", ":cur_y", 7),
			(position_set_y, pos1, ":special_cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_28", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_28", "$g_multiplayer_kick_voteable"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_make_ban_voteable", 0),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_check_box_overlay, "$g_presentation_obj_admin_panel_29", "mesh_checkbox_off", "mesh_checkbox_on"),
			(position_set_x, pos1, 7),
			(store_add, ":special_cur_y", ":cur_y", 7),
			(position_set_y, pos1, ":special_cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_29", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_29", "$g_multiplayer_ban_voteable"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_make_maps_voteable", 0),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_check_box_overlay, "$g_presentation_obj_admin_panel_24", "mesh_checkbox_off", "mesh_checkbox_on"),
			(position_set_x, pos1, 7),
			(store_add, ":special_cur_y", ":cur_y", 7),
			(position_set_y, pos1, ":special_cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_24", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_24", "$g_multiplayer_maps_voteable"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_make_factions_voteable", 0),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_check_box_overlay, "$g_presentation_obj_admin_panel_23", "mesh_checkbox_off", "mesh_checkbox_on"),
			(position_set_x, pos1, 7),
			(store_add, ":special_cur_y", ":cur_y", 7),
			(position_set_y, pos1, ":special_cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_23", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_23", "$g_multiplayer_factions_voteable"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_bots_upper_limit_for_votes", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(assign, ":upper_limit", 51),
			(val_min, ":upper_limit", "$g_multiplayer_max_num_bots"),
			(create_number_box_overlay, "$g_presentation_obj_admin_panel_22", 0, ":upper_limit"),
			(position_set_x, pos1, 390),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_22", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_22", "$g_multiplayer_num_bots_voteable"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_valid_vote_ratio", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_number_box_overlay, "$g_presentation_obj_admin_panel_30", 50, 101),
			(position_set_x, pos1, 390),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_30", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_30", "$g_multiplayer_valid_vote_ratio"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_auto_team_balance_limit", 0),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_combo_button_overlay, "$g_presentation_obj_admin_panel_31"),
			(position_set_x, pos1, 800),
			(position_set_y, pos1, 800),
			(overlay_set_size, "$g_presentation_obj_admin_panel_31", pos1),
			(position_set_x, pos1, 490),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_31", pos1),
			(overlay_add_item, "$g_presentation_obj_admin_panel_31", "str_unlimited"),
			(assign, reg0, 6),
			(overlay_add_item, "$g_presentation_obj_admin_panel_31", "str_reg0"),
			(assign, reg0, 5),
			(overlay_add_item, "$g_presentation_obj_admin_panel_31", "str_reg0"),
			(assign, reg0, 4),
			(overlay_add_item, "$g_presentation_obj_admin_panel_31", "str_reg0"),
			(assign, reg0, 3),
			(overlay_add_item, "$g_presentation_obj_admin_panel_31", "str_reg0"),
			(assign, reg0, 2),
			(overlay_add_item, "$g_presentation_obj_admin_panel_31", "str_reg0"),
			(try_begin),
				(ge, "$g_multiplayer_auto_team_balance_limit", 1000),
				(overlay_set_val, "$g_presentation_obj_admin_panel_31", 0),
			(else_try),
				(store_sub, ":set_value", 7, "$g_multiplayer_auto_team_balance_limit"),
				(overlay_set_val, "$g_presentation_obj_admin_panel_31", ":set_value"),
			(try_end),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_allow_player_banners", 0),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_check_box_overlay, "$g_presentation_obj_admin_panel_39", "mesh_checkbox_off", "mesh_checkbox_on"),
			(position_set_x, pos1, 7),
			(store_add, ":special_cur_y", ":cur_y", 7),
			(position_set_y, pos1, ":special_cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_39", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_39", "$g_multiplayer_allow_player_banners"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_disallow_ranged_weapons", 0),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_check_box_overlay, "$g_presentation_obj_admin_panel_42", "mesh_checkbox_off", "mesh_checkbox_on"),
			(position_set_x, pos1, 7),
			(store_add, ":special_cur_y", ":cur_y", 7),
			(position_set_y, pos1, ":special_cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_42", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_42", "$g_multiplayer_disallow_ranged_weapons"),

			(val_sub, ":cur_y", ":cur_y_adder"),

			(create_text_overlay, reg0, "str_force_default_armor", 0),
			(position_set_x, pos1, 30),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),

			(create_check_box_overlay, "$g_presentation_obj_admin_panel_40", "mesh_checkbox_off", "mesh_checkbox_on"),
			(position_set_x, pos1, 7),
			(store_add, ":special_cur_y", ":cur_y", 7),
			(position_set_y, pos1, ":special_cur_y"),
			(overlay_set_position, "$g_presentation_obj_admin_panel_40", pos1),
			(overlay_set_val, "$g_presentation_obj_admin_panel_40", "$g_multiplayer_force_default_armor"),

			(set_container_overlay, -1),

			(create_button_overlay, "$g_presentation_obj_admin_panel_13", "str_back", tf_center_justify),
			(position_set_x, pos1, 825),
			(position_set_y, pos1, 50),
			(overlay_set_position, "$g_presentation_obj_admin_panel_13", pos1),
			(position_set_x, pos1, 1500),
			(position_set_y, pos1, 1500),
			(overlay_set_size, "$g_presentation_obj_admin_panel_13", pos1),

			(create_button_overlay, "$g_presentation_obj_admin_panel_2", "str_start_map", tf_center_justify),
			(position_set_x, pos1, 825),
			(position_set_y, pos1, 90),
			(overlay_set_position, "$g_presentation_obj_admin_panel_2", pos1),
			(position_set_x, pos1, 1500),
			(position_set_y, pos1, 1500),
			(overlay_set_size, "$g_presentation_obj_admin_panel_2", pos1),

			(presentation_set_duration, 999999),

			(try_begin),
				(eq, ":selected_map_available", 0),
				(assign, "$g_multiplayer_selected_map", ":first_map"),
				(presentation_set_duration, 0),
				(start_presentation, "prsnt_game_multiplayer_admin_panel"),
			(try_end),
			]),

		(ti_on_presentation_event_state_change,
		 [(store_trigger_param_1, ":object"),
			(store_trigger_param_2, ":value"),
			(try_begin),
				(eq, ":object", "$g_presentation_obj_admin_panel_1"),
				(store_add, ":slot_no", ":value", multi_data_maps_for_game_type_begin),
				(troop_get_slot, "$g_multiplayer_selected_map", "trp_multiplayer_data", ":slot_no"),
				(presentation_set_duration, 0),
				(start_presentation, "prsnt_game_multiplayer_admin_panel"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_2"),
				(multiplayer_send_2_int_to_server, multiplayer_event_admin_start_map, "$g_multiplayer_selected_map", "$g_multiplayer_game_type"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_3"),
				(multiplayer_send_2_int_to_server, multiplayer_event_admin_set_num_bots_in_team, 1, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_4"),
				(multiplayer_send_2_int_to_server, multiplayer_event_admin_set_num_bots_in_team, 2, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_5"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_friendly_fire, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_6"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_respawn_period, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_7"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_game_max_minutes, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_8"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_game_max_points, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_9"),
				(multiplayer_send_string_to_server, multiplayer_event_admin_set_game_password, s0),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_10"),
				(assign, "$g_multiplayer_game_type", ":value"),
				(presentation_set_duration, 0),
				(start_presentation, "prsnt_game_multiplayer_admin_panel"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_11"),
				(store_add, "$g_multiplayer_next_team_1_faction", ":value", npc_kingdoms_begin),
##        (try_begin),
##          (ge, "$g_multiplayer_next_team_1_faction", "$g_multiplayer_next_team_2_faction"),
##          (val_add, "$g_multiplayer_next_team_1_faction", 1),
##        (try_end),
				(multiplayer_send_2_int_to_server, multiplayer_event_admin_set_team_faction, 1, "$g_multiplayer_next_team_1_faction"),
				(presentation_set_duration, 0),
				(start_presentation, "prsnt_game_multiplayer_admin_panel"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_12"),
				(store_add, "$g_multiplayer_next_team_2_faction", ":value", npc_kingdoms_begin),
##        (try_begin),
##          (ge, "$g_multiplayer_next_team_2_faction", "$g_multiplayer_next_team_1_faction"),
##          (val_add, "$g_multiplayer_next_team_2_faction", 1),
##        (try_end),
				(multiplayer_send_2_int_to_server, multiplayer_event_admin_set_team_faction, 2, "$g_multiplayer_next_team_2_faction"),
				(presentation_set_duration, 0),
				(start_presentation, "prsnt_game_multiplayer_admin_panel"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_13"),
				(presentation_set_duration, 0),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_14"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_add_to_servers_list, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_15"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_control_block_dir, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_16"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_round_max_seconds, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_17"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_point_gained_from_flags, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_18"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_point_gained_from_capturing_flag, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_19"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_ghost_mode, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_20"),
				(multiplayer_send_string_to_server, multiplayer_event_admin_set_server_name, s0),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_21"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_max_num_players, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_22"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_num_bots_voteable, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_23"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_factions_voteable, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_24"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_maps_voteable, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_25"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_player_respawn_as_bot, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_26"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_combat_speed, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_27"),
				(store_sub, ":value_to_send", 5, ":value"), #opposite index of displayed list
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_respawn_count, ":value_to_send"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_28"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_kick_voteable, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_29"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_ban_voteable, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_30"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_valid_vote_ratio, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_31"),
				(try_begin),
					(eq, ":value", 0),
					(multiplayer_send_int_to_server, multiplayer_event_admin_set_auto_team_balance_limit, 1000),
				(else_try),
					(store_sub, ":value_to_send", 7, ":value"),
					(multiplayer_send_int_to_server, multiplayer_event_admin_set_auto_team_balance_limit, ":value_to_send"),
				(try_end),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_32"),
				(server_set_welcome_message, s0),
				(multiplayer_send_string_to_server, multiplayer_event_admin_set_welcome_message, s0),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_33"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_initial_gold_multiplier, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_34"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_battle_earnings_multiplier, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_35"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_round_earnings_multiplier, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_36"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_melee_friendly_fire, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_37"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_friendly_fire_damage_self_ratio, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_38"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_friendly_fire_damage_friend_ratio, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_39"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_allow_player_banners, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_40"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_force_default_armor, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_41"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_anti_cheat, ":value"),
			(else_try),
				(eq, ":object", "$g_presentation_obj_admin_panel_42"),
				(multiplayer_send_int_to_server, multiplayer_event_admin_set_disallow_ranged_weapons, ":value"),
			(try_end),
			]),
		(ti_on_presentation_run,
		 [
			(try_begin),
				(this_or_next|key_clicked, key_escape),
		(key_clicked, key_xbox_start),
				(presentation_set_duration, 0),
			(try_end),
			]),
		])
