from header import *

multiplayer_welcome_message = (
"multiplayer_welcome_message", prsntf_manual_end_only, 0, [
		(ti_on_presentation_load,
		 [(set_fixed_point_multiplier, 1000),
			(str_store_welcome_message, s0),
			(try_begin),
				(neg|str_is_empty, s0),
				(eq, "$g_multiplayer_welcome_message_shown", 0),
				(create_mesh_overlay, reg0, "mesh_mp_ui_welcome_panel"),
				(position_set_x, pos1, 200),
				(position_set_y, pos1, 400),
				(overlay_set_position, reg0, pos1),
				(create_text_overlay, reg0, s0, tf_scrollable),
				(overlay_set_color, reg0, 0xFFFFFF),
				(position_set_x, pos1, 230),
				(position_set_y, pos1, 425),
				(overlay_set_position, reg0, pos1),
				(position_set_x, pos1, 540),
				(position_set_y, pos1, 150),
				(overlay_set_area_size, reg0, pos1),

				(presentation_set_duration, 999999),
			(else_try),
				(eq, "$g_multiplayer_show_server_rules", 1),
				(create_mesh_overlay, reg0, "mesh_mp_ui_welcome_panel"),
				(position_set_x, pos1, 200),
				(position_set_y, pos1, 400),
				(overlay_set_position, reg0, pos1),
				(try_begin),
					(neg|str_is_empty, s0),
					(str_clear, s3),
					(str_store_string, s2, s0),
					(str_store_string, s2, "str_s2_s3"),
					(str_store_string, s2, "str_s2_s3"),
				(else_try),
					(str_clear, s2),
				(try_end),
				(str_store_string, s3, "@Game Rules:^"),
				(str_store_string, s2, "str_s2_s3"),
				(assign, ":end_cond", 1000),
				(call_script, "script_game_multiplayer_get_game_type_mission_template", "$g_multiplayer_game_type"),
				(assign, ":cur_mt", reg0),

				(str_store_server_name, s0),
				(str_store_string, s3, "str_server_name_s0"),
				(str_store_string, s2, "str_s2_s3"),

				(try_begin),
					(eq, "$g_multiplayer_game_type", multiplayer_game_type_deathmatch),
					(str_store_string, s0, "str_multi_game_type_1"),
				(else_try),
					(eq, "$g_multiplayer_game_type", multiplayer_game_type_team_deathmatch),
					(str_store_string, s0, "str_multi_game_type_2"),
				(else_try),
					(eq, "$g_multiplayer_game_type", multiplayer_game_type_battle),
					(str_store_string, s0, "str_multi_game_type_3"),
				(else_try),
					(eq, "$g_multiplayer_game_type", multiplayer_game_type_destroy),
					(str_store_string, s0, "str_multi_game_type_4"),
				(else_try),
					(eq, "$g_multiplayer_game_type", multiplayer_game_type_capture_the_flag),
					(str_store_string, s0, "str_multi_game_type_5"),
				(else_try),
					(eq, "$g_multiplayer_game_type", multiplayer_game_type_headquarters),
					(str_store_string, s0, "str_multi_game_type_6"),
				(else_try),
					(eq, "$g_multiplayer_game_type", multiplayer_game_type_siege),
					(str_store_string, s0, "str_multi_game_type_7"),
				(else_try),
					(eq, "$g_multiplayer_game_type", multiplayer_game_type_duel),
					(str_store_string, s0, "str_multi_game_type_8"),
				(try_end),
				(str_store_string, s3, "str_game_type_s0"),
				(str_store_string, s2, "str_s2_s3"),

				(store_current_scene, ":cur_scene"),
				(val_sub, ":cur_scene", "scn_multi_scene_1"),
				(val_add, ":cur_scene", "str_multi_scene_1"),
				(str_store_string, s0, ":cur_scene"),
				(str_store_string, s3, "str_map_name_s0"),
				(str_store_string, s2, "str_s2_s3"),

				(store_mission_timer_a, ":mission_timer"),
				(val_add, ":mission_timer", "$server_mission_timer_while_player_joined"),
				(assign, reg0, ":mission_timer"),
				(store_mul, "$g_multiplayer_game_max_seconds", "$g_multiplayer_game_max_minutes", 60),
				(store_sub, ":remaining_seconds", "$g_multiplayer_game_max_seconds", ":mission_timer"),
				(store_div, reg0, ":remaining_seconds", 60),
				(store_mod, reg1, ":remaining_seconds", 60),
				(try_begin),
					(ge, reg0, 10),
					(ge, reg1, 10),
					(str_clear, s0),
					(str_clear, s1),
				(else_try),
					(ge, reg0, 10),
					(str_clear, s0),
					(str_store_string, s1, "@0"),
				(else_try),
					(ge, reg1, 10),
					(str_store_string, s0, "@0"),
					(str_clear, s1),
				(else_try),
					(str_store_string, s0, "@0"),
					(str_store_string, s1, "@0"),
				(try_end),
				(str_store_string, s3, "str_remaining_time_s0reg0_s1reg1"),

				(str_store_string, s2, "str_s2_s3"),

				(try_for_range, ":cur_option", 0, ":end_cond"),
					(assign, reg0, -12345), #magic number
					(call_script, "script_game_get_multiplayer_server_option_for_mission_template", ":cur_mt", ":cur_option"),
					(try_begin),
						(eq, reg0, -12345),
						(assign, ":end_cond", 0),
					(else_try),
						(call_script, "script_game_multiplayer_server_option_for_mission_template_to_string", ":cur_mt", ":cur_option", reg0),
						(str_store_string, s3, s0),
						(str_store_string, s2, "str_s2_s3"),
					(try_end),
				(try_end),
				(create_text_overlay, reg0, s2, tf_scrollable),
				(overlay_set_color, reg0, 0xFFFFFF),
				(position_set_x, pos1, 230),
				(position_set_y, pos1, 425),
				(overlay_set_position, reg0, pos1),
				(position_set_x, pos1, 540),
				(position_set_y, pos1, 150),
				(overlay_set_area_size, reg0, pos1),

				(presentation_set_duration, 999999),
			(try_end),
			]),

		(ti_on_presentation_run,
		 [
			 (str_store_welcome_message, s0),
			 (try_begin),
				 (neq, "$g_multiplayer_show_server_rules", 1),
				 (this_or_next|str_is_empty, s0),
				 (eq, "$g_multiplayer_welcome_message_shown", 1),
				 (presentation_set_duration, 0),
				 (neg|is_presentation_active, "prsnt_multiplayer_escape_menu"),
				 (neg|is_presentation_active, "prsnt_multiplayer_team_select"),
				 (start_presentation, "prsnt_multiplayer_team_select"),
			 (else_try),
				 (store_mission_timer_a, ":mission_timer"),
				 (gt, ":mission_timer", 1),
				 (this_or_next|key_clicked, key_escape),
				 (this_or_next|key_clicked, key_space),
				 (this_or_next|key_clicked, key_enter),
				 (this_or_next|key_clicked, key_left_mouse_button),
				 (this_or_next|key_clicked, key_right_mouse_button),
				 (this_or_next|key_clicked, key_xbox_ltrigger),
				 (key_clicked, key_xbox_rtrigger),
				 (assign, "$g_multiplayer_welcome_message_shown", 1),
				 (presentation_set_duration, 0),
				 (neg|is_presentation_active, "prsnt_multiplayer_escape_menu"),
				 (neg|is_presentation_active, "prsnt_multiplayer_team_select"),
				 (try_begin),
					 (eq, "$g_multiplayer_show_server_rules", 1),
					 (assign, "$g_multiplayer_show_server_rules", 0),
					 (start_presentation, "prsnt_multiplayer_escape_menu"),
				 (else_try),
					 (start_presentation, "prsnt_multiplayer_team_select"),
				 (try_end),
			 (try_end),
			]),
		])


multiplayer_team_select =	(
	"multiplayer_team_select", prsntf_manual_end_only, 0, [
		(ti_on_presentation_load,
		 [(set_fixed_point_multiplier, 1000),

			(create_mesh_overlay, reg0, "mesh_mp_ingame_menu"),
			(position_set_x, pos1, 250),
			(position_set_y, pos1, 80),
			(overlay_set_position, reg0, pos1),
			(position_set_x, pos1, 1000),
			(position_set_y, pos1, 1000),
			(overlay_set_size, reg0, pos1),

			(str_clear, s0),
			(create_text_overlay, "$g_presentation_obj_team_select_container", s0, tf_scrollable_style_2),
			(position_set_x, pos1, 285),
			(position_set_y, pos1, 125),
			(overlay_set_position, "$g_presentation_obj_team_select_container", pos1),
			(position_set_x, pos1, 405),
			(position_set_y, pos1, 500),
			(overlay_set_area_size, "$g_presentation_obj_team_select_container", pos1),
			(set_container_overlay, "$g_presentation_obj_team_select_container"),

			(assign, ":cur_y", 450),

			(create_text_overlay, reg0, "str_choose_a_faction", 0),
			(overlay_set_color, reg0, 0xFFFFFF),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),
			(val_sub, ":cur_y", escape_menu_item_height),
			(position_set_y, pos1, ":cur_y"),
			(position_set_x, pos1, 100),

			(multiplayer_get_my_player, ":my_player_no"),
			(team_get_faction, ":faction_no", 0),
			(str_store_faction_name, s0, ":faction_no"),
			(create_button_overlay, "$g_presentation_obj_team_select_1", s0, 0),
			(try_begin),
				(call_script, "script_cf_multiplayer_team_is_available", ":my_player_no", 0),
				(overlay_set_color, "$g_presentation_obj_team_select_1", 0xFFFFFF),
				(overlay_set_hilight_color, "$g_presentation_obj_team_select_1", 0x55FF50),
				(assign, "$g_multiplayer_team_select_1_available", 1),
			(else_try),
				(overlay_set_color, "$g_presentation_obj_team_select_1", 0x888888),
				(overlay_set_hilight_color, "$g_presentation_obj_team_select_1", 0x888888),
				(assign, "$g_multiplayer_team_select_1_available", 0),
			(try_end),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, "$g_presentation_obj_team_select_1", pos1),
			(val_sub, ":cur_y", escape_menu_item_height),
			(position_set_y, pos1, ":cur_y"),

			(team_get_faction, ":faction_no", 1),
			(str_store_faction_name, s0, ":faction_no"),
			(create_button_overlay, "$g_presentation_obj_team_select_2", s0, 0),
			(try_begin),
				(call_script, "script_cf_multiplayer_team_is_available", ":my_player_no", 1),
				(overlay_set_color, "$g_presentation_obj_team_select_2", 0xFFFFFF),
				(overlay_set_hilight_color, "$g_presentation_obj_team_select_2", 0x55FF50),
				(assign, "$g_multiplayer_team_select_2_available", 1),
			(else_try),
				(overlay_set_color, "$g_presentation_obj_team_select_2", 0x888888),
				(overlay_set_hilight_color, "$g_presentation_obj_team_select_2", 0x888888),
				(assign, "$g_multiplayer_team_select_2_available", 0),
			(try_end),
			(overlay_set_position, "$g_presentation_obj_team_select_2", pos1),
			(val_sub, ":cur_y", escape_menu_item_height),
			(position_set_y, pos1, ":cur_y"),

			(create_button_overlay, "$g_presentation_obj_team_select_3", "str_spectator", 0),
			(overlay_set_color, "$g_presentation_obj_team_select_3", 0xFFFFFF),
			(overlay_set_position, "$g_presentation_obj_team_select_3", pos1),
			(val_sub, ":cur_y", escape_menu_item_height),
			(position_set_y, pos1, ":cur_y"),

			(presentation_set_duration, 999999),
			]),

		(ti_on_presentation_event_state_change,
		 [(store_trigger_param_1, ":object"),
			(multiplayer_get_my_player, ":my_player_no"),
			(try_begin),
				(eq, "$g_waiting_for_confirmation_to_terminate", 0),
				(try_begin),
					(eq, ":object", "$g_presentation_obj_team_select_1"),
					(try_begin),
						(call_script, "script_cf_multiplayer_team_is_available", ":my_player_no", 0),
						(try_begin),
							(player_get_team_no, ":my_team", ":my_player_no"),
							(neq, ":my_team", 0),
							(assign, "$g_confirmation_result", 0),
							(assign, "$g_waiting_for_confirmation_to_terminate", 1),
							(player_get_troop_id, "$g_confirmation_troop_backup", ":my_player_no"),
							(player_get_team_no, "$g_confirmation_team_backup", ":my_player_no"),
							(player_set_troop_id, ":my_player_no", -1),
							(multiplayer_send_int_to_server, multiplayer_event_change_team_no, 0),
							(player_set_team_no, ":my_player_no", 0),
						(else_try),
							(presentation_set_duration, 0),
							(start_presentation, "prsnt_multiplayer_troop_select"),
						(try_end),
					(try_end),
				(else_try),
					(eq, ":object", "$g_presentation_obj_team_select_2"),
					(try_begin),
						(call_script, "script_cf_multiplayer_team_is_available", ":my_player_no", 1),
						(try_begin),
							(player_get_team_no, ":my_team", ":my_player_no"),
							(neq, ":my_team", 1),
							(assign, "$g_confirmation_result", 0),
							(assign, "$g_waiting_for_confirmation_to_terminate", 1),
							(player_get_troop_id, "$g_confirmation_troop_backup", ":my_player_no"),
							(player_get_team_no, "$g_confirmation_team_backup", ":my_player_no"),
							(player_set_troop_id, ":my_player_no", -1),
							(multiplayer_send_int_to_server, multiplayer_event_change_team_no, 1),
							(player_set_team_no, ":my_player_no", 1),
						(else_try),
							(presentation_set_duration, 0),
							(start_presentation, "prsnt_multiplayer_troop_select"),
						(try_end),
					(try_end),
				(else_try),
					(eq, ":object", "$g_presentation_obj_team_select_3"),
					(player_set_troop_id, ":my_player_no", -1),
					(multiplayer_send_int_to_server, multiplayer_event_change_team_no, multi_team_spectator),
					(player_set_team_no, ":my_player_no", multi_team_spectator),
					(presentation_set_duration, 0),
				(try_end),
			(try_end),
			]),

		(ti_on_presentation_run,
		 [
			(multiplayer_get_my_player, ":my_player_no"),
			(try_begin),
		(this_or_next|key_clicked, key_escape),
		(key_clicked, key_xbox_start),
				(eq, "$g_waiting_for_confirmation_to_terminate", 0),
				(multiplayer_get_my_team, ":my_team"),
				(try_begin),
					(eq, ":my_team", multi_team_unassigned),
					(player_set_troop_id, ":my_player_no", -1),
					(multiplayer_send_int_to_server, multiplayer_event_change_team_no, multi_team_spectator),
					(player_set_team_no, ":my_player_no", multi_team_spectator),
				(try_end),
				(presentation_set_duration, 0),
			(else_try),
				(eq, "$g_waiting_for_confirmation_to_terminate", 1),
				(eq, "$g_confirmation_result", 1),
				(assign, "$g_waiting_for_confirmation_to_terminate", 0),
				(assign, "$g_confirmation_result", 0),
				(presentation_set_duration, 0),
				(start_presentation, "prsnt_multiplayer_troop_select"),
			(else_try),
				(eq, "$g_waiting_for_confirmation_to_terminate", 1),
				(eq, "$g_confirmation_result", -1),
				#return troop and team back to the old state
				(player_set_troop_id, ":my_player_no", "$g_confirmation_troop_backup"),
				(player_set_team_no, ":my_player_no", "$g_confirmation_team_backup"),
				(assign, "$g_waiting_for_confirmation_to_terminate", 0),
				(assign, "$g_confirmation_result", 0),
				(presentation_set_duration, 0),
				(start_presentation, "prsnt_multiplayer_team_select"),
			(else_try),
				(assign, ":do_refresh", 0),
				(try_begin),
					(call_script, "script_cf_multiplayer_team_is_available", ":my_player_no", 0),
					(try_begin),
						(eq, "$g_multiplayer_team_select_1_available", 0),
						(assign, ":do_refresh", 1),
					(try_end),
				(else_try),
					#not available
					(try_begin),
						(eq, "$g_multiplayer_team_select_1_available", 1),
						(assign, ":do_refresh", 1),
					(try_end),
				(try_end),
				(try_begin),
					(call_script, "script_cf_multiplayer_team_is_available", ":my_player_no", 1),
					(try_begin),
						(eq, "$g_multiplayer_team_select_2_available", 0),
						(assign, ":do_refresh", 1),
					(try_end),
				(else_try),
					#not available
					(try_begin),
						(eq, "$g_multiplayer_team_select_2_available", 1),
						(assign, ":do_refresh", 1),
					(try_end),
				(try_end),
				(eq, ":do_refresh", 1),
				(presentation_set_duration, 0),
				(start_presentation, "prsnt_multiplayer_team_select"),
			(try_end),
			]),
		])


multiplayer_troop_select =	(
	"multiplayer_troop_select", prsntf_manual_end_only, 0, [
		(ti_on_presentation_load,
		 [(set_fixed_point_multiplier, 1000),

			(create_mesh_overlay, reg0, "mesh_mp_ingame_menu"),
			(position_set_x, pos1, 250),
			(position_set_y, pos1, 80),
			(overlay_set_position, reg0, pos1),
			(position_set_x, pos1, 1000),
			(position_set_y, pos1, 1000),
			(overlay_set_size, reg0, pos1),

			(str_clear, s0),
			(create_text_overlay, "$g_presentation_obj_troop_select_container", s0, tf_scrollable_style_2),
			(position_set_x, pos1, 285),
			(position_set_y, pos1, 125),
			(overlay_set_position, "$g_presentation_obj_troop_select_container", pos1),
			(position_set_x, pos1, 405),
			(position_set_y, pos1, 500),
			(overlay_set_area_size, "$g_presentation_obj_troop_select_container", pos1),
			(set_container_overlay, "$g_presentation_obj_troop_select_container"),

			(assign, ":cur_y", 450),

			(create_text_overlay, reg0, "str_choose_a_troop", 0),
			(overlay_set_color, reg0, 0xFFFFFF),
			(position_set_x, pos1, 0),
			(position_set_y, pos1, ":cur_y"),
			(overlay_set_position, reg0, pos1),
			(val_sub, ":cur_y", escape_menu_item_height),
			(position_set_y, pos1, ":cur_y"),
			(position_set_x, pos1, 100),

			(multiplayer_get_my_player, ":my_player_no"),
			(player_get_team_no, ":my_team_no", ":my_player_no"),
			(team_get_faction, ":my_faction_no", ":my_team_no"),
			(try_for_range, ":i_multi", multi_data_troop_button_indices_begin, multi_data_troop_button_indices_end),
				(troop_set_slot, "trp_multiplayer_data", ":i_multi", -1),
			(try_end),

			(assign, ":cur_troop_index", 0),
			(try_for_range, ":troop_no", multiplayer_troops_begin, multiplayer_troops_end),
				(store_troop_faction, ":troop_faction", ":troop_no"),
				(eq, ":troop_faction", ":my_faction_no"),
				(str_store_troop_name, s1, ":troop_no"),
				(create_button_overlay, reg0, s1, 0),
				(overlay_set_color, reg0, 0xFFFFFF),
				(store_add, ":button_index_slot", ":cur_troop_index", multi_data_troop_button_indices_begin),
				(troop_set_slot, "trp_multiplayer_data", ":button_index_slot", reg0),
				(position_set_y, pos1, ":cur_y"),
				(overlay_set_position, reg0, pos1),
				(val_sub, ":cur_y", escape_menu_item_height),
				(position_set_y, pos1, ":cur_y"),
				(val_add, ":cur_troop_index", 1),
			(try_end),
			(presentation_set_duration, 999999),
			]),

		(ti_on_presentation_event_state_change,
		 [(store_trigger_param_1, ":object"),
			(multiplayer_get_my_player, ":my_player_no"),
			(player_get_team_no, ":my_team_no", ":my_player_no"),
			(team_get_faction, ":my_faction_no", ":my_team_no"),
			(assign, ":selected_troop_no", -1),
			(assign, ":end_cond", multi_data_troop_button_indices_end),
			(try_for_range, ":i_button", multi_data_troop_button_indices_begin, ":end_cond"),
				(troop_slot_eq, "trp_multiplayer_data", ":i_button", ":object"),
				(store_sub, ":selected_troop_index", ":i_button", multi_data_troop_button_indices_begin),
				(assign, ":end_cond_2", multiplayer_troops_end),
				(try_for_range, ":troop_no", multiplayer_troops_begin, ":end_cond_2"),
					(store_troop_faction, ":troop_faction", ":troop_no"),
					(eq, ":troop_faction", ":my_faction_no"),
					(val_sub, ":selected_troop_index", 1),
					(lt, ":selected_troop_index", 0),
					(assign, ":selected_troop_no", ":troop_no"),
					(assign, ":end_cond_2", 0), #break
				(try_end),
				(try_begin),
					(multiplayer_get_my_troop, ":troop_no"),
					(neq, ":troop_no", ":selected_troop_no"),
					(player_set_troop_id, ":my_player_no", ":selected_troop_no"),
					(multiplayer_send_int_to_server, multiplayer_event_change_troop_id, ":selected_troop_no"),
					(call_script, "script_multiplayer_set_default_item_selections_for_troop", ":selected_troop_no"),
					(call_script, "script_multiplayer_send_item_selections"),
				(try_end),
				(presentation_set_duration, 0),
				(assign, "$g_presentation_state", 0),
				(start_presentation, "prsnt_multiplayer_item_select"),
				(assign, ":end_cond", 0), #break
			(try_end),
			]),
		(ti_on_presentation_run,
		 [
			(try_begin),
				(this_or_next|key_clicked, key_escape),
		(key_clicked, key_xbox_start),
				(multiplayer_get_my_player, ":my_player_no"),
				(is_between, ":my_player_no", 0, multiplayer_max_possible_player_id),
				(multiplayer_get_my_troop, ":my_troop"),
				(try_begin),
					(neg|is_between, ":my_troop", multiplayer_troops_begin, multiplayer_troops_end),
					(player_set_troop_id, ":my_player_no", -1),
					(multiplayer_send_int_to_server, multiplayer_event_change_troop_id, -1),
					(multiplayer_send_int_to_server, multiplayer_event_change_team_no, multi_team_spectator),
					(player_set_team_no, ":my_player_no", multi_team_spectator),
				(try_end),
				(presentation_set_duration, 0),
			(try_end),
			]),
		])
