from header import *


sliders =	(
	"sliders",0,0,[
			(ti_on_presentation_load,
			 [(set_fixed_point_multiplier, 1000),
				(create_slider_overlay, "$g_presentation_obj_sliders_1", 0, 100),
				(create_slider_overlay, "$g_presentation_obj_sliders_2", 0, 100),
				(create_slider_overlay, "$g_presentation_obj_sliders_3", 0, 100),
				(create_slider_overlay, "$g_presentation_obj_sliders_4", 0, 100),
				(assign, reg1, 25),
				(str_store_string, s1, "str_reg1"),
				(create_text_overlay, "$g_presentation_obj_sliders_5", s1),
				(create_text_overlay, "$g_presentation_obj_sliders_6", s1),
				(create_text_overlay, "$g_presentation_obj_sliders_7", s1),
				(create_text_overlay, "$g_presentation_obj_sliders_8", s1),
				(assign, "$g_presentation_obj_sliders_1_val", 25),
				(overlay_set_val, "$g_presentation_obj_sliders_1", 25),
				(assign, "$g_presentation_obj_sliders_2_val", 25),
				(overlay_set_val, "$g_presentation_obj_sliders_2", 25),
				(assign, "$g_presentation_obj_sliders_3_val", 25),
				(overlay_set_val, "$g_presentation_obj_sliders_3", 25),
				(assign, "$g_presentation_obj_sliders_4_val", 25),
				(overlay_set_val, "$g_presentation_obj_sliders_4", 25),
				(position_set_x, pos1, 600),
				(position_set_y, pos1, 200),
				(overlay_set_position, "$g_presentation_obj_sliders_1", pos1),
				(position_set_y, pos1, 300),
				(overlay_set_position, "$g_presentation_obj_sliders_2", pos1),
				(position_set_y, pos1, 400),
				(overlay_set_position, "$g_presentation_obj_sliders_3", pos1),
				(position_set_y, pos1, 500),
				(overlay_set_position, "$g_presentation_obj_sliders_4", pos1),
				(position_set_x, pos1, 800),
				(position_set_y, pos1, 200),
				(overlay_set_position, "$g_presentation_obj_sliders_5", pos1),
				(position_set_y, pos1, 300),
				(overlay_set_position, "$g_presentation_obj_sliders_6", pos1),
				(position_set_y, pos1, 400),
				(overlay_set_position, "$g_presentation_obj_sliders_7", pos1),
				(position_set_y, pos1, 500),
				(overlay_set_position, "$g_presentation_obj_sliders_8", pos1),
				(position_set_x, pos1, 500),
				(overlay_set_size, "$g_presentation_obj_sliders_3", pos1),
				]),
			(ti_on_presentation_run,
			 [
				]),
			(ti_on_presentation_event_state_change,
			 [(store_trigger_param_1, ":object"),
				(store_trigger_param_2, ":value"),
				(assign, ":val_changed", 0),
				(try_begin),
					(eq, ":object", "$g_presentation_obj_sliders_1"),
					(try_begin),
						(neq, "$g_presentation_obj_sliders_1_val", ":value"),
						(assign, "$g_presentation_obj_sliders_1_val", ":value"),
						(assign, ":val_changed", 1),
					(try_end),
				(else_try),
					(eq, ":object", "$g_presentation_obj_sliders_2"),
					(try_begin),
						(neq, "$g_presentation_obj_sliders_2_val", ":value"),
						(assign, "$g_presentation_obj_sliders_2_val", ":value"),
						(assign, ":val_changed", 1),
					(try_end),
				(else_try),
					(eq, ":object", "$g_presentation_obj_sliders_3"),
					(try_begin),
						(neq, "$g_presentation_obj_sliders_3_val", ":value"),
						(assign, "$g_presentation_obj_sliders_3_val", ":value"),
						(assign, ":val_changed", 1),
					(try_end),
				(else_try),
					(eq, ":object", "$g_presentation_obj_sliders_4"),
					(try_begin),
						(neq, "$g_presentation_obj_sliders_4_val", ":value"),
						(assign, "$g_presentation_obj_sliders_4_val", ":value"),
						(assign, ":val_changed", 1),
					(try_end),
				(try_end),
				(try_begin),
					(eq, ":val_changed", 1),
					(assign, ":sum_values", 0),
					(val_add, ":sum_values", "$g_presentation_obj_sliders_1_val"),
					(val_add, ":sum_values", "$g_presentation_obj_sliders_2_val"),
					(val_add, ":sum_values", "$g_presentation_obj_sliders_3_val"),
					(val_add, ":sum_values", "$g_presentation_obj_sliders_4_val"),
					(store_sub, ":difference", 100, ":sum_values"),
					(assign, ":obj_1_new_val", "$g_presentation_obj_sliders_1_val"),
					(assign, ":obj_2_new_val", "$g_presentation_obj_sliders_2_val"),
					(assign, ":obj_3_new_val", "$g_presentation_obj_sliders_3_val"),
					(assign, ":obj_4_new_val", "$g_presentation_obj_sliders_4_val"),
					(assign, ":adder", 1),
					(assign, ":between_1", 0),
					(assign, ":between_2", 100),
					(try_begin),
						(lt, ":difference", 0),
						(val_mul, ":difference", -1),
						(assign, ":adder", -1),
						(assign, ":between_1", 1),
						(assign, ":between_2", 101),
					(try_end),
					(store_sub, ":sum_non_changed_values", ":sum_values", ":value"),
					(val_add, ":sum_non_changed_values", 30),
					(try_for_range, ":unused", 0, ":difference"),
						(store_random_in_range, ":random_no", 0, ":sum_non_changed_values"),
						(try_begin),
							(neq, ":object", "$g_presentation_obj_sliders_1"),
							(val_sub, ":random_no", "$g_presentation_obj_sliders_1_val"),
							(val_sub, ":random_no", 10),
							(lt, ":random_no", 0),
							(is_between, ":obj_1_new_val", ":between_1", ":between_2"),
							(val_add, ":obj_1_new_val", ":adder"),
						(else_try),
							(neq, ":object", "$g_presentation_obj_sliders_2"),
							(val_sub, ":random_no", "$g_presentation_obj_sliders_2_val"),
							(val_sub, ":random_no", 10),
							(lt, ":random_no", 0),
							(is_between, ":obj_2_new_val", ":between_1", ":between_2"),
							(val_add, ":obj_2_new_val", ":adder"),
						(else_try),
							(neq, ":object", "$g_presentation_obj_sliders_3"),
							(val_sub, ":random_no", "$g_presentation_obj_sliders_3_val"),
							(val_sub, ":random_no", 10),
							(lt, ":random_no", 0),
							(is_between, ":obj_3_new_val", ":between_1", ":between_2"),
							(val_add, ":obj_3_new_val", ":adder"),
						(else_try),
							(is_between, ":obj_4_new_val", ":between_1", ":between_2"),
							(val_add, ":obj_4_new_val", ":adder"),
						(else_try),
							(val_add, ":difference", 1),
						(try_end),
					(try_end),
					(assign, "$g_presentation_obj_sliders_1_val", ":obj_1_new_val"),
					(assign, "$g_presentation_obj_sliders_2_val", ":obj_2_new_val"),
					(assign, "$g_presentation_obj_sliders_3_val", ":obj_3_new_val"),
					(assign, "$g_presentation_obj_sliders_4_val", ":obj_4_new_val"),
				(try_end),
				(overlay_set_val, "$g_presentation_obj_sliders_1", "$g_presentation_obj_sliders_1_val"),
				(overlay_set_val, "$g_presentation_obj_sliders_2", "$g_presentation_obj_sliders_2_val"),
				(overlay_set_val, "$g_presentation_obj_sliders_3", "$g_presentation_obj_sliders_3_val"),
				(overlay_set_val, "$g_presentation_obj_sliders_4", "$g_presentation_obj_sliders_4_val"),
				(assign, reg1, "$g_presentation_obj_sliders_1_val"),
				(str_store_string, s1, "str_reg1"),
				(overlay_set_text, "$g_presentation_obj_sliders_5", s1),
				(assign, reg1, "$g_presentation_obj_sliders_2_val"),
				(str_store_string, s1, "str_reg1"),
				(overlay_set_text, "$g_presentation_obj_sliders_6", s1),
				(assign, reg1, "$g_presentation_obj_sliders_3_val"),
				(str_store_string, s1, "str_reg1"),
				(overlay_set_text, "$g_presentation_obj_sliders_7", s1),
				(assign, reg1, "$g_presentation_obj_sliders_4_val"),
				(str_store_string, s1, "str_reg1"),
				(overlay_set_text, "$g_presentation_obj_sliders_8", s1),
				]),
			])